import type { AppLocale } from "@artemis/protocol";

type ComputerUseCopy = {
  paused: string;
  foreground: string;
  background: string;
  resume: string;
  stop: string;
  permissions: string;
  noPermissions: string;
  revoke: string;
};

export const COMPUTER_USE_RESOURCES: Record<AppLocale, ComputerUseCopy> = {
  ar: {
    paused: "متوقف مؤقتًا",
    foreground: "التحكم في الواجهة",
    background: "التحكم في الخلفية",
    resume: "استئناف",
    stop: "إيقاف",
    permissions: "أذونات التطبيقات",
    noPermissions: "لا توجد أذونات محفوظة",
    revoke: "إلغاء الإذن",
  },
  de: {
    paused: "Pausiert",
    foreground: "Bedienung im Vordergrund",
    background: "Bedienung im Hintergrund",
    resume: "Fortsetzen",
    stop: "Stoppen",
    permissions: "App-Berechtigungen",
    noPermissions: "Keine gespeicherten App-Berechtigungen",
    revoke: "Widerrufen",
  },
  en: {
    paused: "Paused",
    foreground: "Using foreground",
    background: "Using background",
    resume: "Resume",
    stop: "Stop",
    permissions: "App permissions",
    noPermissions: "No remembered app permissions",
    revoke: "Revoke",
  },
  es: {
    paused: "En pausa",
    foreground: "Usando el primer plano",
    background: "Usando el segundo plano",
    resume: "Reanudar",
    stop: "Detener",
    permissions: "Permisos de aplicaciones",
    noPermissions: "No hay permisos guardados",
    revoke: "Revocar",
  },
  fr: {
    paused: "En pause",
    foreground: "Utilisation au premier plan",
    background: "Utilisation en arrière-plan",
    resume: "Reprendre",
    stop: "Arrêter",
    permissions: "Autorisations des applications",
    noPermissions: "Aucune autorisation enregistrée",
    revoke: "Révoquer",
  },
  hi: {
    paused: "रुका हुआ",
    foreground: "अग्रभूमि में उपयोग",
    background: "पृष्ठभूमि में उपयोग",
    resume: "जारी रखें",
    stop: "रोकें",
    permissions: "ऐप अनुमतियाँ",
    noPermissions: "कोई सहेजी गई अनुमति नहीं",
    revoke: "रद्द करें",
  },
  id: {
    paused: "Dijeda",
    foreground: "Menggunakan latar depan",
    background: "Menggunakan latar belakang",
    resume: "Lanjutkan",
    stop: "Hentikan",
    permissions: "Izin aplikasi",
    noPermissions: "Tidak ada izin aplikasi tersimpan",
    revoke: "Cabut",
  },
  it: {
    paused: "In pausa",
    foreground: "Uso in primo piano",
    background: "Uso in background",
    resume: "Riprendi",
    stop: "Interrompi",
    permissions: "Permessi delle app",
    noPermissions: "Nessun permesso salvato",
    revoke: "Revoca",
  },
  ja: {
    paused: "一時停止中",
    foreground: "前面で操作中",
    background: "バックグラウンドで操作中",
    resume: "再開",
    stop: "停止",
    permissions: "アプリの許可",
    noPermissions: "保存されたアプリの許可はありません",
    revoke: "取り消す",
  },
  ko: {
    paused: "일시 중지됨",
    foreground: "전면에서 제어 중",
    background: "백그라운드에서 제어 중",
    resume: "재개",
    stop: "중지",
    permissions: "앱 권한",
    noPermissions: "저장된 앱 권한이 없습니다",
    revoke: "취소",
  },
  "pt-BR": {
    paused: "Pausado",
    foreground: "Usando em primeiro plano",
    background: "Usando em segundo plano",
    resume: "Retomar",
    stop: "Parar",
    permissions: "Permissões de apps",
    noPermissions: "Nenhuma permissão salva",
    revoke: "Revogar",
  },
  ru: {
    paused: "Приостановлено",
    foreground: "Работа на переднем плане",
    background: "Работа в фоне",
    resume: "Продолжить",
    stop: "Остановить",
    permissions: "Разрешения приложений",
    noPermissions: "Нет сохранённых разрешений",
    revoke: "Отозвать",
  },
  "zh-CN": {
    paused: "已暂停",
    foreground: "正在前台操作",
    background: "正在后台操作",
    resume: "恢复",
    stop: "停止",
    permissions: "应用授权",
    noPermissions: "没有长期授权的应用",
    revoke: "撤销",
  },
  "zh-TW": {
    paused: "已暫停",
    foreground: "正在前景操作",
    background: "正在背景操作",
    resume: "恢復",
    stop: "停止",
    permissions: "應用程式授權",
    noPermissions: "沒有長期授權的應用程式",
    revoke: "撤銷",
  },
};
