import type { AppLocale } from "@artemis/protocol";
const rows: Record<AppLocale, readonly string[]> = {
  en: [
    "Connect",
    "Disconnect",
    "Cancel",
    "Reconnect",
    "Email",
    "Authorization code",
    "Copy code",
    "Install a connector from your plugin marketplace to get started.",
    "Enable the desktop MCP server in Figma → Dev Mode, then connect.",
    "Sign in to mail.qq.com in your desktop browser. Open Settings → Account (or Account & Security).\nFind the POP3/IMAP/SMTP services and enable IMAP/SMTP. If already enabled, choose Generate authorization code.\nComplete the security verification shown by QQ Mail. Paste the generated 16-letter code below, together with your full email address. Use this code, not your QQ password.",
    "Disconnected",
    "Connecting",
    "Connected",
    "Authorization required",
    "Unavailable",
  ],
  "zh-CN": [
    "连接",
    "断开连接",
    "取消",
    "重新连接",
    "邮箱",
    "授权码",
    "复制验证码",
    "请先从已配置的插件市场安装连接器。",
    "在 Figma 桌面端的开发模式中开启 MCP 服务，然后连接。",
    "在电脑浏览器登录 QQ 邮箱，进入「设置」→「账户」（部分版本为「账号与安全」）。\n找到「POP3/IMAP/SMTP」相关服务，开启「IMAP/SMTP」。如果已开启，选择「生成授权码」。\n按邮箱提示完成安全验证，复制生成的 16 位字母授权码。回到这里，填写完整邮箱地址并粘贴授权码；不要填写 QQ 登录密码。",
    "未连接",
    "连接中",
    "已连接",
    "需要授权",
    "暂不可用",
  ],
  "zh-TW": [
    "連線",
    "中斷連線",
    "取消",
    "重新連線",
    "電子郵件",
    "授權碼",
    "複製驗證碼",
    "請先從已設定的外掛市集安裝連接器。",
    "在 Figma 桌面版的開發模式中啟用 MCP 服務，再連線。",
    "在電腦瀏覽器登入 QQ 郵箱，進入「設定」→「帳戶」（部分版本為「帳號與安全」）。\n找到「POP3/IMAP/SMTP」相關服務，啟用「IMAP/SMTP」。若已啟用，選擇「產生授權碼」。\n依郵箱提示完成安全驗證，複製產生的 16 位字母授權碼。回到這裡，填寫完整信箱地址並貼上授權碼；請勿填寫 QQ 登入密碼。",
    "未連線",
    "連線中",
    "已連線",
    "需要授權",
    "暫時無法使用",
  ],
  ja: [
    "接続",
    "切断",
    "キャンセル",
    "再接続",
    "メール",
    "認証コード",
    "コードをコピー",
    "プラグインマーケットからコネクターをインストールしてください。",
    "Figma デスクトップの開発モードで MCP サーバーを有効にして接続します。",
    "パソコンのブラウザーで mail.qq.com にログインし、設定 → アカウント（またはアカウントとセキュリティ）を開きます。\nPOP3/IMAP/SMTP サービスから IMAP/SMTP を有効にします。有効な場合は認証コードの生成を選びます。\n画面の案内に従って本人確認を完了し、16文字の認証コードをコピーします。下に完全なメールアドレスとコードを入力してください。QQ のログインパスワードではありません。",
    "未接続",
    "接続中",
    "接続済み",
    "認証が必要",
    "利用不可",
  ],
  ko: [
    "연결",
    "연결 해제",
    "취소",
    "다시 연결",
    "이메일",
    "인증 코드",
    "코드 복사",
    "플러그인 마켓에서 커넥터를 설치하세요.",
    "Figma 데스크톱 개발 모드에서 MCP 서버를 켠 후 연결하세요.",
    "컴퓨터 브라우저에서 mail.qq.com에 로그인하고 설정 → 계정(또는 계정 및 보안)을 엽니다.\nPOP3/IMAP/SMTP 서비스에서 IMAP/SMTP를 켭니다. 이미 켜져 있다면 인증 코드 생성을 선택합니다.\n안내에 따라 보안 인증을 완료하고 생성된 16자리 영문 코드를 복사합니다. 아래에 전체 이메일 주소와 코드를 입력하세요. QQ 로그인 비밀번호가 아닙니다.",
    "연결 안 됨",
    "연결 중",
    "연결됨",
    "인증 필요",
    "사용 불가",
  ],
  es: [
    "Conectar",
    "Desconectar",
    "Cancelar",
    "Reconectar",
    "Correo",
    "Código de autorización",
    "Copiar código",
    "Instala un conector desde tu mercado de complementos.",
    "Activa el servidor MCP en el modo de desarrollo de Figma y conecta.",
    "Accede a mail.qq.com desde un ordenador y abre Ajustes → Cuenta (o Cuenta y seguridad).\nBusca los servicios POP3/IMAP/SMTP y activa IMAP/SMTP. Si ya está activo, elige Generar código de autorización.\nCompleta la verificación indicada y copia el código de 16 letras. Introduce abajo tu dirección de correo completa y el código, no tu contraseña de QQ.",
    "Desconectado",
    "Conectando",
    "Conectado",
    "Autorización necesaria",
    "No disponible",
  ],
  fr: [
    "Connecter",
    "Déconnecter",
    "Annuler",
    "Reconnecter",
    "E-mail",
    "Code d’autorisation",
    "Copier le code",
    "Installez un connecteur depuis votre catalogue de plugins.",
    "Activez le serveur MCP dans le mode développeur de Figma, puis connectez-vous.",
    "Connectez-vous à mail.qq.com sur un ordinateur, puis ouvrez Paramètres → Compte (ou Compte et sécurité).\nDans les services POP3/IMAP/SMTP, activez IMAP/SMTP. Si le service est actif, choisissez de générer un code d’autorisation.\nEffectuez la vérification demandée et copiez le code de 16 lettres. Saisissez ci-dessous votre adresse e-mail complète et ce code, pas votre mot de passe QQ.",
    "Déconnecté",
    "Connexion en cours",
    "Connecté",
    "Autorisation requise",
    "Indisponible",
  ],
  de: [
    "Verbinden",
    "Trennen",
    "Abbrechen",
    "Neu verbinden",
    "E-Mail",
    "Autorisierungscode",
    "Code kopieren",
    "Installieren Sie einen Connector aus Ihrem Plugin-Marktplatz.",
    "Aktivieren Sie den MCP-Server im Entwicklermodus der Figma-Desktop-App.",
    "Melden Sie sich am Computer bei mail.qq.com an. Öffnen Sie Einstellungen → Konto (oder Konto und Sicherheit).\nAktivieren Sie IMAP/SMTP unter den POP3/IMAP/SMTP-Diensten. Ist es bereits aktiv, wählen Sie Autorisierungscode erzeugen.\nFühren Sie die angezeigte Sicherheitsprüfung durch und kopieren Sie den Code mit 16 Buchstaben. Geben Sie unten Ihre vollständige E-Mail-Adresse und diesen Code ein, nicht Ihr QQ-Passwort.",
    "Getrennt",
    "Verbindung wird hergestellt",
    "Verbunden",
    "Autorisierung erforderlich",
    "Nicht verfügbar",
  ],
  "pt-BR": [
    "Conectar",
    "Desconectar",
    "Cancelar",
    "Reconectar",
    "E-mail",
    "Código de autorização",
    "Copiar código",
    "Instale um conector pelo seu catálogo de plugins.",
    "Ative o servidor MCP no modo de desenvolvimento do Figma e conecte.",
    "Entre em mail.qq.com no navegador do computador e abra Configurações → Conta (ou Conta e segurança).\nEncontre os serviços POP3/IMAP/SMTP e ative IMAP/SMTP. Se já estiver ativo, escolha gerar um código de autorização.\nConclua a verificação indicada e copie o código de 16 letras. Preencha abaixo seu endereço de e-mail completo e esse código, não sua senha do QQ.",
    "Desconectado",
    "Conectando",
    "Conectado",
    "Autorização necessária",
    "Indisponível",
  ],
  it: [
    "Connetti",
    "Disconnetti",
    "Annulla",
    "Riconnetti",
    "Email",
    "Codice di autorizzazione",
    "Copia codice",
    "Installa un connettore dal catalogo dei plugin.",
    "Attiva il server MCP nella modalità sviluppatore di Figma e connettiti.",
    "Accedi a mail.qq.com dal computer e apri Impostazioni → Account (o Account e sicurezza).\nTrova i servizi POP3/IMAP/SMTP e attiva IMAP/SMTP. Se è già attivo, scegli di generare un codice di autorizzazione.\nCompleta la verifica indicata e copia il codice di 16 lettere. Inserisci qui sotto il tuo indirizzo email completo e il codice, non la password QQ.",
    "Disconnesso",
    "Connessione in corso",
    "Connesso",
    "Autorizzazione richiesta",
    "Non disponibile",
  ],
  ru: [
    "Подключить",
    "Отключить",
    "Отмена",
    "Переподключить",
    "Почта",
    "Код авторизации",
    "Копировать код",
    "Установите коннектор из каталога плагинов.",
    "Включите MCP-сервер в режиме разработчика настольной Figma и подключитесь.",
    "Откройте mail.qq.com на компьютере, войдите и перейдите в Настройки → Учётная запись (или Учётная запись и безопасность).\nНайдите службы POP3/IMAP/SMTP и включите IMAP/SMTP. Если служба уже включена, выберите создание кода авторизации.\nПройдите проверку по инструкции и скопируйте код из 16 букв. Введите ниже полный адрес почты и этот код, а не пароль QQ.",
    "Отключено",
    "Подключение",
    "Подключено",
    "Нужна авторизация",
    "Недоступно",
  ],
  ar: [
    "اتصال",
    "قطع الاتصال",
    "إلغاء",
    "إعادة الاتصال",
    "البريد الإلكتروني",
    "رمز التفويض",
    "نسخ الرمز",
    "ثبّت موصلاً من سوق الإضافات.",
    "فعّل خادم MCP في وضع المطور في تطبيق Figma ثم اتصل.",
    "سجّل الدخول إلى mail.qq.com من متصفح الكمبيوتر وافتح الإعدادات ← الحساب (أو الحساب والأمان).\nابحث عن خدمات POP3/IMAP/SMTP وفعّل IMAP/SMTP. إذا كانت مفعّلة، اختر إنشاء رمز تفويض.\nأكمل التحقق المطلوب وانسخ الرمز المكوّن من 16 حرفًا. أدخل عنوان بريدك الكامل والرمز أدناه، وليس كلمة مرور QQ.",
    "غير متصل",
    "جارٍ الاتصال",
    "متصل",
    "التفويض مطلوب",
    "غير متاح",
  ],
  hi: [
    "कनेक्ट करें",
    "डिस्कनेक्ट करें",
    "रद्द करें",
    "फिर कनेक्ट करें",
    "ईमेल",
    "प्राधिकरण कोड",
    "कोड कॉपी करें",
    "प्लगइन बाज़ार से कनेक्टर इंस्टॉल करें।",
    "Figma डेस्कटॉप के डेवलपर मोड में MCP सर्वर चालू करके कनेक्ट करें।",
    "कंप्यूटर के ब्राउज़र में mail.qq.com पर लॉग इन करें और सेटिंग → खाता (या खाता और सुरक्षा) खोलें।\nPOP3/IMAP/SMTP सेवाओं में IMAP/SMTP चालू करें। यदि पहले से चालू है, तो प्राधिकरण कोड बनाने का विकल्प चुनें।\nदिखाए गए निर्देशों के अनुसार सुरक्षा सत्यापन पूरा करें और 16 अक्षरों वाला कोड कॉपी करें। नीचे अपना पूरा ईमेल पता और यह कोड भरें, QQ पासवर्ड नहीं।",
    "डिस्कनेक्ट",
    "कनेक्ट हो रहा है",
    "कनेक्टेड",
    "प्राधिकरण आवश्यक",
    "अनुपलब्ध",
  ],
  id: [
    "Hubungkan",
    "Putuskan",
    "Batal",
    "Hubungkan ulang",
    "Email",
    "Kode otorisasi",
    "Salin kode",
    "Pasang konektor dari pasar plugin Anda.",
    "Aktifkan server MCP dalam mode pengembang Figma desktop, lalu hubungkan.",
    "Masuk ke mail.qq.com melalui browser komputer, lalu buka Pengaturan → Akun (atau Akun dan keamanan).\nCari layanan POP3/IMAP/SMTP dan aktifkan IMAP/SMTP. Jika sudah aktif, pilih untuk membuat kode otorisasi.\nSelesaikan verifikasi sesuai petunjuk dan salin kode 16 huruf. Isi alamat email lengkap dan kode tersebut di bawah, bukan kata sandi QQ.",
    "Terputus",
    "Menghubungkan",
    "Terhubung",
    "Otorisasi diperlukan",
    "Tidak tersedia",
  ],
};
const capabilities: Record<AppLocale, readonly [string, string]> = {
  en: ["Read", "Write"],
  "zh-CN": ["读取", "写入"],
  "zh-TW": ["讀取", "寫入"],
  ja: ["読み取り", "書き込み"],
  ko: ["읽기", "쓰기"],
  es: ["Lectura", "Escritura"],
  fr: ["Lecture", "Écriture"],
  de: ["Lesen", "Schreiben"],
  "pt-BR": ["Leitura", "Gravação"],
  it: ["Lettura", "Scrittura"],
  ru: ["Чтение", "Запись"],
  ar: ["قراءة", "كتابة"],
  hi: ["पढ़ना", "लिखना"],
  id: ["Baca", "Tulis"],
};
const qqLinks: Record<AppLocale, readonly [string, string]> = {
  en: ["Open QQ Mail", "Official setup help"],
  "zh-CN": ["打开 QQ 邮箱", "查看官方设置帮助"],
  "zh-TW": ["開啟 QQ 郵箱", "官方設定說明"],
  ja: ["QQ メールを開く", "公式設定ガイド"],
  ko: ["QQ 메일 열기", "공식 설정 도움말"],
  es: ["Abrir QQ Mail", "Ayuda oficial"],
  fr: ["Ouvrir QQ Mail", "Aide officielle"],
  de: ["QQ Mail öffnen", "Offizielle Hilfe"],
  "pt-BR": ["Abrir QQ Mail", "Ajuda oficial"],
  it: ["Apri QQ Mail", "Guida ufficiale"],
  ru: ["Открыть QQ Mail", "Официальная справка"],
  ar: ["فتح QQ Mail", "مساعدة الإعداد الرسمية"],
  hi: ["QQ Mail खोलें", "आधिकारिक सेटअप सहायता"],
  id: ["Buka QQ Mail", "Bantuan pengaturan resmi"],
};
export function connectorCopy(locale: AppLocale) {
  const r = rows[locale];
  return {
    capabilities: {
      read: capabilities[locale][0],
      write: capabilities[locale][1],
    },
    connect: r[0]!,
    disconnect: r[1]!,
    cancel: r[2]!,
    reconnect: r[3]!,
    email: r[4]!,
    code: r[5]!,
    copy: r[6]!,
    empty: r[7]!,
    figma: r[8]!,
    qq: r[9]!,
    qqOpen: qqLinks[locale][0],
    qqHelp: qqLinks[locale][1],
    states: {
      disconnected: r[10]!,
      connecting: r[11]!,
      connected: r[12]!,
      "authorization-required": r[13]!,
      unavailable: r[14]!,
    },
  };
}
