import type { AppLocale } from "@artemis/protocol";
const rows: Record<AppLocale, readonly string[]> = {
  en: [
    "Connect",
    "Disconnect",
    "Cancel",
    "Reconnect",
    "Email",
    "Authorization code",
    "Copy code",
    "Install a connector from your plugin marketplace to get started.",
    "Enable the desktop MCP server in Figma → Dev Mode, then connect.",
    "Enable IMAP/SMTP in QQ Mail and generate a 16-letter authorization code.",
    "Disconnected",
    "Connecting",
    "Connected",
    "Authorization required",
    "Unavailable",
  ],
  "zh-CN": [
    "连接",
    "断开连接",
    "取消",
    "重新连接",
    "邮箱",
    "授权码",
    "复制验证码",
    "请先从已配置的插件市场安装连接器。",
    "在 Figma 桌面端的开发模式中开启 MCP 服务，然后连接。",
    "在 QQ 邮箱中开启 IMAP/SMTP，并生成 16 位授权码。",
    "未连接",
    "连接中",
    "已连接",
    "需要授权",
    "暂不可用",
  ],
  "zh-TW": [
    "連線",
    "中斷連線",
    "取消",
    "重新連線",
    "電子郵件",
    "授權碼",
    "複製驗證碼",
    "請先從已設定的外掛市集安裝連接器。",
    "在 Figma 桌面版的開發模式中啟用 MCP 服務，再連線。",
    "在 QQ 郵箱啟用 IMAP/SMTP，並產生 16 位授權碼。",
    "未連線",
    "連線中",
    "已連線",
    "需要授權",
    "暫時無法使用",
  ],
  ja: [
    "接続",
    "切断",
    "キャンセル",
    "再接続",
    "メール",
    "認証コード",
    "コードをコピー",
    "プラグインマーケットからコネクターをインストールしてください。",
    "Figma デスクトップの開発モードで MCP サーバーを有効にして接続します。",
    "QQ メールで IMAP/SMTP を有効にし、16文字の認証コードを生成します。",
    "未接続",
    "接続中",
    "接続済み",
    "認証が必要",
    "利用不可",
  ],
  ko: [
    "연결",
    "연결 해제",
    "취소",
    "다시 연결",
    "이메일",
    "인증 코드",
    "코드 복사",
    "플러그인 마켓에서 커넥터를 설치하세요.",
    "Figma 데스크톱 개발 모드에서 MCP 서버를 켠 후 연결하세요.",
    "QQ 메일에서 IMAP/SMTP를 켜고 16자리 인증 코드를 생성하세요.",
    "연결 안 됨",
    "연결 중",
    "연결됨",
    "인증 필요",
    "사용 불가",
  ],
  es: [
    "Conectar",
    "Desconectar",
    "Cancelar",
    "Reconectar",
    "Correo",
    "Código de autorización",
    "Copiar código",
    "Instala un conector desde tu mercado de complementos.",
    "Activa el servidor MCP en el modo de desarrollo de Figma y conecta.",
    "Activa IMAP/SMTP en QQ Mail y genera un código de autorización de 16 letras.",
    "Desconectado",
    "Conectando",
    "Conectado",
    "Autorización necesaria",
    "No disponible",
  ],
  fr: [
    "Connecter",
    "Déconnecter",
    "Annuler",
    "Reconnecter",
    "E-mail",
    "Code d’autorisation",
    "Copier le code",
    "Installez un connecteur depuis votre catalogue de plugins.",
    "Activez le serveur MCP dans le mode développeur de Figma, puis connectez-vous.",
    "Activez IMAP/SMTP dans QQ Mail et générez un code d’autorisation de 16 lettres.",
    "Déconnecté",
    "Connexion en cours",
    "Connecté",
    "Autorisation requise",
    "Indisponible",
  ],
  de: [
    "Verbinden",
    "Trennen",
    "Abbrechen",
    "Neu verbinden",
    "E-Mail",
    "Autorisierungscode",
    "Code kopieren",
    "Installieren Sie einen Connector aus Ihrem Plugin-Marktplatz.",
    "Aktivieren Sie den MCP-Server im Entwicklermodus der Figma-Desktop-App.",
    "Aktivieren Sie IMAP/SMTP in QQ Mail und erzeugen Sie einen Autorisierungscode mit 16 Buchstaben.",
    "Getrennt",
    "Verbindung wird hergestellt",
    "Verbunden",
    "Autorisierung erforderlich",
    "Nicht verfügbar",
  ],
  "pt-BR": [
    "Conectar",
    "Desconectar",
    "Cancelar",
    "Reconectar",
    "E-mail",
    "Código de autorização",
    "Copiar código",
    "Instale um conector pelo seu catálogo de plugins.",
    "Ative o servidor MCP no modo de desenvolvimento do Figma e conecte.",
    "Ative IMAP/SMTP no QQ Mail e gere um código de autorização de 16 letras.",
    "Desconectado",
    "Conectando",
    "Conectado",
    "Autorização necessária",
    "Indisponível",
  ],
  it: [
    "Connetti",
    "Disconnetti",
    "Annulla",
    "Riconnetti",
    "Email",
    "Codice di autorizzazione",
    "Copia codice",
    "Installa un connettore dal catalogo dei plugin.",
    "Attiva il server MCP nella modalità sviluppatore di Figma e connettiti.",
    "Attiva IMAP/SMTP in QQ Mail e genera un codice di autorizzazione di 16 lettere.",
    "Disconnesso",
    "Connessione in corso",
    "Connesso",
    "Autorizzazione richiesta",
    "Non disponibile",
  ],
  ru: [
    "Подключить",
    "Отключить",
    "Отмена",
    "Переподключить",
    "Почта",
    "Код авторизации",
    "Копировать код",
    "Установите коннектор из каталога плагинов.",
    "Включите MCP-сервер в режиме разработчика настольной Figma и подключитесь.",
    "Включите IMAP/SMTP в QQ Mail и создайте код авторизации из 16 букв.",
    "Отключено",
    "Подключение",
    "Подключено",
    "Нужна авторизация",
    "Недоступно",
  ],
  ar: [
    "اتصال",
    "قطع الاتصال",
    "إلغاء",
    "إعادة الاتصال",
    "البريد الإلكتروني",
    "رمز التفويض",
    "نسخ الرمز",
    "ثبّت موصلاً من سوق الإضافات.",
    "فعّل خادم MCP في وضع المطور في تطبيق Figma ثم اتصل.",
    "فعّل IMAP/SMTP في QQ Mail وأنشئ رمز تفويض من 16 حرفاً.",
    "غير متصل",
    "جارٍ الاتصال",
    "متصل",
    "التفويض مطلوب",
    "غير متاح",
  ],
  hi: [
    "कनेक्ट करें",
    "डिस्कनेक्ट करें",
    "रद्द करें",
    "फिर कनेक्ट करें",
    "ईमेल",
    "प्राधिकरण कोड",
    "कोड कॉपी करें",
    "प्लगइन बाज़ार से कनेक्टर इंस्टॉल करें।",
    "Figma डेस्कटॉप के डेवलपर मोड में MCP सर्वर चालू करके कनेक्ट करें।",
    "QQ Mail में IMAP/SMTP चालू करें और 16 अक्षरों का प्राधिकरण कोड बनाएं।",
    "डिस्कनेक्ट",
    "कनेक्ट हो रहा है",
    "कनेक्टेड",
    "प्राधिकरण आवश्यक",
    "अनुपलब्ध",
  ],
  id: [
    "Hubungkan",
    "Putuskan",
    "Batal",
    "Hubungkan ulang",
    "Email",
    "Kode otorisasi",
    "Salin kode",
    "Pasang konektor dari pasar plugin Anda.",
    "Aktifkan server MCP dalam mode pengembang Figma desktop, lalu hubungkan.",
    "Aktifkan IMAP/SMTP di QQ Mail dan buat kode otorisasi 16 huruf.",
    "Terputus",
    "Menghubungkan",
    "Terhubung",
    "Otorisasi diperlukan",
    "Tidak tersedia",
  ],
};
const capabilities: Record<AppLocale, readonly [string, string]> = {
  en: ["Read", "Write"],
  "zh-CN": ["读取", "写入"],
  "zh-TW": ["讀取", "寫入"],
  ja: ["読み取り", "書き込み"],
  ko: ["읽기", "쓰기"],
  es: ["Lectura", "Escritura"],
  fr: ["Lecture", "Écriture"],
  de: ["Lesen", "Schreiben"],
  "pt-BR": ["Leitura", "Gravação"],
  it: ["Lettura", "Scrittura"],
  ru: ["Чтение", "Запись"],
  ar: ["قراءة", "كتابة"],
  hi: ["पढ़ना", "लिखना"],
  id: ["Baca", "Tulis"],
};
export function connectorCopy(locale: AppLocale) {
  const r = rows[locale];
  return {
    capabilities: {
      read: capabilities[locale][0],
      write: capabilities[locale][1],
    },
    connect: r[0]!,
    disconnect: r[1]!,
    cancel: r[2]!,
    reconnect: r[3]!,
    email: r[4]!,
    code: r[5]!,
    copy: r[6]!,
    empty: r[7]!,
    figma: r[8]!,
    qq: r[9]!,
    states: {
      disconnected: r[10]!,
      connecting: r[11]!,
      connected: r[12]!,
      "authorization-required": r[13]!,
      unavailable: r[14]!,
    },
  };
}
