import type { AppLocale } from "@artemis/protocol";

export const GOAL_RESOURCES = {
  en: {
    objectiveRequired: "A Goal objective is required.",
    budgetInvalid: "--token-budget must be a positive integer.",
    active: "Goal in progress",
    paused: "Paused goal",
    blocked: "Goal stalled",
    usageLimited: "Goal usage limited",
    budgetLimited: "Goal limited",
    complete: "Goal achieved",
    pause: "Pause goal",
    resume: "Resume goal",
    edit: "Edit goal",
    clear: "Clear goal",
    goal: "Goal",
    loading: "Loading goal…",
    updatedNow: "Updated just now",
    updatedMinutes: "Updated {{count}} min ago",
    revert: "Revert",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    stale: "This goal changed elsewhere. Reload to get the latest version.",
    staleDirty: "You have unsaved changes; reloading will discard them.",
    loadFailed: "Failed to load the goal.",
    saveFailed: "Failed to save the goal.",
    retryLoad: "Retry loading",
    retrySave: "Retry saving",
    reload: "Reload",
    reloadConfirm: "Discard changes and reload",
    taskGoal: "Task goal",
    statusActive: "Active",
    statusPaused: "Paused",
    statusBlocked: "Blocked",
    statusUsageLimited: "Usage limited",
    statusBudgetLimited: "Budget reached",
    statusComplete: "Complete",
    elapsed: "Elapsed",
    noBudget: "No budget set",
    previewFailed: "Unable to load the full goal. Open the editor to retry.",
    previewLoading: "Loading full goal…",
    running: "Running",
  },
  "zh-CN": {
    objectiveRequired: "请填写目标内容。",
    budgetInvalid: "--token-budget 必须是正整数。",
    active: "进行中的目标",
    paused: "已暂停的目标",
    blocked: "目标已停滞",
    usageLimited: "目标使用受限",
    budgetLimited: "目标受限",
    complete: "已达成目标",
    pause: "暂停目标",
    resume: "继续目标",
    edit: "编辑目标",
    clear: "清除目标",
    goal: "目标",
    loading: "正在载入目标…",
    updatedNow: "刚刚更新",
    updatedMinutes: "{{count}} 分钟前更新",
    revert: "还原",
    save: "保存",
    saving: "正在保存…",
    saved: "已保存",
    stale: "此目标已在其他位置发生变化。重新加载以获取最新版本。",
    staleDirty: "你有未保存的修改，重新加载将丢弃它们。",
    loadFailed: "载入目标内容失败。",
    saveFailed: "保存目标内容失败。",
    retryLoad: "重试加载",
    retrySave: "重试保存",
    reload: "重新加载",
    reloadConfirm: "放弃修改并重新加载",
    taskGoal: "任务目标",
    statusActive: "进行中",
    statusPaused: "已暂停",
    statusBlocked: "已阻塞",
    statusUsageLimited: "用量受限",
    statusBudgetLimited: "预算已用完",
    statusComplete: "已完成",
    elapsed: "已用时",
    noBudget: "预算未设置",
    previewFailed: "无法载入完整目标，请点击编辑重试。",
    previewLoading: "正在载入完整目标…",
    running: "运行中",
  },
  "zh-TW": {
    objectiveRequired: "請填寫目標內容。",
    budgetInvalid: "--token-budget 必須是正整數。",
    active: "進行中的目標",
    paused: "已暫停的目標",
    blocked: "目標已停滯",
    usageLimited: "目標使用受限",
    budgetLimited: "目標受限",
    complete: "已達成目標",
    pause: "暫停目標",
    resume: "繼續目標",
    edit: "編輯目標",
    clear: "清除目標",
    goal: "目標",
    loading: "正在載入目標…",
    updatedNow: "剛剛更新",
    updatedMinutes: "{{count}} 分鐘前更新",
    revert: "還原",
    save: "儲存",
    saving: "正在儲存…",
    saved: "已儲存",
    stale: "此目標已在其他位置變更。請重新載入以取得最新版本。",
    staleDirty: "你有尚未儲存的修改，重新載入將捨棄這些修改。",
    loadFailed: "載入目標內容失敗。",
    saveFailed: "儲存目標內容失敗。",
    retryLoad: "重試載入",
    retrySave: "重試儲存",
    reload: "重新載入",
    reloadConfirm: "捨棄修改並重新載入",
    taskGoal: "任務目標",
    statusActive: "進行中",
    statusPaused: "已暫停",
    statusBlocked: "已受阻",
    statusUsageLimited: "用量受限",
    statusBudgetLimited: "預算已用完",
    statusComplete: "已完成",
    elapsed: "已用時間",
    noBudget: "尚未設定預算",
    previewFailed: "無法載入完整目標，請點擊編輯重試。",
    previewLoading: "正在載入完整目標…",
    running: "執行中",
  },
  ja: {
    objectiveRequired: "目標の内容を入力してください。",
    budgetInvalid: "--token-budget は正の整数で指定してください。",
    active: "進行中の目標",
    paused: "一時停止中の目標",
    blocked: "目標の進行が停滞しています",
    usageLimited: "目標の利用量が制限されています",
    budgetLimited: "目標が制限されています",
    complete: "達成した目標",
    pause: "目標を一時停止",
    resume: "目標を再開",
    edit: "目標を編集",
    clear: "目標をクリア",
    goal: "目標",
    loading: "目標を読み込み中…",
    updatedNow: "たった今更新",
    updatedMinutes: "{{count}} 分前に更新",
    revert: "元に戻す",
    save: "保存",
    saving: "保存中…",
    saved: "保存済み",
    stale:
      "この目標は別の場所で変更されました。再読み込みして最新版を取得してください。",
    staleDirty: "未保存の変更があります。再読み込みすると変更は破棄されます。",
    loadFailed: "目標の読み込みに失敗しました。",
    saveFailed: "目標の保存に失敗しました。",
    retryLoad: "読み込みを再試行",
    retrySave: "保存を再試行",
    reload: "再読み込み",
    reloadConfirm: "変更を破棄して再読み込み",
    taskGoal: "タスクの目標",
    statusActive: "進行中",
    statusPaused: "一時停止中",
    statusBlocked: "進行不能",
    statusUsageLimited: "利用量制限",
    statusBudgetLimited: "予算を使い切りました",
    statusComplete: "完了",
    elapsed: "経過時間",
    noBudget: "予算未設定",
    previewFailed:
      "目標の全文を読み込めません。エディターを開いて再試行してください。",
    previewLoading: "目標の全文を読み込み中…",
    running: "実行中",
  },
  ko: {
    objectiveRequired: "목표 내용을 입력하세요.",
    budgetInvalid: "--token-budget은 양의 정수여야 합니다.",
    active: "진행 중인 목표",
    paused: "일시 중지된 목표",
    blocked: "목표 진행이 멈췄습니다",
    usageLimited: "목표 사용량 제한",
    budgetLimited: "제한된 목표",
    complete: "달성한 목표",
    pause: "목표 일시 중지",
    resume: "목표 재개",
    edit: "목표 편집",
    clear: "목표 지우기",
    goal: "목표",
    loading: "목표 불러오는 중…",
    updatedNow: "방금 업데이트됨",
    updatedMinutes: "{{count}}분 전에 업데이트됨",
    revert: "되돌리기",
    save: "저장",
    saving: "저장 중…",
    saved: "저장됨",
    stale:
      "다른 곳에서 이 목표가 변경되었습니다. 최신 버전을 가져오려면 다시 불러오세요.",
    staleDirty:
      "저장하지 않은 변경 사항이 있습니다. 다시 불러오면 변경 사항이 삭제됩니다.",
    loadFailed: "목표 내용을 불러오지 못했습니다.",
    saveFailed: "목표 내용을 저장하지 못했습니다.",
    retryLoad: "불러오기 재시도",
    retrySave: "저장 재시도",
    reload: "다시 불러오기",
    reloadConfirm: "변경 사항을 버리고 다시 불러오기",
    taskGoal: "작업 목표",
    statusActive: "진행 중",
    statusPaused: "일시 중지됨",
    statusBlocked: "진행 불가",
    statusUsageLimited: "사용량 제한",
    statusBudgetLimited: "예산 소진",
    statusComplete: "완료",
    elapsed: "경과 시간",
    noBudget: "예산 미설정",
    previewFailed:
      "전체 목표를 불러올 수 없습니다. 편집기를 열어 다시 시도하세요.",
    previewLoading: "전체 목표 불러오는 중…",
    running: "실행 중",
  },
  es: {
    objectiveRequired: "Introduce el objetivo.",
    budgetInvalid: "--token-budget debe ser un número entero positivo.",
    active: "Objetivo en curso",
    paused: "Objetivo pausado",
    blocked: "Objetivo estancado",
    usageLimited: "Uso del objetivo limitado",
    budgetLimited: "Objetivo limitado",
    complete: "Objetivo alcanzado",
    pause: "Pausar objetivo",
    resume: "Reanudar objetivo",
    edit: "Editar objetivo",
    clear: "Borrar objetivo",
    goal: "Objetivo",
    loading: "Cargando objetivo…",
    updatedNow: "Actualizado ahora mismo",
    updatedMinutes: "Actualizado hace {{count}} min",
    revert: "Revertir",
    save: "Guardar",
    saving: "Guardando…",
    saved: "Guardado",
    stale:
      "Este objetivo cambió en otro lugar. Recarga para obtener la última versión.",
    staleDirty: "Tienes cambios sin guardar; se perderán al recargar.",
    loadFailed: "No se pudo cargar el objetivo.",
    saveFailed: "No se pudo guardar el objetivo.",
    retryLoad: "Reintentar la carga",
    retrySave: "Reintentar el guardado",
    reload: "Recargar",
    reloadConfirm: "Descartar cambios y recargar",
    taskGoal: "Objetivo de la tarea",
    statusActive: "En curso",
    statusPaused: "Pausado",
    statusBlocked: "Bloqueado",
    statusUsageLimited: "Uso limitado",
    statusBudgetLimited: "Presupuesto agotado",
    statusComplete: "Completado",
    elapsed: "Tiempo transcurrido",
    noBudget: "Sin presupuesto definido",
    previewFailed:
      "No se puede cargar el objetivo completo. Abre el editor para reintentar.",
    previewLoading: "Cargando el objetivo completo…",
    running: "En ejecución",
  },
  fr: {
    objectiveRequired: "Veuillez saisir l’objectif.",
    budgetInvalid: "--token-budget doit être un entier positif.",
    active: "Objectif en cours",
    paused: "Objectif en pause",
    blocked: "Objectif au point mort",
    usageLimited: "Utilisation de l’objectif limitée",
    budgetLimited: "Objectif limité",
    complete: "Objectif atteint",
    pause: "Mettre l’objectif en pause",
    resume: "Reprendre l’objectif",
    edit: "Modifier l’objectif",
    clear: "Effacer l’objectif",
    goal: "Objectif",
    loading: "Chargement de l’objectif…",
    updatedNow: "Mis à jour à l’instant",
    updatedMinutes: "Mis à jour il y a {{count}} min",
    revert: "Rétablir",
    save: "Enregistrer",
    saving: "Enregistrement…",
    saved: "Enregistré",
    stale:
      "Cet objectif a été modifié ailleurs. Rechargez pour obtenir la dernière version.",
    staleDirty:
      "Vous avez des modifications non enregistrées ; elles seront perdues lors du rechargement.",
    loadFailed: "Impossible de charger l’objectif.",
    saveFailed: "Impossible d’enregistrer l’objectif.",
    retryLoad: "Réessayer le chargement",
    retrySave: "Réessayer l’enregistrement",
    reload: "Recharger",
    reloadConfirm: "Abandonner les modifications et recharger",
    taskGoal: "Objectif de la tâche",
    statusActive: "En cours",
    statusPaused: "En pause",
    statusBlocked: "Bloqué",
    statusUsageLimited: "Utilisation limitée",
    statusBudgetLimited: "Budget épuisé",
    statusComplete: "Terminé",
    elapsed: "Temps écoulé",
    noBudget: "Aucun budget défini",
    previewFailed:
      "Impossible de charger l’objectif complet. Ouvrez l’éditeur pour réessayer.",
    previewLoading: "Chargement de l’objectif complet…",
    running: "En cours d’exécution",
  },
  de: {
    objectiveRequired: "Bitte gib ein Ziel ein.",
    budgetInvalid: "--token-budget muss eine positive ganze Zahl sein.",
    active: "Ziel in Bearbeitung",
    paused: "Pausiertes Ziel",
    blocked: "Zielfortschritt stagniert",
    usageLimited: "Nutzung für das Ziel begrenzt",
    budgetLimited: "Ziel eingeschränkt",
    complete: "Ziel erreicht",
    pause: "Ziel pausieren",
    resume: "Ziel fortsetzen",
    edit: "Ziel bearbeiten",
    clear: "Ziel entfernen",
    goal: "Ziel",
    loading: "Ziel wird geladen…",
    updatedNow: "Gerade aktualisiert",
    updatedMinutes: "Vor {{count}} Min. aktualisiert",
    revert: "Zurücksetzen",
    save: "Speichern",
    saving: "Wird gespeichert…",
    saved: "Gespeichert",
    stale:
      "Dieses Ziel wurde an anderer Stelle geändert. Lade es erneut, um die aktuelle Version zu erhalten.",
    staleDirty:
      "Du hast ungespeicherte Änderungen. Beim Neuladen werden sie verworfen.",
    loadFailed: "Das Ziel konnte nicht geladen werden.",
    saveFailed: "Das Ziel konnte nicht gespeichert werden.",
    retryLoad: "Laden erneut versuchen",
    retrySave: "Speichern erneut versuchen",
    reload: "Neu laden",
    reloadConfirm: "Änderungen verwerfen und neu laden",
    taskGoal: "Aufgabenziel",
    statusActive: "In Bearbeitung",
    statusPaused: "Pausiert",
    statusBlocked: "Blockiert",
    statusUsageLimited: "Nutzung begrenzt",
    statusBudgetLimited: "Budget aufgebraucht",
    statusComplete: "Abgeschlossen",
    elapsed: "Verstrichene Zeit",
    noBudget: "Kein Budget festgelegt",
    previewFailed:
      "Das vollständige Ziel konnte nicht geladen werden. Öffne den Editor, um es erneut zu versuchen.",
    previewLoading: "Vollständiges Ziel wird geladen…",
    running: "Wird ausgeführt",
  },
  "pt-BR": {
    objectiveRequired: "Informe o objetivo.",
    budgetInvalid: "--token-budget deve ser um número inteiro positivo.",
    active: "Objetivo em andamento",
    paused: "Objetivo pausado",
    blocked: "Objetivo estagnado",
    usageLimited: "Uso do objetivo limitado",
    budgetLimited: "Objetivo limitado",
    complete: "Objetivo alcançado",
    pause: "Pausar objetivo",
    resume: "Retomar objetivo",
    edit: "Editar objetivo",
    clear: "Limpar objetivo",
    goal: "Objetivo",
    loading: "Carregando objetivo…",
    updatedNow: "Atualizado agora",
    updatedMinutes: "Atualizado há {{count}} min",
    revert: "Reverter",
    save: "Salvar",
    saving: "Salvando…",
    saved: "Salvo",
    stale:
      "Este objetivo foi alterado em outro lugar. Recarregue para obter a versão mais recente.",
    staleDirty:
      "Há alterações não salvas; elas serão descartadas ao recarregar.",
    loadFailed: "Não foi possível carregar o objetivo.",
    saveFailed: "Não foi possível salvar o objetivo.",
    retryLoad: "Tentar carregar novamente",
    retrySave: "Tentar salvar novamente",
    reload: "Recarregar",
    reloadConfirm: "Descartar alterações e recarregar",
    taskGoal: "Objetivo da tarefa",
    statusActive: "Em andamento",
    statusPaused: "Pausado",
    statusBlocked: "Bloqueado",
    statusUsageLimited: "Uso limitado",
    statusBudgetLimited: "Orçamento esgotado",
    statusComplete: "Concluído",
    elapsed: "Tempo decorrido",
    noBudget: "Nenhum orçamento definido",
    previewFailed:
      "Não foi possível carregar o objetivo completo. Abra o editor para tentar novamente.",
    previewLoading: "Carregando objetivo completo…",
    running: "Em execução",
  },
  it: {
    objectiveRequired: "Inserisci l’obiettivo.",
    budgetInvalid: "--token-budget deve essere un numero intero positivo.",
    active: "Obiettivo in corso",
    paused: "Obiettivo in pausa",
    blocked: "Obiettivo fermo",
    usageLimited: "Utilizzo dell’obiettivo limitato",
    budgetLimited: "Obiettivo limitato",
    complete: "Obiettivo raggiunto",
    pause: "Metti in pausa l’obiettivo",
    resume: "Riprendi l’obiettivo",
    edit: "Modifica l’obiettivo",
    clear: "Cancella l’obiettivo",
    goal: "Obiettivo",
    loading: "Caricamento dell’obiettivo…",
    updatedNow: "Aggiornato ora",
    updatedMinutes: "Aggiornato {{count}} min fa",
    revert: "Ripristina",
    save: "Salva",
    saving: "Salvataggio…",
    saved: "Salvato",
    stale:
      "Questo obiettivo è stato modificato altrove. Ricarica per ottenere la versione più recente.",
    staleDirty: "Ci sono modifiche non salvate; ricaricando verranno perse.",
    loadFailed: "Impossibile caricare l’obiettivo.",
    saveFailed: "Impossibile salvare l’obiettivo.",
    retryLoad: "Riprova il caricamento",
    retrySave: "Riprova il salvataggio",
    reload: "Ricarica",
    reloadConfirm: "Scarta le modifiche e ricarica",
    taskGoal: "Obiettivo dell’attività",
    statusActive: "In corso",
    statusPaused: "In pausa",
    statusBlocked: "Bloccato",
    statusUsageLimited: "Utilizzo limitato",
    statusBudgetLimited: "Budget esaurito",
    statusComplete: "Completato",
    elapsed: "Tempo trascorso",
    noBudget: "Nessun budget impostato",
    previewFailed:
      "Impossibile caricare l’obiettivo completo. Apri l’editor per riprovare.",
    previewLoading: "Caricamento dell’obiettivo completo…",
    running: "In esecuzione",
  },
  ru: {
    objectiveRequired: "Укажите цель.",
    budgetInvalid: "--token-budget должен быть положительным целым числом.",
    active: "Цель в работе",
    paused: "Приостановленная цель",
    blocked: "Работа над целью остановилась",
    usageLimited: "Использование ресурсов для цели ограничено",
    budgetLimited: "Цель ограничена",
    complete: "Цель достигнута",
    pause: "Приостановить цель",
    resume: "Продолжить цель",
    edit: "Изменить цель",
    clear: "Удалить цель",
    goal: "Цель",
    loading: "Загрузка цели…",
    updatedNow: "Обновлено только что",
    updatedMinutes: "Обновлено {{count}} мин назад",
    revert: "Отменить изменения",
    save: "Сохранить",
    saving: "Сохранение…",
    saved: "Сохранено",
    stale:
      "Эта цель изменена в другом месте. Перезагрузите её, чтобы получить последнюю версию.",
    staleDirty:
      "Есть несохранённые изменения. При перезагрузке они будут потеряны.",
    loadFailed: "Не удалось загрузить цель.",
    saveFailed: "Не удалось сохранить цель.",
    retryLoad: "Повторить загрузку",
    retrySave: "Повторить сохранение",
    reload: "Перезагрузить",
    reloadConfirm: "Отменить изменения и перезагрузить",
    taskGoal: "Цель задачи",
    statusActive: "В работе",
    statusPaused: "Приостановлено",
    statusBlocked: "Заблокировано",
    statusUsageLimited: "Использование ограничено",
    statusBudgetLimited: "Бюджет исчерпан",
    statusComplete: "Завершено",
    elapsed: "Прошло времени",
    noBudget: "Бюджет не задан",
    previewFailed:
      "Не удалось загрузить полный текст цели. Откройте редактор, чтобы повторить попытку.",
    previewLoading: "Загрузка полного текста цели…",
    running: "Выполняется",
  },
  ar: {
    objectiveRequired: "يرجى إدخال الهدف.",
    budgetInvalid: "يجب أن تكون قيمة --token-budget عددًا صحيحًا موجبًا.",
    active: "هدف قيد التنفيذ",
    paused: "هدف متوقف مؤقتًا",
    blocked: "توقف التقدم نحو الهدف",
    usageLimited: "استخدام الهدف محدود",
    budgetLimited: "هدف مقيّد",
    complete: "تم تحقيق الهدف",
    pause: "إيقاف الهدف مؤقتًا",
    resume: "استئناف الهدف",
    edit: "تعديل الهدف",
    clear: "مسح الهدف",
    goal: "الهدف",
    loading: "جارٍ تحميل الهدف…",
    updatedNow: "تم التحديث للتو",
    updatedMinutes: "تم التحديث قبل {{count}} د",
    revert: "تراجع عن التغييرات",
    save: "حفظ",
    saving: "جارٍ الحفظ…",
    saved: "تم الحفظ",
    stale: "تم تغيير هذا الهدف في مكان آخر. أعد التحميل للحصول على أحدث نسخة.",
    staleDirty: "لديك تغييرات غير محفوظة؛ ستُفقد عند إعادة التحميل.",
    loadFailed: "تعذّر تحميل محتوى الهدف.",
    saveFailed: "تعذّر حفظ محتوى الهدف.",
    retryLoad: "إعادة محاولة التحميل",
    retrySave: "إعادة محاولة الحفظ",
    reload: "إعادة التحميل",
    reloadConfirm: "تجاهل التغييرات وإعادة التحميل",
    taskGoal: "هدف المهمة",
    statusActive: "قيد التنفيذ",
    statusPaused: "متوقف مؤقتًا",
    statusBlocked: "متعذّر التقدم",
    statusUsageLimited: "الاستخدام محدود",
    statusBudgetLimited: "نفدت الميزانية",
    statusComplete: "مكتمل",
    elapsed: "الوقت المنقضي",
    noBudget: "لم تُحدّد ميزانية",
    previewFailed: "تعذّر تحميل الهدف كاملًا. افتح المحرر لإعادة المحاولة.",
    previewLoading: "جارٍ تحميل الهدف كاملًا…",
    running: "قيد التشغيل",
  },
  hi: {
    objectiveRequired: "कृपया लक्ष्य दर्ज करें।",
    budgetInvalid: "--token-budget एक धनात्मक पूर्णांक होना चाहिए।",
    active: "लक्ष्य पर काम जारी है",
    paused: "रुका हुआ लक्ष्य",
    blocked: "लक्ष्य की प्रगति रुक गई है",
    usageLimited: "लक्ष्य का उपयोग सीमित है",
    budgetLimited: "सीमित लक्ष्य",
    complete: "लक्ष्य प्राप्त हुआ",
    pause: "लक्ष्य रोकें",
    resume: "लक्ष्य फिर शुरू करें",
    edit: "लक्ष्य संपादित करें",
    clear: "लक्ष्य हटाएँ",
    goal: "लक्ष्य",
    loading: "लक्ष्य लोड हो रहा है…",
    updatedNow: "अभी अपडेट हुआ",
    updatedMinutes: "{{count}} मिनट पहले अपडेट हुआ",
    revert: "बदलाव वापस लें",
    save: "सहेजें",
    saving: "सहेजा जा रहा है…",
    saved: "सहेजा गया",
    stale:
      "यह लक्ष्य कहीं और बदल गया है। नवीनतम संस्करण पाने के लिए फिर से लोड करें।",
    staleDirty:
      "आपके कुछ बदलाव सहेजे नहीं गए हैं; फिर से लोड करने पर वे मिट जाएँगे।",
    loadFailed: "लक्ष्य लोड नहीं हो सका।",
    saveFailed: "लक्ष्य सहेजा नहीं जा सका।",
    retryLoad: "लोड करने की फिर कोशिश करें",
    retrySave: "सहेजने की फिर कोशिश करें",
    reload: "फिर से लोड करें",
    reloadConfirm: "बदलाव छोड़कर फिर से लोड करें",
    taskGoal: "कार्य का लक्ष्य",
    statusActive: "प्रगति में",
    statusPaused: "रुका हुआ",
    statusBlocked: "अवरुद्ध",
    statusUsageLimited: "उपयोग सीमित",
    statusBudgetLimited: "बजट खत्म हो गया",
    statusComplete: "पूरा हुआ",
    elapsed: "बीता समय",
    noBudget: "बजट तय नहीं है",
    previewFailed:
      "पूरा लक्ष्य लोड नहीं हो सका। फिर कोशिश करने के लिए संपादक खोलें।",
    previewLoading: "पूरा लक्ष्य लोड हो रहा है…",
    running: "चल रहा है",
  },
  id: {
    objectiveRequired: "Masukkan tujuan.",
    budgetInvalid: "--token-budget harus berupa bilangan bulat positif.",
    active: "Tujuan sedang dikerjakan",
    paused: "Tujuan dijeda",
    blocked: "Kemajuan tujuan terhenti",
    usageLimited: "Penggunaan tujuan dibatasi",
    budgetLimited: "Tujuan dibatasi",
    complete: "Tujuan tercapai",
    pause: "Jeda tujuan",
    resume: "Lanjutkan tujuan",
    edit: "Edit tujuan",
    clear: "Hapus tujuan",
    goal: "Tujuan",
    loading: "Memuat tujuan…",
    updatedNow: "Baru saja diperbarui",
    updatedMinutes: "Diperbarui {{count}} menit lalu",
    revert: "Kembalikan",
    save: "Simpan",
    saving: "Menyimpan…",
    saved: "Tersimpan",
    stale:
      "Tujuan ini diubah di tempat lain. Muat ulang untuk mendapatkan versi terbaru.",
    staleDirty:
      "Ada perubahan yang belum disimpan; memuat ulang akan membuangnya.",
    loadFailed: "Gagal memuat isi tujuan.",
    saveFailed: "Gagal menyimpan isi tujuan.",
    retryLoad: "Coba muat lagi",
    retrySave: "Coba simpan lagi",
    reload: "Muat ulang",
    reloadConfirm: "Buang perubahan dan muat ulang",
    taskGoal: "Tujuan tugas",
    statusActive: "Sedang dikerjakan",
    statusPaused: "Dijeda",
    statusBlocked: "Terhambat",
    statusUsageLimited: "Penggunaan dibatasi",
    statusBudgetLimited: "Anggaran habis",
    statusComplete: "Selesai",
    elapsed: "Waktu berlalu",
    noBudget: "Anggaran belum ditetapkan",
    previewFailed:
      "Tidak dapat memuat tujuan lengkap. Buka editor untuk mencoba lagi.",
    previewLoading: "Memuat tujuan lengkap…",
    running: "Berjalan",
  },
} satisfies Record<
  AppLocale,
  Record<
    | "objectiveRequired"
    | "budgetInvalid"
    | "active"
    | "paused"
    | "blocked"
    | "usageLimited"
    | "budgetLimited"
    | "complete"
    | "pause"
    | "resume"
    | "edit"
    | "clear"
    | "goal"
    | "loading"
    | "updatedNow"
    | "updatedMinutes"
    | "revert"
    | "save"
    | "saving"
    | "saved"
    | "stale"
    | "staleDirty"
    | "loadFailed"
    | "saveFailed"
    | "retryLoad"
    | "retrySave"
    | "reload"
    | "reloadConfirm"
    | "taskGoal"
    | "statusActive"
    | "statusPaused"
    | "statusBlocked"
    | "statusUsageLimited"
    | "statusBudgetLimited"
    | "statusComplete"
    | "elapsed"
    | "noBudget"
    | "previewFailed"
    | "previewLoading"
    | "running",
    string
  >
>;
