import type { AppLocale } from "@artemis/protocol";
const resources = {
  ja: {
    "Hooks.summary": "ローカルプロジェクトで実行するスクリプトを確認します。",
    "Hooks.emptyHint":
      "ユーザーまたはプロジェクトに hooks.json を追加するか、フック付きプラグインをインストールしてください。",
    "Hooks.close": "閉じる",
    "Hooks.cwd": "作業ディレクトリ",
    "Hooks.title": "フック",
    "Hooks.review": "フックを確認",
    "Hooks.trust": "信頼して有効化",
    "Hooks.revoke": "信頼を取り消す",
    "Hooks.enable": "有効化",
    "Hooks.disable": "無効化",
    "Hooks.refresh": "更新",
    "Hooks.empty": "フックは未設定です",
    "Hooks.pending": "確認待ち",
    "Hooks.trusted": "信頼済み",
    "Hooks.disabled": "無効",
    "Hooks.invalid": "不正",
    "Hooks.allProjects": "すべてのローカルプロジェクト",
    "Hooks.project": "プロジェクト",
    "Hooks.source": "提供元",
    "Hooks.event": "イベント",
    "Hooks.command": "コマンド",
    "Hooks.timeout": "タイムアウト（秒）",
    "Hooks.files": "設定とスクリプト",
    "Hooks.changes": "前回の承認からの変更",
    "Hooks.history": "実行履歴",
    "Hooks.permission":
      "このフックは現在のデスクトップユーザーの権限で実行され、ローカルファイルとネットワークにアクセスできます。管理者権限は自動取得しません。",
    "Hooks.permissionHook":
      "このフックはエージェントのツール権限要求を許可または拒否できます。",
    "Hooks.pendingNotice":
      "{{count}} 件のフックが確認待ちです。まだ有効ではありません。",
    "Hooks.skipped":
      "Plan／Review と IM タスクではコマンドフックを実行しません。",
    "Hooks.inspect": "表示",
    "Hooks.scope": "承認の適用範囲",
    "Hooks.select": "承認するフックを選択してください。自動選択は行いません。",
    "Hooks.filter": "絞り込み",
    "Hooks.error": "エラー",
    "Hooks.user": "ユーザー",
    "Hooks.plugin": "プラグイン",
    "Hooks.running": "実行中",
    "Hooks.success": "成功",
    "Hooks.failed": "失敗",
    "Hooks.cancelled": "キャンセル済み",
  },
  de: {
    "Hooks.summary": "Skripte vor der Ausführung in lokalen Projekten prüfen.",
    "Hooks.emptyHint":
      "hooks.json im Benutzer- oder Projektordner hinzufügen oder ein Plugin mit Hooks installieren.",
    "Hooks.close": "Schließen",
    "Hooks.cwd": "Arbeitsverzeichnis",
    "Hooks.title": "Hooks",
    "Hooks.review": "Hooks prüfen",
    "Hooks.trust": "Vertrauen und aktivieren",
    "Hooks.revoke": "Vertrauen widerrufen",
    "Hooks.enable": "Aktivieren",
    "Hooks.disable": "Deaktivieren",
    "Hooks.refresh": "Aktualisieren",
    "Hooks.empty": "Keine Hooks eingerichtet",
    "Hooks.pending": "Prüfung erforderlich",
    "Hooks.trusted": "Vertrauenswürdig",
    "Hooks.disabled": "Deaktiviert",
    "Hooks.invalid": "Ungültig",
    "Hooks.allProjects": "Alle lokalen Projekte",
    "Hooks.project": "Projekt",
    "Hooks.source": "Quelle",
    "Hooks.event": "Ereignis",
    "Hooks.command": "Befehl",
    "Hooks.timeout": "Zeitlimit (Sekunden)",
    "Hooks.files": "Konfiguration und Skripte",
    "Hooks.changes": "Änderungen seit der Freigabe",
    "Hooks.history": "Ausführungsverlauf",
    "Hooks.permission":
      "Dieser Hook läuft mit den Rechten des aktuellen Benutzers, kann auf lokale Dateien und das Netzwerk zugreifen und erhält nicht automatisch Administratorrechte.",
    "Hooks.permissionHook":
      "Dieser Hook kann Berechtigungsanfragen für Agent-Werkzeuge erlauben oder ablehnen.",
    "Hooks.pendingNotice":
      "{{count}} Hooks müssen geprüft werden. Sie sind noch nicht aktiviert.",
    "Hooks.skipped":
      "Befehls-Hooks laufen nicht in Plan-, Review- oder IM-Aufgaben.",
    "Hooks.inspect": "Ansehen",
    "Hooks.scope": "Geltungsbereich",
    "Hooks.select":
      "Wähle die freizugebenden Hooks; keiner wird automatisch ausgewählt.",
    "Hooks.filter": "Filtern",
    "Hooks.error": "Fehler",
    "Hooks.user": "Benutzer",
    "Hooks.plugin": "Plugin",
    "Hooks.running": "Läuft",
    "Hooks.success": "Erfolgreich",
    "Hooks.failed": "Fehlgeschlagen",
    "Hooks.cancelled": "Abgebrochen",
  },
  ru: {
    "Hooks.summary": "Проверьте скрипты перед запуском в локальных проектах.",
    "Hooks.emptyHint":
      "Добавьте hooks.json в папку пользователя или проекта либо установите плагин с хуками.",
    "Hooks.close": "Закрыть",
    "Hooks.cwd": "Рабочая папка",
    "Hooks.title": "Хуки",
    "Hooks.review": "Проверить хуки",
    "Hooks.trust": "Доверять и включить",
    "Hooks.revoke": "Отозвать доверие",
    "Hooks.enable": "Включить",
    "Hooks.disable": "Отключить",
    "Hooks.refresh": "Обновить",
    "Hooks.empty": "Хуки не настроены",
    "Hooks.pending": "Требует проверки",
    "Hooks.trusted": "Доверенный",
    "Hooks.disabled": "Отключён",
    "Hooks.invalid": "Недопустимый",
    "Hooks.allProjects": "Все локальные проекты",
    "Hooks.project": "Проект",
    "Hooks.source": "Источник",
    "Hooks.event": "Событие",
    "Hooks.command": "Команда",
    "Hooks.timeout": "Тайм-аут (секунды)",
    "Hooks.files": "Настройки и скрипты",
    "Hooks.changes": "Изменения после разрешения",
    "Hooks.history": "История запусков",
    "Hooks.permission":
      "Хук запускается с правами текущего пользователя, имеет доступ к локальным файлам и сети и не получает права администратора автоматически.",
    "Hooks.permissionHook":
      "Этот хук может разрешать или отклонять запросы прав инструментов агента.",
    "Hooks.pendingNotice":
      "{{count}} хуков требуют проверки. Они ещё не включены.",
    "Hooks.skipped":
      "Командные хуки не запускаются в задачах Plan, Review и IM.",
    "Hooks.inspect": "Просмотр",
    "Hooks.scope": "Область разрешения",
    "Hooks.select": "Выберите хуки для разрешения; автоматического выбора нет.",
    "Hooks.filter": "Фильтр",
    "Hooks.error": "Ошибка",
    "Hooks.user": "Пользователь",
    "Hooks.plugin": "Плагин",
    "Hooks.running": "Выполняется",
    "Hooks.success": "Успешно",
    "Hooks.failed": "Ошибка",
    "Hooks.cancelled": "Отменено",
  },
  "zh-CN": {
    "Hooks.summary": "审核在本地项目中运行的自动化脚本。",
    "Hooks.emptyHint": "在用户或项目目录添加 hooks.json，或安装带钩子的插件。",
    "Hooks.close": "关闭",
    "Hooks.cwd": "工作目录",
    "Hooks.title": "钩子",
    "Hooks.review": "审核钩子",
    "Hooks.trust": "信任并启用",
    "Hooks.revoke": "撤销信任",
    "Hooks.enable": "启用",
    "Hooks.disable": "停用",
    "Hooks.refresh": "刷新",
    "Hooks.empty": "尚未配置钩子",
    "Hooks.pending": "待审核",
    "Hooks.trusted": "已信任",
    "Hooks.disabled": "已停用",
    "Hooks.invalid": "无效",
    "Hooks.allProjects": "所有本地项目",
    "Hooks.project": "项目",
    "Hooks.source": "来源",
    "Hooks.event": "事件",
    "Hooks.command": "命令",
    "Hooks.timeout": "超时（秒）",
    "Hooks.files": "配置与脚本",
    "Hooks.changes": "相较上次授权的变化",
    "Hooks.history": "运行记录",
    "Hooks.permission":
      "此钩子将以当前桌面用户权限运行，可访问本机文件和网络，不会自动获取管理员权限。",
    "Hooks.permissionHook": "此钩子可以允许或拒绝 Agent 工具的权限请求。",
    "Hooks.pendingNotice": "有 {{count}} 个钩子待审核。这些钩子尚未启用。",
    "Hooks.skipped": "Plan／Review 和 IM 任务不运行命令钩子。",
    "Hooks.inspect": "查看",
    "Hooks.scope": "授权范围",
    "Hooks.select": "勾选要授权的钩子；不会自动全选。",
    "Hooks.filter": "筛选",
    "Hooks.error": "错误",
    "Hooks.user": "用户",
    "Hooks.plugin": "插件",
    "Hooks.running": "运行中",
    "Hooks.success": "成功",
    "Hooks.failed": "失败",
    "Hooks.cancelled": "已取消",
  },
  en: {
    "Hooks.summary": "Review scripts before they run in your local projects.",
    "Hooks.emptyHint":
      "Add hooks.json to your user or project directory, or install a plugin with hooks.",
    "Hooks.close": "Close",
    "Hooks.cwd": "Working directory",
    "Hooks.title": "Hooks",
    "Hooks.review": "Review hooks",
    "Hooks.trust": "Trust and enable",
    "Hooks.revoke": "Revoke trust",
    "Hooks.enable": "Enable",
    "Hooks.disable": "Disable",
    "Hooks.refresh": "Refresh",
    "Hooks.empty": "No hooks configured",
    "Hooks.pending": "Needs review",
    "Hooks.trusted": "Trusted",
    "Hooks.disabled": "Disabled",
    "Hooks.invalid": "Invalid",
    "Hooks.allProjects": "All local projects",
    "Hooks.project": "Project",
    "Hooks.source": "Source",
    "Hooks.event": "Event",
    "Hooks.command": "Command",
    "Hooks.timeout": "Timeout (seconds)",
    "Hooks.files": "Configuration and scripts",
    "Hooks.changes": "Changes since approval",
    "Hooks.history": "Run history",
    "Hooks.permission":
      "This hook runs with the current desktop user’s permissions, can access local files and the network, and does not automatically gain administrator privileges.",
    "Hooks.permissionHook":
      "This hook can approve or deny agent tool permission requests.",
    "Hooks.pendingNotice":
      "{{count}} hooks need review. These hooks are not enabled.",
    "Hooks.skipped": "Command hooks do not run in Plan, Review, or IM tasks.",
    "Hooks.inspect": "Inspect",
    "Hooks.scope": "Authorization scope",
    "Hooks.select":
      "Select hooks to authorize; none are selected automatically.",
    "Hooks.filter": "Filter",
    "Hooks.error": "Error",
    "Hooks.user": "User",
    "Hooks.plugin": "Plugin",
    "Hooks.running": "Running",
    "Hooks.success": "Succeeded",
    "Hooks.failed": "Failed",
    "Hooks.cancelled": "Cancelled",
  },
  it: {
    "Hooks.summary":
      "Esamina gli script prima di eseguirli nei progetti locali.",
    "Hooks.emptyHint":
      "Aggiungi hooks.json alla cartella utente o del progetto, oppure installa un plugin con hook.",
    "Hooks.close": "Chiudi",
    "Hooks.cwd": "Cartella di lavoro",
    "Hooks.title": "Hook",
    "Hooks.review": "Esamina hook",
    "Hooks.trust": "Considera attendibile e attiva",
    "Hooks.revoke": "Revoca fiducia",
    "Hooks.enable": "Attiva",
    "Hooks.disable": "Disattiva",
    "Hooks.refresh": "Aggiorna",
    "Hooks.empty": "Nessun hook configurato",
    "Hooks.pending": "Da esaminare",
    "Hooks.trusted": "Attendibile",
    "Hooks.disabled": "Disattivato",
    "Hooks.invalid": "Non valido",
    "Hooks.allProjects": "Tutti i progetti locali",
    "Hooks.project": "Progetto",
    "Hooks.source": "Origine",
    "Hooks.event": "Evento",
    "Hooks.command": "Comando",
    "Hooks.timeout": "Timeout (secondi)",
    "Hooks.files": "Configurazione e script",
    "Hooks.changes": "Modifiche dall’autorizzazione",
    "Hooks.history": "Cronologia esecuzioni",
    "Hooks.permission":
      "Questo hook usa i permessi dell’utente corrente, può accedere ai file locali e alla rete e non acquisisce automaticamente privilegi di amministratore.",
    "Hooks.permissionHook":
      "Questo hook può consentire o negare le richieste di autorizzazione degli strumenti dell’agente.",
    "Hooks.pendingNotice":
      "{{count}} hook richiedono una verifica. Non sono ancora attivi.",
    "Hooks.skipped":
      "Gli hook di comando non vengono eseguiti nelle attività Plan, Review o IM.",
    "Hooks.inspect": "Esamina",
    "Hooks.scope": "Ambito dell’autorizzazione",
    "Hooks.select":
      "Seleziona gli hook da autorizzare; nessuno viene selezionato automaticamente.",
    "Hooks.filter": "Filtra",
    "Hooks.error": "Errore",
    "Hooks.user": "Utente",
    "Hooks.plugin": "Plugin",
    "Hooks.running": "In esecuzione",
    "Hooks.success": "Riuscito",
    "Hooks.failed": "Non riuscito",
    "Hooks.cancelled": "Annullato",
  },
  fr: {
    "Hooks.summary":
      "Examinez les scripts avant leur exécution dans vos projets locaux.",
    "Hooks.emptyHint":
      "Ajoutez hooks.json au dossier utilisateur ou au projet, ou installez une extension avec des hooks.",
    "Hooks.close": "Fermer",
    "Hooks.cwd": "Dossier de travail",
    "Hooks.title": "Hooks",
    "Hooks.review": "Examiner les hooks",
    "Hooks.trust": "Autoriser et activer",
    "Hooks.revoke": "Révoquer la confiance",
    "Hooks.enable": "Activer",
    "Hooks.disable": "Désactiver",
    "Hooks.refresh": "Actualiser",
    "Hooks.empty": "Aucun hook configuré",
    "Hooks.pending": "À examiner",
    "Hooks.trusted": "Approuvé",
    "Hooks.disabled": "Désactivé",
    "Hooks.invalid": "Non valide",
    "Hooks.allProjects": "Tous les projets locaux",
    "Hooks.project": "Projet",
    "Hooks.source": "Source",
    "Hooks.event": "Événement",
    "Hooks.command": "Commande",
    "Hooks.timeout": "Délai maximal (secondes)",
    "Hooks.files": "Configuration et scripts",
    "Hooks.changes": "Modifications depuis l’autorisation",
    "Hooks.history": "Historique des exécutions",
    "Hooks.permission":
      "Ce hook s’exécute avec les droits de l’utilisateur actuel, peut accéder aux fichiers locaux et au réseau, sans obtenir automatiquement les privilèges administrateur.",
    "Hooks.permissionHook":
      "Ce hook peut autoriser ou refuser les demandes de permission des outils de l’agent.",
    "Hooks.pendingNotice":
      "{{count}} hooks sont à examiner. Ils ne sont pas encore activés.",
    "Hooks.skipped":
      "Les hooks de commande ne s’exécutent pas dans les tâches Plan, Review ou IM.",
    "Hooks.inspect": "Inspecter",
    "Hooks.scope": "Portée de l’autorisation",
    "Hooks.select":
      "Sélectionnez les hooks à autoriser ; aucun n’est présélectionné.",
    "Hooks.filter": "Filtrer",
    "Hooks.error": "Erreur",
    "Hooks.user": "Utilisateur",
    "Hooks.plugin": "Extension",
    "Hooks.running": "En cours",
    "Hooks.success": "Réussi",
    "Hooks.failed": "Échec",
    "Hooks.cancelled": "Annulé",
  },
  hi: {
    "Hooks.summary":
      "स्थानीय प्रोजेक्ट में चलाने से पहले स्क्रिप्ट की समीक्षा करें।",
    "Hooks.emptyHint":
      "उपयोगकर्ता या प्रोजेक्ट फ़ोल्डर में hooks.json जोड़ें या हुक वाला प्लगइन इंस्टॉल करें।",
    "Hooks.close": "बंद करें",
    "Hooks.cwd": "कार्य फ़ोल्डर",
    "Hooks.title": "हुक",
    "Hooks.review": "हुक की समीक्षा करें",
    "Hooks.trust": "भरोसा करें और चालू करें",
    "Hooks.revoke": "भरोसा वापस लें",
    "Hooks.enable": "चालू करें",
    "Hooks.disable": "बंद करें",
    "Hooks.refresh": "रीफ़्रेश",
    "Hooks.empty": "कोई हुक कॉन्फ़िगर नहीं है",
    "Hooks.pending": "समीक्षा आवश्यक",
    "Hooks.trusted": "विश्वसनीय",
    "Hooks.disabled": "बंद",
    "Hooks.invalid": "अमान्य",
    "Hooks.allProjects": "सभी स्थानीय प्रोजेक्ट",
    "Hooks.project": "प्रोजेक्ट",
    "Hooks.source": "स्रोत",
    "Hooks.event": "इवेंट",
    "Hooks.command": "कमांड",
    "Hooks.timeout": "समय सीमा (सेकंड)",
    "Hooks.files": "कॉन्फ़िगरेशन और स्क्रिप्ट",
    "Hooks.changes": "अनुमति के बाद बदलाव",
    "Hooks.history": "निष्पादन इतिहास",
    "Hooks.permission":
      "यह हुक वर्तमान डेस्कटॉप उपयोगकर्ता की अनुमतियों से चलता है, स्थानीय फ़ाइलों और नेटवर्क तक पहुँच सकता है और अपने आप व्यवस्थापक अधिकार नहीं लेता।",
    "Hooks.permissionHook":
      "यह हुक एजेंट टूल की अनुमति के अनुरोध स्वीकार या अस्वीकार कर सकता है।",
    "Hooks.pendingNotice":
      "{{count}} हुक की समीक्षा आवश्यक है। ये अभी चालू नहीं हैं।",
    "Hooks.skipped": "Plan, Review और IM कार्यों में कमांड हुक नहीं चलते।",
    "Hooks.inspect": "देखें",
    "Hooks.scope": "अनुमति का दायरा",
    "Hooks.select":
      "अनुमति देने के लिए हुक चुनें; कोई हुक अपने आप नहीं चुना जाता।",
    "Hooks.filter": "फ़िल्टर",
    "Hooks.error": "त्रुटि",
    "Hooks.user": "उपयोगकर्ता",
    "Hooks.plugin": "प्लगइन",
    "Hooks.running": "चल रहा है",
    "Hooks.success": "सफल",
    "Hooks.failed": "विफल",
    "Hooks.cancelled": "रद्द",
  },
  "pt-BR": {
    "Hooks.summary": "Revise os scripts antes da execução em projetos locais.",
    "Hooks.emptyHint":
      "Adicione hooks.json à pasta do usuário ou projeto, ou instale um plugin com hooks.",
    "Hooks.close": "Fechar",
    "Hooks.cwd": "Diretório de trabalho",
    "Hooks.title": "Hooks",
    "Hooks.review": "Revisar hooks",
    "Hooks.trust": "Confiar e ativar",
    "Hooks.revoke": "Revogar confiança",
    "Hooks.enable": "Ativar",
    "Hooks.disable": "Desativar",
    "Hooks.refresh": "Atualizar",
    "Hooks.empty": "Nenhum hook configurado",
    "Hooks.pending": "Aguardando revisão",
    "Hooks.trusted": "Confiável",
    "Hooks.disabled": "Desativado",
    "Hooks.invalid": "Inválido",
    "Hooks.allProjects": "Todos os projetos locais",
    "Hooks.project": "Projeto",
    "Hooks.source": "Origem",
    "Hooks.event": "Evento",
    "Hooks.command": "Comando",
    "Hooks.timeout": "Tempo limite (segundos)",
    "Hooks.files": "Configuração e scripts",
    "Hooks.changes": "Alterações desde a autorização",
    "Hooks.history": "Histórico de execução",
    "Hooks.permission":
      "Este hook usa as permissões do usuário atual, pode acessar arquivos locais e a rede, e não recebe privilégios de administrador automaticamente.",
    "Hooks.permissionHook":
      "Este hook pode permitir ou negar solicitações de permissão das ferramentas do agente.",
    "Hooks.pendingNotice":
      "{{count}} hooks precisam de revisão. Eles ainda não estão ativados.",
    "Hooks.skipped":
      "Hooks de comando não são executados em tarefas Plan, Review ou IM.",
    "Hooks.inspect": "Inspecionar",
    "Hooks.scope": "Escopo da autorização",
    "Hooks.select":
      "Selecione os hooks a autorizar; nenhum é selecionado automaticamente.",
    "Hooks.filter": "Filtrar",
    "Hooks.error": "Erro",
    "Hooks.user": "Usuário",
    "Hooks.plugin": "Plugin",
    "Hooks.running": "Em execução",
    "Hooks.success": "Concluído",
    "Hooks.failed": "Falhou",
    "Hooks.cancelled": "Cancelado",
  },
  ko: {
    "Hooks.summary": "로컬 프로젝트에서 실행할 스크립트를 검토하세요.",
    "Hooks.emptyHint":
      "사용자 또는 프로젝트 폴더에 hooks.json을 추가하거나 훅이 있는 플러그인을 설치하세요.",
    "Hooks.close": "닫기",
    "Hooks.cwd": "작업 디렉터리",
    "Hooks.title": "훅",
    "Hooks.review": "훅 검토",
    "Hooks.trust": "신뢰 및 활성화",
    "Hooks.revoke": "신뢰 취소",
    "Hooks.enable": "활성화",
    "Hooks.disable": "비활성화",
    "Hooks.refresh": "새로 고침",
    "Hooks.empty": "설정된 훅 없음",
    "Hooks.pending": "검토 필요",
    "Hooks.trusted": "신뢰됨",
    "Hooks.disabled": "비활성",
    "Hooks.invalid": "유효하지 않음",
    "Hooks.allProjects": "모든 로컬 프로젝트",
    "Hooks.project": "프로젝트",
    "Hooks.source": "출처",
    "Hooks.event": "이벤트",
    "Hooks.command": "명령",
    "Hooks.timeout": "시간 제한(초)",
    "Hooks.files": "설정 및 스크립트",
    "Hooks.changes": "이전 승인 이후 변경",
    "Hooks.history": "실행 기록",
    "Hooks.permission":
      "이 훅은 현재 데스크톱 사용자 권한으로 실행되며 로컬 파일과 네트워크에 접근할 수 있습니다. 관리자 권한을 자동으로 얻지 않습니다.",
    "Hooks.permissionHook":
      "이 훅은 에이전트 도구의 권한 요청을 허용하거나 거부할 수 있습니다.",
    "Hooks.pendingNotice":
      "{{count}}개의 훅을 검토해야 합니다. 아직 활성화되지 않았습니다.",
    "Hooks.skipped":
      "Plan／Review 및 IM 작업에서는 명령 훅을 실행하지 않습니다.",
    "Hooks.inspect": "보기",
    "Hooks.scope": "승인 범위",
    "Hooks.select": "승인할 훅을 선택하세요. 자동으로 선택되지 않습니다.",
    "Hooks.filter": "필터",
    "Hooks.error": "오류",
    "Hooks.user": "사용자",
    "Hooks.plugin": "플러그인",
    "Hooks.running": "실행 중",
    "Hooks.success": "성공",
    "Hooks.failed": "실패",
    "Hooks.cancelled": "취소됨",
  },
  "zh-TW": {
    "Hooks.summary": "審核在本機專案中執行的自動化指令碼。",
    "Hooks.emptyHint":
      "在使用者或專案目錄新增 hooks.json，或安裝含鉤子的外掛。",
    "Hooks.close": "關閉",
    "Hooks.cwd": "工作目錄",
    "Hooks.title": "鉤子",
    "Hooks.review": "審核鉤子",
    "Hooks.trust": "信任並啟用",
    "Hooks.revoke": "撤銮信任",
    "Hooks.enable": "啟用",
    "Hooks.disable": "停用",
    "Hooks.refresh": "重新整理",
    "Hooks.empty": "尚未設定鉤子",
    "Hooks.pending": "待審核",
    "Hooks.trusted": "已信任",
    "Hooks.disabled": "已停用",
    "Hooks.invalid": "無效",
    "Hooks.allProjects": "所有本機專案",
    "Hooks.project": "專案",
    "Hooks.source": "來源",
    "Hooks.event": "事件",
    "Hooks.command": "命令",
    "Hooks.timeout": "逾時（秒）",
    "Hooks.files": "設定與指令碼",
    "Hooks.changes": "相較上次授權的變更",
    "Hooks.history": "執行記錄",
    "Hooks.permission":
      "此鉤子將以目前桌面使用者權限執行，可存取本機檔案和網路，不會自動取得管理員權限。",
    "Hooks.permissionHook": "此鉤子可以允許或拒絕 Agent 工具的權限請求。",
    "Hooks.pendingNotice": "有 {{count}} 個鉤子待審核。這些鉤子尚未啟用。",
    "Hooks.skipped": "Plan／Review 和 IM 任務不執行命令鉤子。",
    "Hooks.inspect": "檢視",
    "Hooks.scope": "授權範圍",
    "Hooks.select": "勾選要授權的鉤子；不會自動全選。",
    "Hooks.filter": "篩選",
    "Hooks.error": "錯誤",
    "Hooks.user": "使用者",
    "Hooks.plugin": "外掛",
    "Hooks.running": "執行中",
    "Hooks.success": "成功",
    "Hooks.failed": "失敗",
    "Hooks.cancelled": "已取消",
  },
  id: {
    "Hooks.summary": "Tinjau skrip sebelum dijalankan di proyek lokal.",
    "Hooks.emptyHint":
      "Tambahkan hooks.json ke folder pengguna atau proyek, atau pasang plugin dengan hook.",
    "Hooks.close": "Tutup",
    "Hooks.cwd": "Direktori kerja",
    "Hooks.title": "Hook",
    "Hooks.review": "Tinjau hook",
    "Hooks.trust": "Percayai dan aktifkan",
    "Hooks.revoke": "Cabut kepercayaan",
    "Hooks.enable": "Aktifkan",
    "Hooks.disable": "Nonaktifkan",
    "Hooks.refresh": "Muat ulang",
    "Hooks.empty": "Belum ada hook",
    "Hooks.pending": "Perlu ditinjau",
    "Hooks.trusted": "Dipercaya",
    "Hooks.disabled": "Nonaktif",
    "Hooks.invalid": "Tidak valid",
    "Hooks.allProjects": "Semua proyek lokal",
    "Hooks.project": "Proyek",
    "Hooks.source": "Sumber",
    "Hooks.event": "Peristiwa",
    "Hooks.command": "Perintah",
    "Hooks.timeout": "Batas waktu (detik)",
    "Hooks.files": "Konfigurasi dan skrip",
    "Hooks.changes": "Perubahan sejak persetujuan",
    "Hooks.history": "Riwayat eksekusi",
    "Hooks.permission":
      "Hook ini berjalan dengan izin pengguna desktop saat ini, dapat mengakses berkas lokal dan jaringan, dan tidak memperoleh hak administrator secara otomatis.",
    "Hooks.permissionHook":
      "Hook ini dapat mengizinkan atau menolak permintaan izin alat agen.",
    "Hooks.pendingNotice":
      "{{count}} hook perlu ditinjau. Hook tersebut belum aktif.",
    "Hooks.skipped":
      "Hook perintah tidak berjalan dalam tugas Plan, Review, atau IM.",
    "Hooks.inspect": "Periksa",
    "Hooks.scope": "Cakupan izin",
    "Hooks.select":
      "Pilih hook yang ingin diizinkan; tidak ada yang dipilih otomatis.",
    "Hooks.filter": "Filter",
    "Hooks.error": "Kesalahan",
    "Hooks.user": "Pengguna",
    "Hooks.plugin": "Plugin",
    "Hooks.running": "Berjalan",
    "Hooks.success": "Berhasil",
    "Hooks.failed": "Gagal",
    "Hooks.cancelled": "Dibatalkan",
  },
  es: {
    "Hooks.summary":
      "Revisa los scripts antes de ejecutarlos en proyectos locales.",
    "Hooks.emptyHint":
      "Añade hooks.json al directorio de usuario o proyecto, o instala un complemento con hooks.",
    "Hooks.close": "Cerrar",
    "Hooks.cwd": "Directorio de trabajo",
    "Hooks.title": "Hooks",
    "Hooks.review": "Revisar hooks",
    "Hooks.trust": "Confiar y activar",
    "Hooks.revoke": "Revocar confianza",
    "Hooks.enable": "Activar",
    "Hooks.disable": "Desactivar",
    "Hooks.refresh": "Actualizar",
    "Hooks.empty": "No hay hooks configurados",
    "Hooks.pending": "Pendiente de revisión",
    "Hooks.trusted": "De confianza",
    "Hooks.disabled": "Desactivado",
    "Hooks.invalid": "No válido",
    "Hooks.allProjects": "Todos los proyectos locales",
    "Hooks.project": "Proyecto",
    "Hooks.source": "Origen",
    "Hooks.event": "Evento",
    "Hooks.command": "Comando",
    "Hooks.timeout": "Tiempo límite (segundos)",
    "Hooks.files": "Configuración y scripts",
    "Hooks.changes": "Cambios desde la aprobación",
    "Hooks.history": "Historial de ejecución",
    "Hooks.permission":
      "Este hook se ejecuta con los permisos del usuario actual, puede acceder a archivos locales y a la red, y no obtiene privilegios de administrador automáticamente.",
    "Hooks.permissionHook":
      "Este hook puede permitir o denegar solicitudes de permisos de herramientas del agente.",
    "Hooks.pendingNotice":
      "{{count}} hooks requieren revisión. Todavía no están activados.",
    "Hooks.skipped":
      "Los hooks de comandos no se ejecutan en tareas Plan, Review o IM.",
    "Hooks.inspect": "Inspeccionar",
    "Hooks.scope": "Ámbito de autorización",
    "Hooks.select":
      "Selecciona los hooks que deseas autorizar; ninguno se selecciona automáticamente.",
    "Hooks.filter": "Filtrar",
    "Hooks.error": "Error",
    "Hooks.user": "Usuario",
    "Hooks.plugin": "Complemento",
    "Hooks.running": "En ejecución",
    "Hooks.success": "Correcto",
    "Hooks.failed": "Error",
    "Hooks.cancelled": "Cancelado",
  },
  ar: {
    "Hooks.summary": "راجع البرامج النصية قبل تشغيلها في مشاريعك المحلية.",
    "Hooks.emptyHint":
      "أضف hooks.json إلى مجلد المستخدم أو المشروع، أو ثبّت إضافة تحتوي على خطافات.",
    "Hooks.close": "إغلاق",
    "Hooks.cwd": "مجلد العمل",
    "Hooks.title": "الخطافات",
    "Hooks.review": "مراجعة الخطافات",
    "Hooks.trust": "الوثوق والتفعيل",
    "Hooks.revoke": "إلغاء الثقة",
    "Hooks.enable": "تفعيل",
    "Hooks.disable": "تعطيل",
    "Hooks.refresh": "تحديث",
    "Hooks.empty": "لا توجد خطافات مهيأة",
    "Hooks.pending": "تحتاج إلى مراجعة",
    "Hooks.trusted": "موثوق",
    "Hooks.disabled": "معطل",
    "Hooks.invalid": "غير صالح",
    "Hooks.allProjects": "كل المشاريع المحلية",
    "Hooks.project": "المشروع",
    "Hooks.source": "المصدر",
    "Hooks.event": "الحدث",
    "Hooks.command": "الأمر",
    "Hooks.timeout": "المهلة بالثواني",
    "Hooks.files": "الإعدادات والبرامج النصية",
    "Hooks.changes": "التغييرات منذ الموافقة",
    "Hooks.history": "سجل التشغيل",
    "Hooks.permission":
      "يعمل هذا الخطاف بصلاحيات مستخدم سطح المكتب الحالي ويمكنه الوصول إلى الملفات المحلية والشبكة، ولا يحصل تلقائيًا على صلاحيات المسؤول.",
    "Hooks.permissionHook":
      "يمكن لهذا الخطاف السماح بطلبات أذونات أدوات الوكيل أو رفضها.",
    "Hooks.pendingNotice":
      "هناك {{count}} خطافات تحتاج إلى مراجعة. لم يتم تفعيلها بعد.",
    "Hooks.skipped": "لا تعمل خطافات الأوامر في مهام Plan أو Review أو IM.",
    "Hooks.inspect": "فحص",
    "Hooks.scope": "نطاق التفويض",
    "Hooks.select":
      "حدد الخطافات التي تريد تفويضها؛ لا يتم تحديد أي منها تلقائيًا.",
    "Hooks.filter": "تصفية",
    "Hooks.error": "خطأ",
    "Hooks.user": "المستخدم",
    "Hooks.plugin": "الإضافة",
    "Hooks.running": "قيد التشغيل",
    "Hooks.success": "نجح",
    "Hooks.failed": "فشل",
    "Hooks.cancelled": "تم الإلغاء",
  },
} as const;
export type HookMessageKey = keyof typeof resources.en;
export function hookText(locale: AppLocale, key: HookMessageKey): string {
  return resources[locale][key];
}
