import type { AppLocale } from "@artemis/protocol";
export const STATUS_RESOURCES = {
  en: {
    starting: "Starting",
    skipped: "Skipped",
    checking: "Checking for updates",
    available: "Update available",
    downloading: "Downloading",
    downloaded: "Downloaded",
    disconnected: "Disconnected",
    "authorization-required": "Authorization required",
    authorizing: "Authorizing",
    changed: "Changed since approval",
    pending: "Pending",
    sending: "Sending",
    sent: "Sent",
    uncertain: "Delivery uncertain",
    processing: "Processing",
    incoming: "Incoming",
    outgoing: "Outgoing",
    device: "Device queue",
    direct: "Private chat",
    group: "Group chat",
    revoked: "Revoked",
    expired: "Expired",
    media: "Media",
    rejected: "Rejected",
  },
  "zh-CN": {
    starting: "正在启动",
    skipped: "已跳过",
    checking: "正在检查更新",
    available: "有可用更新",
    downloading: "正在下载",
    downloaded: "已下载",
    disconnected: "未连接",
    "authorization-required": "需要授权",
    authorizing: "正在授权",
    changed: "授权后内容已变更",
    pending: "待处理",
    sending: "正在发送",
    sent: "已发送",
    uncertain: "投递状态不确定",
    processing: "正在处理",
    incoming: "接收队列",
    outgoing: "发送队列",
    device: "设备队列",
    direct: "私聊",
    group: "群聊",
    revoked: "已撤销",
    expired: "已过期",
    media: "媒体",
    rejected: "已拒绝",
  },
  "zh-TW": {
    starting: "正在啟動",
    skipped: "已略過",
    checking: "正在檢查更新",
    available: "有可用更新",
    downloading: "正在下載",
    downloaded: "已下載",
    disconnected: "未連線",
    "authorization-required": "需要授權",
    authorizing: "正在授權",
    changed: "授權後內容已變更",
    pending: "待處理",
    sending: "正在傳送",
    sent: "已傳送",
    uncertain: "傳送狀態不確定",
    processing: "正在處理",
    incoming: "接收佇列",
    outgoing: "傳送佇列",
    device: "裝置佇列",
    direct: "私訊",
    group: "群組聊天",
    revoked: "已撤銷",
    expired: "已過期",
    media: "媒體",
    rejected: "已拒絕",
  },
  ja: {
    starting: "起動中",
    skipped: "スキップ済み",
    checking: "更新を確認中",
    available: "更新があります",
    downloading: "ダウンロード中",
    downloaded: "ダウンロード済み",
    disconnected: "未接続",
    "authorization-required": "認証が必要です",
    authorizing: "認証中",
    changed: "承認後に内容が変更されました",
    pending: "保留中",
    sending: "送信中",
    sent: "送信済み",
    uncertain: "配信状況が不明です",
    processing: "処理中",
    incoming: "受信キュー",
    outgoing: "送信キュー",
    device: "デバイスキュー",
    direct: "個別チャット",
    group: "グループチャット",
    revoked: "取り消し済み",
    expired: "期限切れ",
    media: "メディア",
    rejected: "拒否済み",
  },
  ko: {
    starting: "시작 중",
    skipped: "건너뜀",
    checking: "업데이트 확인 중",
    available: "업데이트 사용 가능",
    downloading: "다운로드 중",
    downloaded: "다운로드 완료",
    disconnected: "연결 안 됨",
    "authorization-required": "인증 필요",
    authorizing: "인증 중",
    changed: "승인 후 내용이 변경됨",
    pending: "대기 중",
    sending: "전송 중",
    sent: "전송됨",
    uncertain: "전달 상태 불확실",
    processing: "처리 중",
    incoming: "수신 대기열",
    outgoing: "발신 대기열",
    device: "기기 대기열",
    direct: "개인 채팅",
    group: "그룹 채팅",
    revoked: "철회됨",
    expired: "만료됨",
    media: "미디어",
    rejected: "거부됨",
  },
  es: {
    starting: "Iniciando",
    skipped: "Omitido",
    checking: "Buscando actualizaciones",
    available: "Actualización disponible",
    downloading: "Descargando",
    downloaded: "Descargado",
    disconnected: "Desconectado",
    "authorization-required": "Autorización necesaria",
    authorizing: "Autorizando",
    changed: "Contenido modificado tras la aprobación",
    pending: "Pendiente",
    sending: "Enviando",
    sent: "Enviado",
    uncertain: "Entrega sin confirmar",
    processing: "Procesando",
    incoming: "Cola de entrada",
    outgoing: "Cola de salida",
    device: "Cola del dispositivo",
    direct: "Chat privado",
    group: "Chat de grupo",
    revoked: "Revocado",
    expired: "Caducado",
    media: "Multimedia",
    rejected: "Rechazado",
  },
  fr: {
    starting: "Démarrage",
    skipped: "Ignoré",
    checking: "Recherche de mises à jour",
    available: "Mise à jour disponible",
    downloading: "Téléchargement",
    downloaded: "Téléchargé",
    disconnected: "Déconnecté",
    "authorization-required": "Autorisation requise",
    authorizing: "Autorisation en cours",
    changed: "Contenu modifié depuis l’approbation",
    pending: "En attente",
    sending: "Envoi en cours",
    sent: "Envoyé",
    uncertain: "Livraison incertaine",
    processing: "Traitement en cours",
    incoming: "File de réception",
    outgoing: "File d’envoi",
    device: "File de l’appareil",
    direct: "Discussion privée",
    group: "Discussion de groupe",
    revoked: "Révoqué",
    expired: "Expiré",
    media: "Médias",
    rejected: "Refusé",
  },
  de: {
    starting: "Wird gestartet",
    skipped: "Übersprungen",
    checking: "Updates werden gesucht",
    available: "Update verfügbar",
    downloading: "Wird heruntergeladen",
    downloaded: "Heruntergeladen",
    disconnected: "Nicht verbunden",
    "authorization-required": "Autorisierung erforderlich",
    authorizing: "Autorisierung läuft",
    changed: "Inhalt seit Genehmigung geändert",
    pending: "Ausstehend",
    sending: "Wird gesendet",
    sent: "Gesendet",
    uncertain: "Zustellung ungewiss",
    processing: "Wird verarbeitet",
    incoming: "Eingangswarteschlange",
    outgoing: "Ausgangswarteschlange",
    device: "Gerätewarteschlange",
    direct: "Privater Chat",
    group: "Gruppenchat",
    revoked: "Widerrufen",
    expired: "Abgelaufen",
    media: "Medien",
    rejected: "Abgelehnt",
  },
  "pt-BR": {
    starting: "Iniciando",
    skipped: "Ignorado",
    checking: "Verificando atualizações",
    available: "Atualização disponível",
    downloading: "Baixando",
    downloaded: "Download concluído",
    disconnected: "Desconectado",
    "authorization-required": "Autorização necessária",
    authorizing: "Autorizando",
    changed: "Conteúdo alterado após a aprovação",
    pending: "Pendente",
    sending: "Enviando",
    sent: "Enviado",
    uncertain: "Entrega incerta",
    processing: "Processando",
    incoming: "Fila de entrada",
    outgoing: "Fila de saída",
    device: "Fila do dispositivo",
    direct: "Conversa privada",
    group: "Conversa em grupo",
    revoked: "Revogado",
    expired: "Expirado",
    media: "Mídia",
    rejected: "Rejeitado",
  },
  it: {
    starting: "Avvio in corso",
    skipped: "Saltato",
    checking: "Ricerca di aggiornamenti",
    available: "Aggiornamento disponibile",
    downloading: "Download in corso",
    downloaded: "Scaricato",
    disconnected: "Disconnesso",
    "authorization-required": "Autorizzazione richiesta",
    authorizing: "Autorizzazione in corso",
    changed: "Contenuto modificato dopo l’approvazione",
    pending: "In attesa",
    sending: "Invio in corso",
    sent: "Inviato",
    uncertain: "Consegna incerta",
    processing: "Elaborazione in corso",
    incoming: "Coda in entrata",
    outgoing: "Coda in uscita",
    device: "Coda del dispositivo",
    direct: "Chat privata",
    group: "Chat di gruppo",
    revoked: "Revocato",
    expired: "Scaduto",
    media: "Contenuti multimediali",
    rejected: "Rifiutato",
  },
  ru: {
    starting: "Запуск",
    skipped: "Пропущено",
    checking: "Проверка обновлений",
    available: "Доступно обновление",
    downloading: "Загрузка",
    downloaded: "Загружено",
    disconnected: "Нет подключения",
    "authorization-required": "Требуется авторизация",
    authorizing: "Авторизация",
    changed: "Содержимое изменено после одобрения",
    pending: "Ожидание",
    sending: "Отправка",
    sent: "Отправлено",
    uncertain: "Статус доставки неясен",
    processing: "Обработка",
    incoming: "Очередь входящих",
    outgoing: "Очередь исходящих",
    device: "Очередь устройства",
    direct: "Личный чат",
    group: "Групповой чат",
    revoked: "Отозвано",
    expired: "Срок истёк",
    media: "Медиа",
    rejected: "Отклонено",
  },
  ar: {
    starting: "جارٍ البدء",
    skipped: "تم التخطي",
    checking: "جارٍ البحث عن تحديثات",
    available: "يتوفر تحديث",
    downloading: "جارٍ التنزيل",
    downloaded: "تم التنزيل",
    disconnected: "غير متصل",
    "authorization-required": "يلزم التفويض",
    authorizing: "جارٍ التفويض",
    changed: "تغيّر المحتوى بعد الموافقة",
    pending: "قيد الانتظار",
    sending: "جارٍ الإرسال",
    sent: "تم الإرسال",
    uncertain: "حالة التسليم غير مؤكدة",
    processing: "جارٍ المعالجة",
    incoming: "قائمة الاستقبال",
    outgoing: "قائمة الإرسال",
    device: "قائمة الجهاز",
    direct: "محادثة خاصة",
    group: "محادثة جماعية",
    revoked: "تم الإلغاء",
    expired: "انتهت الصلاحية",
    media: "الوسائط",
    rejected: "مرفوض",
  },
  hi: {
    starting: "शुरू हो रहा है",
    skipped: "छोड़ दिया गया",
    checking: "अपडेट जाँचे जा रहे हैं",
    available: "अपडेट उपलब्ध है",
    downloading: "डाउनलोड हो रहा है",
    downloaded: "डाउनलोड हो गया",
    disconnected: "कनेक्ट नहीं है",
    "authorization-required": "अनुमति आवश्यक है",
    authorizing: "अनुमति ली जा रही है",
    changed: "स्वीकृति के बाद सामग्री बदल गई है",
    pending: "लंबित",
    sending: "भेजा जा रहा है",
    sent: "भेजा गया",
    uncertain: "डिलीवरी की स्थिति अनिश्चित है",
    processing: "प्रक्रिया जारी है",
    incoming: "प्राप्ति कतार",
    outgoing: "प्रेषण कतार",
    device: "डिवाइस कतार",
    direct: "निजी चैट",
    group: "समूह चैट",
    revoked: "रद्द किया गया",
    expired: "समय सीमा समाप्त",
    media: "मीडिया",
    rejected: "अस्वीकृत",
  },
  id: {
    starting: "Memulai",
    skipped: "Dilewati",
    checking: "Memeriksa pembaruan",
    available: "Pembaruan tersedia",
    downloading: "Mengunduh",
    downloaded: "Sudah diunduh",
    disconnected: "Terputus",
    "authorization-required": "Otorisasi diperlukan",
    authorizing: "Sedang mengotorisasi",
    changed: "Konten berubah setelah persetujuan",
    pending: "Menunggu",
    sending: "Mengirim",
    sent: "Terkirim",
    uncertain: "Status pengiriman tidak pasti",
    processing: "Memproses",
    incoming: "Antrean masuk",
    outgoing: "Antrean keluar",
    device: "Antrean perangkat",
    direct: "Obrolan pribadi",
    group: "Obrolan grup",
    revoked: "Dicabut",
    expired: "Kedaluwarsa",
    media: "Media",
    rejected: "Ditolak",
  },
} satisfies Record<
  AppLocale,
  Record<
    | "starting"
    | "skipped"
    | "checking"
    | "available"
    | "downloading"
    | "downloaded"
    | "disconnected"
    | "authorization-required"
    | "authorizing"
    | "changed"
    | "pending"
    | "sending"
    | "sent"
    | "uncertain"
    | "processing"
    | "incoming"
    | "outgoing"
    | "device"
    | "direct"
    | "group"
    | "revoked"
    | "expired"
    | "media"
    | "rejected",
    string
  >
>;
