import { makeUiCopy, uiText } from "./ui-text.js";
export const UI_COPY = {
  App_copy: makeUiCopy((locale) => ({
    appName: uiText(locale, "App_copy.appName"),
    activityBar: uiText(locale, "App_copy.activityBar"),
    projects: uiText(locale, "App_copy.projects"),
    expandProjects: uiText(locale, "App_copy.expandProjects"),
    collapseProjects: uiText(locale, "App_copy.collapseProjects"),
    expandTemporaryConversations: uiText(
      locale,
      "App_copy.expandTemporaryConversations",
    ),
    collapseTemporaryConversations: uiText(
      locale,
      "App_copy.collapseTemporaryConversations",
    ),
    resizeProjectsSidebar: uiText(locale, "App_copy.resizeProjectsSidebar"),
    temporaryConversations: uiText(locale, "App_copy.temporaryConversations"),
    temporaryConversation: uiText(locale, "App_copy.temporaryConversation"),
    automations: uiText(locale, "App_copy.automations"),
    tasks: uiText(locale, "App_copy.tasks"),
    newTask: uiText(locale, "App_copy.newTask"),
    openProject: uiText(locale, "App_copy.openProject"),
    removeProject: uiText(locale, "App_copy.removeProject"),
    removeProjectConfirm: uiText(locale, "App_copy.removeProjectConfirm"),
    moreProjectActions: uiText(locale, "App_copy.moreProjectActions"),
    stopTasksBeforeRemove: uiText(locale, "App_copy.stopTasksBeforeRemove"),
    search: uiText(locale, "App_copy.search"),
    noTasks: uiText(locale, "App_copy.noTasks"),
    activeTasks: uiText(locale, "App_copy.activeTasks"),
    archivedTasks: uiText(locale, "App_copy.archivedTasks"),
    showArchived: uiText(locale, "App_copy.showArchived"),
    showActive: uiText(locale, "App_copy.showActive"),
    renameTask: uiText(locale, "App_copy.renameTask"),
    renameTaskTitle: uiText(locale, "App_copy.renameTaskTitle"),
    renameTaskHint: uiText(locale, "App_copy.renameTaskHint"),
    renameSave: uiText(locale, "App_copy.renameSave"),
    renameCancel: uiText(locale, "App_copy.renameCancel"),
    renameClose: uiText(locale, "App_copy.renameClose"),
    forkTask: uiText(locale, "App_copy.forkTask"),
    archiveTask: uiText(locale, "App_copy.archiveTask"),
    restoreTask: uiText(locale, "App_copy.restoreTask"),
    deleteTask: uiText(locale, "App_copy.deleteTask"),
    deleteTaskConfirm: uiText(locale, "App_copy.deleteTaskConfirm"),
    confirmationTitle: uiText(locale, "App_copy.confirmationTitle"),
    confirmationDangerTitle: uiText(locale, "App_copy.confirmationDangerTitle"),
    confirmationCancel: uiText(locale, "App_copy.renameCancel"),
    confirmationAccept: uiText(locale, "App_copy.confirmationAccept"),
    showMoreTasks: uiText(locale, "App_copy.showMoreTasks"),
    showFewerTasks: uiText(locale, "App_copy.showFewerTasks"),
    expandProjectHistory: uiText(locale, "App_copy.expandProjectHistory"),
    collapseProjectHistory: uiText(locale, "App_copy.collapseProjectHistory"),
    collapseAllProjectHistories: uiText(
      locale,
      "App_copy.collapseAllProjectHistories",
    ),
    expandAllProjectHistories: uiText(
      locale,
      "App_copy.expandAllProjectHistories",
    ),
    moreActions: uiText(locale, "App_copy.moreActions"),
    taskNamePrompt: uiText(locale, "App_copy.taskNamePrompt"),
    archiveConfirm: uiText(locale, "App_copy.archiveConfirm"),
    emptyTitle: uiText(locale, "App_copy.emptyTitle"),
    emptyBody: uiText(locale, "App_copy.emptyBody"),
    prompt: uiText(locale, "App_copy.prompt"),
    send: uiText(locale, "App_copy.send"),
    stop: uiText(locale, "App_copy.stop"),
    execute: uiText(locale, "App_copy.execute"),
    plan: uiText(locale, "App_copy.plan"),
    review: uiText(locale, "App_copy.review"),
    local: uiText(locale, "App_copy.local"),
    taskMode: uiText(locale, "App_copy.taskMode"),
    reviewPanel: uiText(locale, "App_copy.review"),
    agentTeam: uiText(locale, "App_copy.agentTeam"),
    terminal: uiText(locale, "App_copy.terminal"),
    browser: uiText(locale, "App_copy.browser"),
    browserAddress: uiText(locale, "App_copy.browserAddress"),
    browserBack: uiText(locale, "App_copy.browserBack"),
    browserForward: uiText(locale, "App_copy.browserForward"),
    browserGo: uiText(locale, "App_copy.browserGo"),
    markdownReader: uiText(locale, "App_copy.markdownReader"),
    files: uiText(locale, "App_copy.files"),
    sources: uiText(locale, "App_copy.sources"),
    addTab: uiText(locale, "App_copy.addTab"),
    closeTab: uiText(locale, "App_copy.closeTab"),
    scrollTabsLeft: uiText(locale, "App_copy.scrollTabsLeft"),
    scrollTabsRight: uiText(locale, "App_copy.scrollTabsRight"),
    resizeRightSidebar: uiText(locale, "App_copy.resizeRightSidebar"),
    dismissTurnError: uiText(locale, "App_copy.dismissTurnError"),
    dismissNotice: uiText(locale, "App_copy.dismissNotice"),
    editFile: uiText(locale, "App_copy.editFile"),
    saveFile: uiText(locale, "App_copy.renameSave"),
    saved: uiText(locale, "App_copy.saved"),
    saving: uiText(locale, "App_copy.saving"),
    unsaved: uiText(locale, "App_copy.unsaved"),
    noHtmlPreview: uiText(locale, "App_copy.noHtmlPreview"),
    noMarkdownPreview: uiText(locale, "App_copy.noMarkdownPreview"),
    filterFiles: uiText(locale, "App_copy.filterFiles"),
    openFileFromTree: uiText(locale, "App_copy.openFileFromTree"),
    binaryFile: uiText(locale, "App_copy.binaryFile"),
    imageFailedToLoad: uiText(locale, "App_copy.imageFailedToLoad"),
    previewFile: uiText(locale, "App_copy.previewFile"),
    fileLinkMenu: uiText(locale, "App_copy.fileLinkMenu"),
    openLinkedFile: uiText(locale, "App_copy.openLinkedFile"),
    revealLinkedFile: uiText(locale, "App_copy.revealLinkedFile"),
    runLinkedFile: uiText(locale, "App_copy.runLinkedFile"),
    runLinkedFileStarted: uiText(locale, "App_copy.runLinkedFileStarted"),
    richText: uiText(locale, "App_copy.richText"),
    sourceText: uiText(locale, "App_copy.sourceText"),
    refreshPreview: uiText(locale, "App_copy.refreshPreview"),
    changedFiles: uiText(locale, "App_copy.changedFiles"),
    noChanges: uiText(locale, "App_copy.noChanges"),
    changesAppearHere: uiText(locale, "App_copy.changesAppearHere"),
    noMatchingFiles: uiText(locale, "App_copy.noMatchingFiles"),
    comparison: uiText(locale, "App_copy.comparison"),
    lastTurn: uiText(locale, "App_copy.lastTurn"),
    thisTurn: uiText(locale, "App_copy.thisTurn"),
    workedFor: uiText(locale, "App_copy.workedFor"),
    taskPeriodChanges: uiText(locale, "App_copy.taskPeriodChanges"),
    editedFile: uiText(locale, "App_copy.editedFile"),
    editedFiles: uiText(locale, "App_copy.editedFiles"),
    showMoreFiles: uiText(locale, "App_copy.showMoreFiles"),
    binaryChange: uiText(locale, "App_copy.binaryChange"),
    reviewChanges: uiText(locale, "App_copy.reviewChanges"),
    undoChanges: uiText(locale, "App_copy.undoChanges"),
    changesUndone: uiText(locale, "App_copy.changesUndone"),
    undoTurnConfirm: uiText(locale, "App_copy.undoTurnConfirm"),
    undoTurnComplete: uiText(locale, "App_copy.undoTurnComplete"),
    unstaged: uiText(locale, "App_copy.unstaged"),
    staged: uiText(locale, "App_copy.staged"),
    branch: uiText(locale, "App_copy.branch"),
    baseRef: uiText(locale, "App_copy.baseRef"),
    stage: uiText(locale, "App_copy.stage"),
    unstage: uiText(locale, "App_copy.unstage"),
    revert: uiText(locale, "App_copy.revert"),
    revertConfirm: uiText(locale, "App_copy.revertConfirm"),
    recoverySaved: uiText(locale, "App_copy.recoverySaved"),
    additions: uiText(locale, "App_copy.additions"),
    deletions: uiText(locale, "App_copy.deletions"),
    addComment: uiText(locale, "App_copy.addComment"),
    commentPlaceholder: uiText(locale, "App_copy.commentPlaceholder"),
    saveComment: uiText(locale, "App_copy.saveComment"),
    cancelComment: uiText(locale, "App_copy.renameCancel"),
    deleteComment: uiText(locale, "App_copy.deleteComment"),
    approveOnce: uiText(locale, "App_copy.approveOnce"),
    approveSession: uiText(locale, "App_copy.approveSession"),
    approveProject: uiText(locale, "App_copy.approveProject"),
    approvalScopeHint: uiText(locale, "App_copy.approvalScopeHint"),
    deny: uiText(locale, "App_copy.deny"),
    approvalApproved: uiText(locale, "App_copy.approvalApproved"),
    approvalDenied: uiText(locale, "App_copy.approvalDenied"),
    recommended: uiText(locale, "App_copy.recommended"),
    otherAnswer: uiText(locale, "App_copy.otherAnswer"),
    otherAnswerDetail: uiText(locale, "App_copy.otherAnswerDetail"),
    customAnswer: uiText(locale, "App_copy.customAnswer"),
    submitAnswer: uiText(locale, "App_copy.submitAnswer"),
    waitingSelection: uiText(locale, "App_copy.waitingSelection"),
    navigateChoices: uiText(locale, "App_copy.navigateChoices"),
    selectChoice: uiText(locale, "App_copy.selectChoice"),
    answered: uiText(locale, "App_copy.answered"),
    timedOut: uiText(locale, "App_copy.timedOut"),
    timeoutHint: uiText(locale, "App_copy.timeoutHint"),
    inputCancelled: uiText(locale, "App_copy.inputCancelled"),
    cancelCurrentTask: uiText(locale, "App_copy.cancelCurrentTask"),
    skip: uiText(locale, "App_copy.skip"),
    skipAndCancelTask: uiText(locale, "App_copy.skipAndCancelTask"),
    modelReason: uiText(locale, "App_copy.modelReason"),
    agentActor: uiText(locale, "App_copy.agentActor"),
    thinking: uiText(locale, "App_copy.thinking"),
    running: uiText(locale, "App_copy.running"),
    queuedForAgent: uiText(locale, "App_copy.queuedForAgent"),
    waitingForModel: uiText(locale, "App_copy.waitingForModel"),
    waitingNetwork: uiText(locale, "App_copy.waitingNetwork"),
    reconnecting: uiText(locale, "App_copy.reconnecting"),
    modelRetrying: uiText(locale, "App_copy.modelRetrying"),
    modelStreamStalled: uiText(locale, "App_copy.modelStreamStalled"),
    rateLimited: uiText(locale, "App_copy.rateLimited"),
    connectionRecovered: uiText(locale, "App_copy.connectionRecovered"),
    taskInterrupted: uiText(locale, "App_copy.taskInterrupted"),
    waiting: uiText(locale, "App_copy.waiting"),
    waitingInput: uiText(locale, "App_copy.waitingInput"),
    completed: uiText(locale, "App_copy.completed"),
    failed: uiText(locale, "App_copy.failed"),
    ready: uiText(locale, "App_copy.ready"),
    elapsed: uiText(locale, "App_copy.elapsed"),
    model: uiText(locale, "App_copy.model"),
    modelPicker: uiText(locale, "App_copy.modelPicker"),
    modelPickerModel: uiText(locale, "App_copy.modelPickerModel"),
    ultraMode: uiText(locale, "App_copy.ultraMode"),
    ultraModeQuota: uiText(locale, "App_copy.ultraModeQuota"),
    modelSwitchFailed: uiText(locale, "App_copy.modelSwitchFailed"),
    steer: uiText(locale, "App_copy.steer"),
    followUp: uiText(locale, "App_copy.followUp"),
    queuedMessages: uiText(locale, "App_copy.queuedMessages"),
    queueItem: uiText(locale, "App_copy.queueItem"),
    queueSteer: uiText(locale, "App_copy.queueSteer"),
    queueSteerHint: uiText(locale, "App_copy.queueSteerHint"),
    queueMoveToFront: uiText(locale, "App_copy.queueMoveToFront"),
    queueMoveToFrontHint: uiText(locale, "App_copy.queueMoveToFrontHint"),
    queueDelete: uiText(locale, "App_copy.queueDelete"),
    queueEdit: uiText(locale, "App_copy.queueEdit"),
    queueSave: uiText(locale, "App_copy.queueSave"),
    queueCancel: uiText(locale, "App_copy.queueCancel"),
    queueSaveError: uiText(locale, "App_copy.queueSaveError"),
    queueRetry: uiText(locale, "App_copy.queueRetry"),
    copyMessage: uiText(locale, "App_copy.copyMessage"),
    editAndResend: uiText(locale, "App_copy.editAndResend"),
    messageCopied: uiText(locale, "App_copy.messageCopied"),
    messageCopyFailed: uiText(locale, "App_copy.messageCopyFailed"),
    conversation: uiText(locale, "App_copy.conversation"),
    conversationHistory: uiText(locale, "App_copy.conversationHistory"),
    emptyConversationPrompt: uiText(locale, "App_copy.emptyConversationPrompt"),
    temporaryConversationPrompt: uiText(
      locale,
      "App_copy.temporaryConversationPrompt",
    ),
    sandboxUnavailable: uiText(locale, "App_copy.sandboxUnavailable"),
    sandboxDetail: uiText(locale, "App_copy.sandboxDetail"),
    terminalLocked: uiText(locale, "App_copy.terminalLocked"),
    refreshDiff: uiText(locale, "App_copy.refreshPreview"),
    refreshingDiff: uiText(locale, "App_copy.refreshingDiff"),
    diffRefreshed: uiText(locale, "App_copy.diffRefreshed"),
    addAttachments: uiText(locale, "App_copy.addAttachments"),
    removeAttachment: uiText(locale, "App_copy.removeAttachment"),
    removeSelectedSkill: uiText(locale, "App_copy.removeSelectedSkill"),
    customAgentMentionHeading: uiText(
      locale,
      "App_copy.customAgentMentionHeading",
    ),
    selectedCustomAgent: uiText(locale, "App_copy.selectedCustomAgent"),
    removeSelectedCustomAgent: uiText(
      locale,
      "App_copy.removeSelectedCustomAgent",
    ),
    customAgentWhileRunning: uiText(locale, "App_copy.customAgentWhileRunning"),
    customAgentControlConflict: uiText(
      locale,
      "App_copy.customAgentControlConflict",
    ),
    attachmentLimit: uiText(locale, "App_copy.attachmentLimit"),
    inspectAttachments: uiText(locale, "App_copy.inspectAttachments"),
    dropAttachments: uiText(locale, "App_copy.dropAttachments"),
    dropAttachmentsDetail: uiText(locale, "App_copy.dropAttachmentsDetail"),
    approvalPolicy: uiText(locale, "App_copy.approvalPolicy"),
    askApproval: uiText(locale, "App_copy.askApproval"),
    askApprovalDetail: uiText(locale, "App_copy.askApprovalDetail"),
    agentApproval: uiText(locale, "App_copy.agentApproval"),
    agentApprovalDetail: uiText(locale, "App_copy.agentApprovalDetail"),
    fullAccess: uiText(locale, "App_copy.fullAccess"),
    fullAccessDetail: uiText(locale, "App_copy.fullAccessDetail"),
    fullAccessUnavailable: uiText(locale, "App_copy.fullAccessUnavailable"),
    customApproval: uiText(locale, "App_copy.customApproval"),
    customApprovalDetail: uiText(locale, "App_copy.customApprovalDetail"),
    openFolder: uiText(locale, "App_copy.openFolder"),
    leftSidebar: uiText(locale, "App_copy.leftSidebar"),
    rightSidebar: uiText(locale, "App_copy.rightSidebar"),
    toggleReview: uiText(locale, "App_copy.toggleReview"),
    toggleTerminal: uiText(locale, "App_copy.toggleTerminal"),
    noProject: uiText(locale, "App_copy.noProject"),
    taskError: uiText(locale, "App_copy.taskError"),
    turnError: uiText(locale, "App_copy.turnError"),
    hostRestart: uiText(locale, "App_copy.hostRestart"),
    hostRecovering: uiText(locale, "App_copy.hostRecovering"),
    streamInterrupted: uiText(locale, "App_copy.streamInterrupted"),
    agentHostInterrupted: uiText(locale, "App_copy.agentHostInterrupted"),
    settings: uiText(locale, "App_copy.settings"),
    loadingSettings: uiText(locale, "App_copy.loadingSettings"),
    currentVersion: uiText(locale, "App_copy.currentVersion"),
    archiveLibrary: uiText(locale, "App_copy.archiveTask"),
    resourceCenter: uiText(locale, "App_copy.resourceCenter"),
    tokenUsage: uiText(locale, "App_copy.tokenUsage"),
    goal: uiText(locale, "App_copy.goal"),
    goalEditTitle: uiText(locale, "App_copy.goalEditTitle"),
    goalSet: uiText(locale, "App_copy.goalSet"),
    goalCleared: uiText(locale, "App_copy.goalCleared"),
    goalReplaceConfirm: uiText(locale, "App_copy.goalReplaceConfirm"),
    goalClearConfirm: uiText(locale, "App_copy.goalClearConfirm"),
    goalResumeTitle: uiText(locale, "App_copy.goalResumeTitle"),
    goalResumeConfirm: uiText(locale, "App_copy.goalResumeConfirm"),
    goalResumeAccept: uiText(locale, "App_copy.goalResumeAccept"),
    goalResumeLater: uiText(locale, "App_copy.goalResumeLater"),
    goalSetWhileRunning: uiText(locale, "App_copy.goalSetWhileRunning"),
    noGoal: uiText(locale, "App_copy.noGoal"),
    goalCommand: uiText(locale, "App_copy.goalCommand"),
    goalCommandDetail: uiText(locale, "App_copy.goalCommandDetail"),
    compactCommand: uiText(locale, "App_copy.compactCommand"),
    compactCommandDetail: uiText(locale, "App_copy.compactCommandDetail"),
    contextCompacting: uiText(locale, "App_copy.contextCompacting"),
    contextCompacted: uiText(locale, "App_copy.contextCompacted"),
    contextCompactionFailed: uiText(locale, "App_copy.contextCompactionFailed"),
    contextCompactionCancelled: uiText(
      locale,
      "App_copy.contextCompactionCancelled",
    ),
    compactRequiresTask: uiText(locale, "App_copy.compactRequiresTask"),
    compactWhileRunning: uiText(locale, "App_copy.compactWhileRunning"),
    compactFailed: uiText(locale, "App_copy.compactFailed"),
    initCommand: uiText(locale, "App_copy.initCommand"),
    initCommandDetail: uiText(locale, "App_copy.initCommandDetail"),
    planCommand: uiText(locale, "App_copy.planCommand"),
    planCommandDetail: uiText(locale, "App_copy.planCommandDetail"),
    executeCommand: uiText(locale, "App_copy.executeCommand"),
    executeCommandDetail: uiText(locale, "App_copy.executeCommandDetail"),
    reviewCommand: uiText(locale, "App_copy.reviewCommand"),
    reviewCommandDetail: uiText(locale, "App_copy.reviewCommandDetail"),
    multipleModeCommands: uiText(locale, "App_copy.multipleModeCommands"),
    modeCommandWhileRunning: uiText(locale, "App_copy.modeCommandWhileRunning"),
    installedSkills: uiText(locale, "App_copy.installedSkills"),
    installedPlugins: uiText(locale, "App_copy.installedPlugins"),
    loadingSkills: uiText(locale, "App_copy.loadingSkills"),
    noInstalledSkills: uiText(locale, "App_copy.noInstalledSkills"),
    noMatchingSkills: uiText(locale, "App_copy.noMatchingSkills"),
    selectedSkill: uiText(locale, "App_copy.selectedSkill"),
    archivedReadOnly: uiText(locale, "App_copy.archivedReadOnly"),
    archivedReadOnlyDetail: uiText(locale, "App_copy.archivedReadOnlyDetail"),
  })),
  App_copy_9734: makeUiCopy((locale) => ({
    queued: uiText(locale, "App_copy_9734.queued"),
    running: uiText(locale, "App_copy_9734.running"),
    blocked: uiText(locale, "App_copy_9734.blocked"),
    cancelling: uiText(locale, "App_copy_9734.cancelling"),
    completed: uiText(locale, "App_copy.completed"),
    failed: uiText(locale, "App_copy.failed"),
    cancelled: uiText(locale, "App_copy_9734.cancelled"),
  })),
  App_labels: makeUiCopy((locale) => ({
    title: uiText(locale, "App_copy.agentTeam"),
    teamMembers: uiText(locale, "App_labels.teamMembers"),
    teamMessages: uiText(locale, "App_labels.teamMessages"),
    teamView: uiText(locale, "App_labels.teamView"),
    noMessages: uiText(locale, "App_labels.noMessages"),
    unavailable: uiText(locale, "App_labels.unavailable"),
    history: uiText(locale, "App_labels.history"),
    teamStop: uiText(locale, "App_labels.teamStop"),
    parent: uiText(locale, "App_labels.parent"),
    everyone: uiText(locale, "App_labels.everyone"),
    expand: uiText(locale, "App_labels.expand"),
    collapse: uiText(locale, "App_labels.collapse"),
  })),
  App_teamStatusLabels: makeUiCopy((locale) => ({
    forming: uiText(locale, "App_teamStatusLabels.forming"),
    teamRunning: uiText(locale, "App_copy_9734.running"),
    blocked: uiText(locale, "App_teamStatusLabels.blocked"),
    integrating: uiText(locale, "App_teamStatusLabels.integrating"),
    completed: uiText(locale, "App_copy.completed"),
    aborted: uiText(locale, "App_teamStatusLabels.aborted"),
  })),
  App_messageKindLabels: makeUiCopy((locale) => ({
    finding: uiText(locale, "App_messageKindLabels.finding"),
    request: uiText(locale, "App_messageKindLabels.request"),
    blocker: uiText(locale, "App_messageKindLabels.blocker"),
    handoff: uiText(locale, "App_messageKindLabels.handoff"),
  })),
  App_labels_10125: makeUiCopy((locale) => ({
    waiting: uiText(locale, "App_labels_10125.waiting"),
    unavailable: uiText(locale, "App_labels_10125.unavailable"),
    task: uiText(locale, "App_labels_10125.task"),
    activityLog: uiText(locale, "App_labels_10125.activityLog"),
    result: uiText(locale, "App_labels_10125.result"),
    runtimeDetails: uiText(locale, "App_labels_10125.runtimeDetails"),
    elapsed: uiText(locale, "App_labels_10125.elapsed"),
    lastActivity: uiText(locale, "App_labels_10125.lastActivity"),
    currentTool: uiText(locale, "App_labels_10125.currentTool"),
    health: uiText(locale, "App_labels_10125.health"),
    longRunning: uiText(locale, "App_labels_10125.longRunning"),
    unresponsive: uiText(locale, "App_labels_10125.unresponsive"),
    nudge: uiText(locale, "App_labels_10125.nudge"),
    childStop: uiText(locale, "App_labels_10125.childStop"),
    retry: uiText(locale, "App_copy.queueRetry"),
    justNow: uiText(locale, "App_labels_10125.justNow"),
    ago: uiText(locale, "App_labels_10125.ago"),
    subagent: uiText(locale, "App_labels_10125.subagent"),
  })),
  App_disclosureLabels: makeUiCopy((locale) => ({
    collapse: uiText(locale, "App_disclosureLabels.collapse"),
    expand: uiText(locale, "App_disclosureLabels.expand"),
    toolGroupCalls: uiText(locale, "App_disclosureLabels.toolGroupCalls"),
    toolGroupRead: uiText(locale, "App_disclosureLabels.toolGroupRead"),
    toolGroupEdit: uiText(locale, "App_disclosureLabels.toolGroupEdit"),
  })),
  App_childStatusLabels: makeUiCopy((locale) => ({
    queued: uiText(locale, "App_childStatusLabels.queued"),
    running: uiText(locale, "App_copy_9734.running"),
    blocked: uiText(locale, "App_childStatusLabels.blocked"),
    cancelling: uiText(locale, "App_copy_9734.cancelling"),
    completed: uiText(locale, "App_copy.completed"),
    failed: uiText(locale, "App_copy.failed"),
    cancelled: uiText(locale, "App_copy_9734.cancelled"),
  })),
  App_approvalDisclosureLabels: makeUiCopy((locale) => ({
    collapse: uiText(locale, "App_disclosureLabels.collapse"),
    expand: uiText(locale, "App_disclosureLabels.expand"),
  })),
  ArchivePage_labels: makeUiCopy((locale) => ({
    archiveTitle: uiText(locale, "ArchivePage_labels.archiveTitle"),
    archiveDescription: uiText(locale, "ArchivePage_labels.archiveDescription"),
    archiveSearch: uiText(locale, "ArchivePage_labels.archiveSearch"),
    archiveOpen: uiText(locale, "ArchivePage_labels.archiveOpen"),
    archiveRestore: uiText(locale, "ArchivePage_labels.archiveRestore"),
    archiveDelete: uiText(locale, "App_copy.deleteTask"),
    archiveSectionTitle: uiText(
      locale,
      "ArchivePage_labels.archiveSectionTitle",
    ),
    archiveCountOne: uiText(locale, "ArchivePage_labels.archiveCountOne"),
    archiveCountOther: uiText(locale, "ArchivePage_labels.archiveCountOther"),
    archiveMatchOne: uiText(locale, "ArchivePage_labels.archiveMatchOne"),
    archiveMatchOther: uiText(locale, "ArchivePage_labels.archiveMatchOther"),
    archiveEmptyTitle: uiText(locale, "ArchivePage_labels.archiveEmptyTitle"),
    archiveEmptyDescription: uiText(
      locale,
      "ArchivePage_labels.archiveEmptyDescription",
    ),
    archiveNoResultsTitle: uiText(
      locale,
      "ArchivePage_labels.archiveNoResultsTitle",
    ),
    archiveNoResultsDescription: uiText(
      locale,
      "ArchivePage_labels.archiveNoResultsDescription",
    ),
    archiveClearSearch: uiText(locale, "ArchivePage_labels.archiveClearSearch"),
    archiveGoal: uiText(locale, "App_copy.goal"),
    archiveTemporary: uiText(locale, "App_copy.temporaryConversation"),
  })),
  AutomationPage_text: makeUiCopy((locale) => ({
    title: uiText(locale, "App_copy.automations"),
    subtitle: uiText(locale, "AutomationPage_text.subtitle"),
    create: uiText(locale, "AutomationPage_text.create"),
    allProjects: uiText(locale, "AutomationPage_text.allProjects"),
    empty: uiText(locale, "AutomationPage_text.empty"),
    enabled: uiText(locale, "AutomationPage_text.enabled"),
    paused: uiText(locale, "AutomationPage_text.paused"),
    pauseTask: uiText(locale, "AutomationPage_text.pauseTask"),
    enableTask: uiText(locale, "AutomationPage_text.enableTask"),
    authorizationRequired: uiText(
      locale,
      "AutomationPage_text.authorizationRequired",
    ),
    authorize: uiText(locale, "AutomationPage_text.authorize"),
    runNow: uiText(locale, "AutomationPage_text.runNow"),
    edit: uiText(locale, "AutomationPage_text.edit"),
    delete: uiText(locale, "AutomationPage_text.delete"),
    history: uiText(locale, "AutomationPage_text.history"),
    noRuns: uiText(locale, "AutomationPage_text.noRuns"),
    nextRun: uiText(locale, "AutomationPage_text.nextRun"),
    lastRun: uiText(locale, "AutomationPage_text.lastRun"),
    never: uiText(locale, "AutomationPage_text.never"),
    save: uiText(locale, "App_copy.renameSave"),
    cancel: uiText(locale, "App_copy.renameCancel"),
    name: uiText(locale, "AutomationPage_text.name"),
    prompt: uiText(locale, "AutomationPage_text.prompt"),
    project: uiText(locale, "AutomationPage_text.project"),
    mode: uiText(locale, "AutomationPage_text.mode"),
    target: uiText(locale, "AutomationPage_text.target"),
    schedule: uiText(locale, "AutomationPage_text.schedule"),
    date: uiText(locale, "AutomationPage_text.date"),
    time: uiText(locale, "AutomationPage_text.time"),
    chooseTime: uiText(locale, "AutomationPage_text.chooseTime"),
    hour: uiText(locale, "AutomationPage_text.hour"),
    minute: uiText(locale, "AutomationPage_text.minute"),
    timeZone: uiText(locale, "AutomationPage_text.timeZone"),
    once: uiText(locale, "AutomationPage_text.once"),
    daily: uiText(locale, "AutomationPage_text.daily"),
    weekdays: uiText(locale, "AutomationPage_text.weekdays"),
    weekly: uiText(locale, "AutomationPage_text.weekly"),
    interval: uiText(locale, "AutomationPage_text.interval"),
    windowedInterval: uiText(locale, "AutomationPage_text.windowedInterval"),
    windowStart: uiText(locale, "AutomationPage_text.windowStart"),
    windowEnd: uiText(locale, "AutomationPage_text.windowEnd"),
    intervalUnit: uiText(locale, "AutomationPage_text.intervalUnit"),
    minutes: uiText(locale, "AutomationPage_text.minutes"),
    hours: uiText(locale, "AutomationPage_text.hours"),
    days: uiText(locale, "AutomationPage_text.days"),
    local: uiText(locale, "AutomationPage_text.local"),
    managed: uiText(locale, "AutomationPage_text.managed"),
    unavailableProject: uiText(
      locale,
      "AutomationPage_text.unavailableProject",
    ),
    deleteConfirm: uiText(locale, "AutomationPage_text.deleteConfirm"),
    executeWarning: uiText(locale, "AutomationPage_text.executeWarning"),
  })),
  ComposerContextBar_labels: makeUiCopy((locale) => ({
    projectMenu: uiText(locale, "ComposerContextBar_labels.projectMenu"),
    searchProjects: uiText(locale, "ComposerContextBar_labels.searchProjects"),
    addProject: uiText(locale, "ComposerContextBar_labels.addProject"),
    clearProject: uiText(locale, "ComposerContextBar_labels.clearProject"),
    temporaryConversation: uiText(locale, "App_copy.temporaryConversation"),
    noProjects: uiText(locale, "ComposerContextBar_labels.noProjects"),
    branchMenu: uiText(locale, "ComposerContextBar_labels.branchMenu"),
    searchBranches: uiText(locale, "ComposerContextBar_labels.searchBranches"),
    branches: uiText(locale, "ComposerContextBar_labels.branches"),
    noBranches: uiText(locale, "ComposerContextBar_labels.noBranches"),
    createBranch: uiText(locale, "ComposerContextBar_labels.createBranch"),
    branchName: uiText(locale, "ComposerContextBar_labels.branchName"),
    branchNamePlaceholder: uiText(
      locale,
      "ComposerContextBar_labels.branchNamePlaceholder",
    ),
    branchNameHelp: uiText(locale, "ComposerContextBar_labels.branchNameHelp"),
    cancel: uiText(locale, "App_copy.renameCancel"),
    create: uiText(locale, "ComposerContextBar_labels.create"),
    retry: uiText(locale, "App_copy.queueRetry"),
    loadingGit: uiText(locale, "ComposerContextBar_labels.loadingGit"),
    changingBranch: uiText(locale, "ComposerContextBar_labels.changingBranch"),
    taskMode: uiText(locale, "App_copy.taskMode"),
    plan: uiText(locale, "ComposerContextBar_labels.plan"),
    execute: uiText(locale, "App_copy.execute"),
    review: uiText(locale, "App_copy.review"),
    detached: uiText(locale, "ComposerContextBar_labels.detached"),
    stopTasks: uiText(locale, "ComposerContextBar_labels.stopTasks"),
    uncommitted: (count: number) =>
      count === 1
        ? uiText(locale, "ComposerContextBar_labels.uncommitted_one", { count })
        : uiText(locale, "ComposerContextBar_labels.uncommitted_other", {
            count,
          }),
  })),
  ContextUsageIndicator_CONTEXT_USAGE_COPY: makeUiCopy((locale) => ({
    title: uiText(locale, "ContextUsageIndicator_CONTEXT_USAGE_COPY.title"),
    summary: uiText(locale, "ContextUsageIndicator_CONTEXT_USAGE_COPY.summary"),
    estimatedSummary: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.estimatedSummary",
    ),
    unknownSummary: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.unknownSummary",
    ),
    tokens: uiText(locale, "ContextUsageIndicator_CONTEXT_USAGE_COPY.tokens"),
    estimatedTokens: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.estimatedTokens",
    ),
    localEstimatedTokens: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.localEstimatedTokens",
    ),
    providerInput: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.providerInput",
    ),
    breakdown: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.breakdown",
    ),
    systemPrompt: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.systemPrompt",
    ),
    systemTools: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.systemTools",
    ),
    mcpTools: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.mcpTools",
    ),
    customAgents: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.customAgents",
    ),
    memoryFiles: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.memoryFiles",
    ),
    skills: uiText(locale, "ContextUsageIndicator_CONTEXT_USAGE_COPY.skills"),
    messages: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.messages",
    ),
    freeSpace: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.freeSpace",
    ),
    autocompactBuffer: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.autocompactBuffer",
    ),
    compacting: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.compacting",
    ),
    unknown: uiText(locale, "ContextUsageIndicator_CONTEXT_USAGE_COPY.unknown"),
  })),
  CustomAgentsSettingsSection_labels: makeUiCopy((locale) => ({
    title: uiText(locale, "CustomAgentsSettingsSection_labels.title"),
    hint: uiText(locale, "CustomAgentsSettingsSection_labels.hint"),
    count: uiText(locale, "CustomAgentsSettingsSection_labels.count"),
    add: uiText(locale, "CustomAgentsSettingsSection_labels.add"),
    edit: uiText(locale, "AutomationPage_text.edit"),
    delete: uiText(locale, "AutomationPage_text.delete"),
    confirmDelete: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.confirmDelete",
    ),
    cancelDelete: uiText(locale, "App_copy.renameCancel"),
    empty: uiText(locale, "CustomAgentsSettingsSection_labels.empty"),
    emptyHint: uiText(locale, "CustomAgentsSettingsSection_labels.emptyHint"),
    closeDialog: uiText(locale, "App_copy.renameClose"),
    editorEditTitle: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.editorEditTitle",
    ),
    editorHint: uiText(locale, "CustomAgentsSettingsSection_labels.editorHint"),
    name: uiText(locale, "AutomationPage_text.name"),
    nameRequired: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.nameRequired",
    ),
    description: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.description",
    ),
    color: uiText(locale, "CustomAgentsSettingsSection_labels.color"),
    instructions: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.instructions",
    ),
    instructionsRequired: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.instructionsRequired",
    ),
    instructionsUsage: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.instructionsUsage",
    ),
    instructionsLong: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.instructionsLong",
    ),
    instructionsInheritedWindow: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.instructionsInheritedWindow",
    ),
    instructionsFixedWindow: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.instructionsFixedWindow",
    ),
    instructionsHint: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.instructionsHint",
    ),
    scope: uiText(locale, "CustomAgentsSettingsSection_labels.scope"),
    scopeAll: uiText(locale, "AutomationPage_text.allProjects"),
    scopeSelected: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.scopeSelected",
    ),
    scopeHint: uiText(locale, "CustomAgentsSettingsSection_labels.scopeHint"),
    projects: uiText(locale, "App_copy.projects"),
    modelPolicy: uiText(locale, "App_copy.modelPickerModel"),
    modelInherit: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.modelInherit",
    ),
    modelFixed: uiText(locale, "CustomAgentsSettingsSection_labels.modelFixed"),
    modelChoose: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.modelChoose",
    ),
    modelEmpty: uiText(locale, "CustomAgentsSettingsSection_labels.modelEmpty"),
    modelUnavailable: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.modelUnavailable",
    ),
    modelSearch: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.modelSearch",
    ),
    modelNoResults: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.modelNoResults",
    ),
    thinkingPolicy: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.thinkingPolicy",
    ),
    thinkingInherit: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.modelInherit",
    ),
    thinkingFixed: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.thinkingFixed",
    ),
    toolPolicy: uiText(locale, "CustomAgentsSettingsSection_labels.toolPolicy"),
    toolInherit: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.toolInherit",
    ),
    toolAllowlist: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.toolAllowlist",
    ),
    builtinTools: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.builtinTools",
    ),
    mcpTools: uiText(locale, "CustomAgentsSettingsSection_labels.mcpTools"),
    mcpToolsCount: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.mcpToolsCount",
    ),
    mcpToolsSelected: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.mcpToolsSelected",
    ),
    enabledLabel: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.enabledLabel",
    ),
    allowAutomatic: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.allowAutomatic",
    ),
    allowAutomaticHint: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.allowAutomaticHint",
    ),
    triggers: uiText(locale, "CustomAgentsSettingsSection_labels.triggers"),
    triggersHint: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.triggersHint",
    ),
    save: uiText(locale, "CustomAgentsSettingsSection_labels.save"),
    cancelEdit: uiText(locale, "App_copy.renameCancel"),
    revisionConflict: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.revisionConflict",
    ),
    capabilityPreview: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.capabilityPreview",
    ),
    scopeBadgeAll: uiText(locale, "AutomationPage_text.allProjects"),
    scopeBadgeSelected: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.scopeBadgeSelected",
    ),
    disabledBadge: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.disabledBadge",
    ),
    automaticBadge: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.automaticBadge",
    ),
    manualBadge: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.manualBadge",
    ),
    modelBadgeInherit: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.modelBadgeInherit",
    ),
    toolBadgeInherit: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.toolBadgeInherit",
    ),
    toolBadgeCount: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.mcpToolsCount",
    ),
    automaticBudgetExceeded: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.automaticBudgetExceeded",
    ),
  })),
  EnvironmentPanel_labels: makeUiCopy((locale) => ({
    trigger: uiText(locale, "EnvironmentPanel_labels.trigger"),
    close: uiText(locale, "App_copy.renameClose"),
    workspaceLabel: uiText(locale, "EnvironmentPanel_labels.workspaceLabel"),
    viewChanges: uiText(locale, "EnvironmentPanel_labels.viewChanges"),
    changedFiles: (count: number) =>
      uiText(locale, "EnvironmentPanel_labels.changedFiles", { count }),
    title: uiText(locale, "EnvironmentPanel_labels.title"),
    addProject: uiText(locale, "EnvironmentPanel_labels.addProject"),
    changes: uiText(locale, "EnvironmentPanel_labels.viewChanges"),
    local: uiText(locale, "App_copy.local"),
    branch: uiText(locale, "EnvironmentPanel_labels.branch"),
    branchMenu: uiText(locale, "ComposerContextBar_labels.branchMenu"),
    branchSearch: (project: string) =>
      uiText(locale, "EnvironmentPanel_labels.branchSearch", { project }),
    branches: uiText(locale, "ComposerContextBar_labels.branches"),
    noBranches: uiText(locale, "EnvironmentPanel_labels.noBranches"),
    createBranch: uiText(locale, "ComposerContextBar_labels.createBranch"),
    branchName: uiText(locale, "ComposerContextBar_labels.branchName"),
    branchNameHelp: uiText(locale, "ComposerContextBar_labels.branchNameHelp"),
    create: uiText(locale, "ComposerContextBar_labels.create"),
    changingBranch: uiText(locale, "ComposerContextBar_labels.changingBranch"),
    detached: uiText(locale, "EnvironmentPanel_labels.detached"),
    detachedBlocked: uiText(locale, "EnvironmentPanel_labels.detachedBlocked"),
    compareBranch: uiText(locale, "EnvironmentPanel_labels.compareBranch"),
    noCompareBase: uiText(locale, "EnvironmentPanel_labels.noCompareBase"),
    commitOrPush: uiText(locale, "EnvironmentPanel_labels.commitOrPush"),
    commitMessage: uiText(locale, "EnvironmentPanel_labels.commitMessage"),
    commitMessagePlaceholder: uiText(
      locale,
      "EnvironmentPanel_labels.commitMessagePlaceholder",
    ),
    generatingCommit: uiText(
      locale,
      "EnvironmentPanel_labels.generatingCommit",
    ),
    generatingPush: uiText(locale, "EnvironmentPanel_labels.generatingPush"),
    includeUnstaged: uiText(locale, "EnvironmentPanel_labels.includeUnstaged"),
    commit: uiText(locale, "EnvironmentPanel_labels.commit"),
    commitAndPush: uiText(locale, "EnvironmentPanel_labels.commitAndPush"),
    push: uiText(locale, "EnvironmentPanel_labels.push"),
    commitAndPushConfirm: (count: number, upstream: string) =>
      count === 1
        ? uiText(locale, "EnvironmentPanel_labels.commitAndPushConfirm_one", {
            count,
            upstream,
          })
        : uiText(locale, "EnvironmentPanel_labels.commitAndPushConfirm_other", {
            count,
            upstream,
          }),
    commitDestination: uiText(
      locale,
      "EnvironmentPanel_labels.commitDestination",
    ),
    newBranch: uiText(locale, "EnvironmentPanel_labels.newBranch"),
    newBranchPlaceholder: uiText(
      locale,
      "EnvironmentPanel_labels.newBranchPlaceholder",
    ),
    noSelectedChanges: uiText(
      locale,
      "EnvironmentPanel_labels.noSelectedChanges",
    ),
    commitChangesFirst: uiText(
      locale,
      "EnvironmentPanel_labels.commitChangesFirst",
    ),
    cancel: uiText(locale, "App_copy.renameCancel"),
    pushCommits: (count: number) =>
      count === 1
        ? uiText(locale, "EnvironmentPanel_labels.pushCommits_one", { count })
        : uiText(locale, "EnvironmentPanel_labels.pushCommits_other", {
            count,
          }),
    pushConfirm: (count: number, upstream: string) =>
      count === 1
        ? uiText(locale, "EnvironmentPanel_labels.pushConfirm_one", {
            count,
            upstream,
          })
        : uiText(locale, "EnvironmentPanel_labels.pushConfirm_other", {
            count,
            upstream,
          }),
    synced: uiText(locale, "EnvironmentPanel_labels.synced"),
    noUpstream: uiText(locale, "EnvironmentPanel_labels.noUpstream"),
    behind: uiText(locale, "EnvironmentPanel_labels.behind"),
    conflicts: uiText(locale, "EnvironmentPanel_labels.conflicts"),
    commitAndSwitch: uiText(locale, "EnvironmentPanel_labels.commitAndSwitch"),
    stopTasks: uiText(locale, "EnvironmentPanel_labels.stopTasks"),
    committing: uiText(locale, "EnvironmentPanel_labels.committing"),
    pushing: uiText(locale, "EnvironmentPanel_labels.pushing"),
    commitCreated: (commit: string) =>
      uiText(locale, "EnvironmentPanel_labels.commitCreated", { commit }),
    pushCompleted: (upstream: string) =>
      uiText(locale, "EnvironmentPanel_labels.pushCompleted", { upstream }),
    loading: uiText(locale, "EnvironmentPanel_labels.loading"),
    retry: uiText(locale, "App_copy.queueRetry"),
    notGit: uiText(locale, "EnvironmentPanel_labels.notGit"),
    githubChecking: uiText(locale, "EnvironmentPanel_labels.githubChecking"),
    githubStale: uiText(locale, "EnvironmentPanel_labels.githubStale"),
    pullRequestDraft: uiText(
      locale,
      "EnvironmentPanel_labels.pullRequestDraft",
    ),
    pullRequestOpen: uiText(locale, "EnvironmentPanel_labels.pullRequestOpen"),
    pullRequestMerged: uiText(
      locale,
      "EnvironmentPanel_labels.pullRequestMerged",
    ),
    pullRequestClosed: uiText(
      locale,
      "EnvironmentPanel_labels.pullRequestClosed",
    ),
    checksPassed: uiText(locale, "EnvironmentPanel_labels.checksPassed"),
    checksFailed: uiText(locale, "EnvironmentPanel_labels.checksFailed"),
    checksPending: uiText(locale, "EnvironmentPanel_labels.checksPending"),
    checksSkipped: uiText(locale, "EnvironmentPanel_labels.checksSkipped"),
    checksCancelled: uiText(locale, "EnvironmentPanel_labels.checksCancelled"),
    checksNone: uiText(locale, "EnvironmentPanel_labels.checksNone"),
    checkDetails: uiText(locale, "EnvironmentPanel_labels.checkDetails"),
    localChangesNotChecked: uiText(
      locale,
      "EnvironmentPanel_labels.localChangesNotChecked",
    ),
    unpushedCommitNotChecked: uiText(
      locale,
      "EnvironmentPanel_labels.unpushedCommitNotChecked",
    ),
    differentHeadNotChecked: uiText(
      locale,
      "EnvironmentPanel_labels.differentHeadNotChecked",
    ),
    agents: uiText(locale, "EnvironmentPanel_labels.agents"),
    taskContext: uiText(locale, "EnvironmentPanel_labels.taskContext"),
    sourceSummary: (attachments: number, calls: number) =>
      uiText(locale, "EnvironmentPanel_labels.sourceSummary", {
        attachments,
        calls,
      }),
    agentSummary: (total: number, active: number) =>
      active > 0
        ? uiText(locale, "EnvironmentPanel_labels.agentSummary_active", {
            total,
            active,
          })
        : uiText(locale, "EnvironmentPanel_labels.agentSummary_idle", {
            total,
          }),
    noAgents: uiText(locale, "EnvironmentPanel_labels.noAgents"),
    teams: uiText(locale, "EnvironmentPanel_labels.teams"),
    agentQueued: uiText(locale, "App_childStatusLabels.queued"),
    agentRunning: uiText(locale, "App_copy_9734.running"),
    agentBlocked: uiText(locale, "App_childStatusLabels.blocked"),
    agentCancelling: uiText(locale, "App_copy_9734.cancelling"),
    agentCompleted: uiText(locale, "App_copy.completed"),
    agentFailed: uiText(locale, "App_copy.failed"),
    agentCancelled: uiText(locale, "App_copy_9734.cancelled"),
    teamForming: uiText(locale, "EnvironmentPanel_labels.teamForming"),
    teamRunning: uiText(locale, "App_copy_9734.running"),
    teamBlocked: uiText(locale, "EnvironmentPanel_labels.teamBlocked"),
    teamIntegrating: uiText(locale, "EnvironmentPanel_labels.teamIntegrating"),
    teamCompleted: uiText(locale, "App_copy.completed"),
    teamAborted: uiText(locale, "App_teamStatusLabels.aborted"),
    active: uiText(locale, "EnvironmentPanel_labels.active"),
    queued: uiText(locale, "EnvironmentPanel_labels.queued"),
    blocked: uiText(locale, "EnvironmentPanel_labels.teamBlocked"),
    completed: uiText(locale, "EnvironmentPanel_labels.completed"),
    viewAll: uiText(locale, "EnvironmentPanel_labels.viewAll"),
    details: uiText(locale, "EnvironmentPanel_labels.details"),
    showLess: uiText(locale, "EnvironmentPanel_labels.showLess"),
    sources: uiText(locale, "App_copy.sources"),
    addSources: uiText(locale, "EnvironmentPanel_labels.addSources"),
    noSources: uiText(locale, "EnvironmentPanel_labels.noSources"),
    webSearch: uiText(locale, "EnvironmentPanel_labels.webSearch"),
  })),
  EnvironmentPullRequestError_labels: makeUiCopy((locale) => ({
    title: uiText(locale, "EnvironmentPullRequestError_labels.title"),
    connection: uiText(locale, "EnvironmentPullRequestError_labels.connection"),
    fallback: uiText(locale, "EnvironmentPullRequestError_labels.fallback"),
    retry: uiText(locale, "App_copy.queueRetry"),
    retrying: uiText(locale, "EnvironmentPullRequestError_labels.retrying"),
    details: uiText(locale, "EnvironmentPullRequestError_labels.details"),
    errorDetails: uiText(
      locale,
      "EnvironmentPullRequestError_labels.errorDetails",
    ),
    copy: uiText(locale, "EnvironmentPullRequestError_labels.copy"),
    copied: uiText(locale, "EnvironmentPullRequestError_labels.copied"),
    copyFailed: uiText(locale, "EnvironmentPullRequestError_labels.copyFailed"),
    close: uiText(locale, "App_copy.renameClose"),
  })),
  McpServerEditor_labels: makeUiCopy((locale) => ({
    addMcp: uiText(locale, "McpServerEditor_labels.addMcp"),
    updateMcp: uiText(locale, "McpServerEditor_labels.updateMcp"),
    newServerHint: uiText(locale, "McpServerEditor_labels.newServerHint"),
    transportChangeHint: uiText(
      locale,
      "McpServerEditor_labels.transportChangeHint",
    ),
    launchCommand: uiText(locale, "McpServerEditor_labels.launchCommand"),
    serverUrl: uiText(locale, "McpServerEditor_labels.serverUrl"),
    arguments: uiText(locale, "McpServerEditor_labels.arguments"),
    addArgument: uiText(locale, "McpServerEditor_labels.addArgument"),
    environmentVariables: uiText(
      locale,
      "McpServerEditor_labels.environmentVariables",
    ),
    environmentKey: uiText(locale, "McpServerEditor_labels.environmentKey"),
    environmentValue: uiText(locale, "McpServerEditor_labels.environmentValue"),
    addEnvironment: uiText(locale, "McpServerEditor_labels.addEnvironment"),
    environmentVariablePassthrough: uiText(
      locale,
      "McpServerEditor_labels.environmentVariablePassthrough",
    ),
    environmentVariableName: uiText(
      locale,
      "McpServerEditor_labels.environmentVariableName",
    ),
    addEnvironmentVariable: uiText(
      locale,
      "McpServerEditor_labels.addEnvironmentVariable",
    ),
    workspace: uiText(locale, "McpServerEditor_labels.workspace"),
    authentication: uiText(locale, "McpServerEditor_labels.authentication"),
    authNone: uiText(locale, "McpServerEditor_labels.authNone"),
    authBearer: uiText(locale, "McpServerEditor_labels.authBearer"),
    authOAuth: uiText(locale, "McpServerEditor_labels.authOAuth"),
    authHeaders: uiText(locale, "McpServerEditor_labels.authHeaders"),
    bearer: uiText(locale, "McpServerEditor_labels.bearer"),
    oauthHint: uiText(locale, "McpServerEditor_labels.oauthHint"),
    registryHeadersHint: uiText(
      locale,
      "McpServerEditor_labels.registryHeadersHint",
    ),
    registryCredentialsHint: uiText(
      locale,
      "McpServerEditor_labels.registryCredentialsHint",
    ),
    mcpSecurity: uiText(locale, "McpServerEditor_labels.mcpSecurity"),
    mcpAllowNetwork: uiText(locale, "McpServerEditor_labels.mcpAllowNetwork"),
    mcpAllowNetworkHint: uiText(
      locale,
      "McpServerEditor_labels.mcpAllowNetworkHint",
    ),
    mcpFullAccess: uiText(locale, "McpServerEditor_labels.mcpFullAccess"),
    mcpFullAccessHint: uiText(
      locale,
      "McpServerEditor_labels.mcpFullAccessHint",
    ),
    saveServer: uiText(locale, "McpServerEditor_labels.saveServer"),
    uninstall: uiText(locale, "McpServerEditor_labels.uninstall"),
    cancel: uiText(locale, "McpServerEditor_labels.cancel"),
    delete: uiText(locale, "AutomationPage_text.delete"),
    savingServer: uiText(locale, "App_copy.saving"),
    removingServer: uiText(locale, "McpServerEditor_labels.removingServer"),
    tryAgain: uiText(locale, "McpServerEditor_labels.tryAgain"),
    validationHeading: uiText(
      locale,
      "McpServerEditor_labels.validationHeading",
    ),
    validationCommandRequired: uiText(
      locale,
      "McpServerEditor_labels.validationCommandRequired",
    ),
    validationUrlRequired: uiText(
      locale,
      "McpServerEditor_labels.validationUrlRequired",
    ),
    validationUrlInvalid: uiText(
      locale,
      "McpServerEditor_labels.validationUrlInvalid",
    ),
    testConnection: uiText(locale, "McpServerEditor_labels.testConnection"),
    testConnectionBusy: uiText(
      locale,
      "McpServerEditor_labels.testConnectionBusy",
    ),
    testConnectionSuccess: uiText(
      locale,
      "McpServerEditor_labels.testConnectionSuccess",
    ),
    testConnectionFailure: uiText(
      locale,
      "McpServerEditor_labels.testConnectionFailure",
    ),
    testConnectionNotConnected: uiText(
      locale,
      "McpServerEditor_labels.testConnectionNotConnected",
    ),
    testSavedOnlyHint: uiText(
      locale,
      "McpServerEditor_labels.testSavedOnlyHint",
    ),
    confirmUninstall: uiText(locale, "McpServerEditor_labels.confirmUninstall"),
  })),
  MultiQuestionUserInputCard_multiQuestionCopy: makeUiCopy((locale) => ({
    questionProgress: uiText(
      locale,
      "MultiQuestionUserInputCard_multiQuestionCopy.questionProgress",
    ),
    answeredProgress: uiText(
      locale,
      "MultiQuestionUserInputCard_multiQuestionCopy.answeredProgress",
    ),
    progressLabel: uiText(
      locale,
      "MultiQuestionUserInputCard_multiQuestionCopy.progressLabel",
    ),
    questionNavLabel: uiText(
      locale,
      "MultiQuestionUserInputCard_multiQuestionCopy.questionNavLabel",
    ),
    questionTabLabel: uiText(
      locale,
      "MultiQuestionUserInputCard_multiQuestionCopy.questionTabLabel",
    ),
    recommended: uiText(locale, "App_copy.recommended"),
    otherAnswer: uiText(locale, "App_copy.otherAnswer"),
    otherAnswerDetail: uiText(locale, "App_copy.otherAnswerDetail"),
    customAnswer: uiText(locale, "App_copy.customAnswer"),
    submitAnswer: uiText(locale, "App_copy.submitAnswer"),
    submitSelection: uiText(
      locale,
      "MultiQuestionUserInputCard_multiQuestionCopy.submitSelection",
    ),
    waitingSelection: uiText(locale, "App_copy.waitingSelection"),
    timeoutHint: uiText(locale, "App_copy.timeoutHint"),
    answered: uiText(locale, "App_copy.answered"),
    timedOut: uiText(locale, "App_copy.timedOut"),
    inputCancelled: uiText(locale, "App_copy.inputCancelled"),
  })),
  ResourceCenter_labels: makeUiCopy((locale) => ({
    title: uiText(locale, "ResourceCenter_labels.title"),
    marketDescription: uiText(
      locale,
      "ResourceCenter_labels.marketDescription",
    ),
    manageDescription: uiText(
      locale,
      "ResourceCenter_labels.manageDescription",
    ),
    plugins: uiText(locale, "ResourceCenter_labels.plugins"),
    connectors: uiText(locale, "ResourceCenter_labels.connectors"),
    mcp: uiText(locale, "ResourceCenter_labels.mcp"),
    skills: uiText(locale, "ResourceCenter_labels.skills"),
    public: uiText(locale, "ResourceCenter_labels.public"),
    local: uiText(locale, "App_copy.local"),
    marketplaces: uiText(locale, "ResourceCenter_labels.marketplaces"),
    manageMarketplaces: uiText(
      locale,
      "ResourceCenter_labels.manageMarketplaces",
    ),
    marketplaceSource: uiText(
      locale,
      "ResourceCenter_labels.marketplaceSource",
    ),
    marketplaceRemoved: uiText(
      locale,
      "ResourceCenter_labels.marketplaceRemoved",
    ),
    marketplaceStale: uiText(locale, "ResourceCenter_labels.marketplaceStale"),
    removeMarketplace: uiText(
      locale,
      "ResourceCenter_labels.removeMarketplace",
    ),
    confirmRemoveMarketplace: uiText(
      locale,
      "ResourceCenter_labels.confirmRemoveMarketplace",
    ),
    moveMarketplaceUp: uiText(
      locale,
      "ResourceCenter_labels.moveMarketplaceUp",
    ),
    moveMarketplaceDown: uiText(
      locale,
      "ResourceCenter_labels.moveMarketplaceDown",
    ),
    skillConflict: uiText(locale, "ResourceCenter_labels.skillConflict"),
    featured: uiText(locale, "ResourceCenter_labels.featured"),
    installed: uiText(locale, "ResourceCenter_labels.installed"),
    manage: uiText(locale, "ResourceCenter_labels.manage"),
    backToMarketplace: uiText(
      locale,
      "ResourceCenter_labels.backToMarketplace",
    ),
    refresh: uiText(locale, "ResourceCenter_labels.refresh"),
    add: uiText(locale, "ResourceCenter_labels.add"),
    addPlugin: uiText(locale, "ResourceCenter_labels.addPlugin"),
    addPluginDescription: uiText(
      locale,
      "ResourceCenter_labels.addPluginDescription",
    ),
    backToPlugins: uiText(locale, "ResourceCenter_labels.backToPlugins"),
    localPlugin: uiText(locale, "ResourceCenter_labels.localPlugin"),
    executableExtension: uiText(
      locale,
      "ResourceCenter_labels.executableExtension",
    ),
    executableExtensionHint: uiText(
      locale,
      "ResourceCenter_labels.executableExtensionHint",
    ),
    trustExtension: uiText(locale, "ResourceCenter_labels.trustExtension"),
    extensionNetwork: uiText(locale, "ResourceCenter_labels.extensionNetwork"),
    retrust: uiText(locale, "ResourceCenter_labels.retrust"),
    extensionChanged: uiText(locale, "ResourceCenter_labels.extensionChanged"),
    addConnector: uiText(locale, "ResourceCenter_labels.addConnector"),
    addMcp: uiText(locale, "ResourceCenter_labels.addMcp"),
    addSkill: uiText(locale, "ResourceCenter_labels.addSkill"),
    browseOfficialMcp: uiText(
      locale,
      "ResourceCenter_labels.browseOfficialMcp",
    ),
    browseSkills: uiText(locale, "ResourceCenter_labels.browseSkills"),
    searchPlugins: uiText(locale, "ResourceCenter_labels.searchPlugins"),
    searchInstalled: uiText(locale, "ResourceCenter_labels.searchInstalled"),
    searchMcp: uiText(locale, "ResourceCenter_labels.searchMcp"),
    searchSkills: uiText(locale, "ResourceCenter_labels.searchSkills"),
    searchingMcp: uiText(locale, "ResourceCenter_labels.searchingMcp"),
    searchingSkills: uiText(locale, "ResourceCenter_labels.searchingSkills"),
    gitMarketplace: uiText(locale, "ResourceCenter_labels.gitMarketplace"),
    gitMarketplaceHint: uiText(
      locale,
      "ResourceCenter_labels.gitMarketplaceHint",
    ),
    offlineMarketplace: uiText(
      locale,
      "ResourceCenter_labels.offlineMarketplace",
    ),
    offlineMarketplaceHint: uiText(
      locale,
      "ResourceCenter_labels.offlineMarketplaceHint",
    ),
    importOfflineMarketplace: uiText(
      locale,
      "ResourceCenter_labels.importOfflineMarketplace",
    ),
    offline: uiText(locale, "ResourceCenter_labels.offline"),
    loadMarketplace: uiText(locale, "ResourceCenter_labels.loadMarketplace"),
    openOfficialMarketplace: uiText(
      locale,
      "ResourceCenter_labels.openOfficialMarketplace",
    ),
    publicMarketplace: uiText(
      locale,
      "ResourceCenter_labels.publicMarketplace",
    ),
    bundledPlugins: uiText(locale, "ResourceCenter_labels.bundledPlugins"),
    inspectLocalPlugin: uiText(
      locale,
      "ResourceCenter_labels.inspectLocalPlugin",
    ),
    installLocalSkill: uiText(
      locale,
      "ResourceCenter_labels.installLocalSkill",
    ),
    installRequiredDocuments: uiText(
      locale,
      "ResourceCenter_labels.installRequiredDocuments",
    ),
    requiredDocumentsDescription: uiText(
      locale,
      "ResourceCenter_labels.requiredDocumentsDescription",
    ),
    confirmRequiredDocuments: uiText(
      locale,
      "ResourceCenter_labels.confirmRequiredDocuments",
    ),
    install: uiText(locale, "ResourceCenter_labels.install"),
    configureInstall: uiText(locale, "ResourceCenter_labels.configureInstall"),
    installMcpTitle: uiText(locale, "ResourceCenter_labels.installMcpTitle"),
    installMcpMethod: uiText(locale, "ResourceCenter_labels.installMcpMethod"),
    installMcpCredentialHint: uiText(
      locale,
      "ResourceCenter_labels.installMcpCredentialHint",
    ),
    installMcpLocalWarning: uiText(
      locale,
      "ResourceCenter_labels.installMcpLocalWarning",
    ),
    optional: uiText(locale, "ResourceCenter_labels.optional"),
    cancel: uiText(locale, "App_copy.renameCancel"),
    installedLabel: uiText(locale, "ResourceCenter_labels.installed"),
    installing: uiText(locale, "ResourceCenter_labels.installing"),
    update: uiText(locale, "ResourceCenter_labels.update"),
    remove: uiText(locale, "McpServerEditor_labels.uninstall"),
    removeMcpAction: uiText(locale, "ResourceCenter_labels.removeMcpAction"),
    enabled: uiText(locale, "AutomationPage_text.enabled"),
    disabled: uiText(
      locale,
      "CustomAgentsSettingsSection_labels.disabledBadge",
    ),
    connected: uiText(locale, "ImNavigation.message12"),
    tools: uiText(locale, "ResourceCenter_labels.tools"),
    source: uiText(locale, "ResourceCenter_labels.source"),
    noMarketplaceResults: uiText(
      locale,
      "ResourceCenter_labels.noMarketplaceResults",
    ),
    noPlugins: uiText(locale, "ResourceCenter_labels.noPlugins"),
    noConnectors: uiText(locale, "ResourceCenter_labels.noConnectors"),
    noMcp: uiText(locale, "ResourceCenter_labels.noMcp"),
    noSkills: uiText(locale, "ResourceCenter_labels.noSkills"),
    noCatalogResults: uiText(locale, "ResourceCenter_labels.noCatalogResults"),
    noMcpCatalogResults: uiText(
      locale,
      "ResourceCenter_labels.noMcpCatalogResults",
    ),
    noSkillCatalogResults: uiText(
      locale,
      "ResourceCenter_labels.noSkillCatalogResults",
    ),
    needsSetup: uiText(locale, "ResourceCenter_labels.needsSetup"),
    thirdParty: uiText(locale, "ResourceCenter_labels.thirdParty"),
    confirmMcp: uiText(locale, "ResourceCenter_labels.confirmMcp"),
    confirmSkill: uiText(locale, "ResourceCenter_labels.confirmSkill"),
    confirmPlugin: uiText(locale, "ResourceCenter_labels.confirmPlugin"),
    confirmUpdatePlugin: uiText(
      locale,
      "ResourceCenter_labels.confirmUpdatePlugin",
    ),
    confirmRemovePlugin: uiText(
      locale,
      "ResourceCenter_labels.confirmRemovePlugin",
    ),
    confirmRemoveMcp: uiText(locale, "ResourceCenter_labels.confirmRemoveMcp"),
    confirmRemoveConnector: uiText(
      locale,
      "ResourceCenter_labels.confirmRemoveConnector",
    ),
    confirmRemoveSkill: uiText(
      locale,
      "ResourceCenter_labels.confirmRemoveSkill",
    ),
    confirmRemoveExtension: uiText(
      locale,
      "ResourceCenter_labels.confirmRemoveExtension",
    ),
    installedNow: uiText(locale, "ResourceCenter_labels.installedNow"),
    removedNow: uiText(locale, "ResourceCenter_labels.removedNow"),
    pluginWarnings: uiText(locale, "ResourceCenter_labels.pluginWarnings"),
    mcpSaved: uiText(locale, "ResourceCenter_labels.mcpSaved"),
    mcpRemoved: uiText(locale, "ResourceCenter_labels.mcpRemoved"),
    pluginEnabled: uiText(locale, "ResourceCenter_labels.pluginEnabled"),
    pluginDisabled: uiText(locale, "ResourceCenter_labels.pluginDisabled"),
    supported: uiText(locale, "ResourceCenter_labels.supported"),
    unsupported: uiText(locale, "ResourceCenter_labels.unsupported"),
    skillsCount: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.skills",
    ),
    mcpCount: uiText(locale, "ResourceCenter_labels.mcp"),
    appsCount: uiText(locale, "ResourceCenter_labels.connectors"),
    mcpDisabled: uiText(locale, "ResourceCenter_labels.mcpDisabled"),
    managedByPlugin: uiText(locale, "ResourceCenter_labels.managedByPlugin"),
    connectorName: uiText(locale, "ResourceCenter_labels.connectorName"),
    connectorUrl: uiText(locale, "ResourceCenter_labels.connectorUrl"),
    connectorAuth: uiText(locale, "ResourceCenter_labels.connectorAuth"),
    connectorBearer: uiText(locale, "McpServerEditor_labels.authBearer"),
    connectorHelp: uiText(locale, "ResourceCenter_labels.connectorHelp"),
    configure: uiText(locale, "ResourceCenter_labels.configure"),
    authorize: uiText(locale, "AutomationPage_text.authorize"),
    saveConnector: uiText(locale, "ResourceCenter_labels.saveConnector"),
    standalone: uiText(locale, "ResourceCenter_labels.standalone"),
    fromPlugins: uiText(locale, "ResourceCenter_labels.fromPlugins"),
    allResults: uiText(locale, "ResourceCenter_labels.allResults"),
  })),
  SettingsPanel_labels: makeUiCopy((locale) => ({
    title: uiText(locale, "App_copy.settings"),
    close: uiText(locale, "App_copy.renameClose"),
    tabGeneral: uiText(locale, "SettingsPanel_labels.tabGeneral"),
    tabProviders: uiText(locale, "SettingsPanel_labels.tabProviders"),
    providerConfigBuiltin: uiText(
      locale,
      "SettingsPanel_labels.providerConfigBuiltin",
    ),
    providerConfigCustom: uiText(locale, "App_copy.customApproval"),
    tabAgents: uiText(locale, "SettingsPanel_labels.tabAgents"),
    tabCapabilities: uiText(locale, "SettingsPanel_labels.tabCapabilities"),
    tabMaintenance: uiText(locale, "SettingsPanel_labels.tabMaintenance"),
    model: uiText(locale, "App_copy.modelPickerModel"),
    modelSearch: uiText(locale, "SettingsPanel_labels.modelSearch"),
    modelSearchEmpty: uiText(locale, "SettingsPanel_labels.modelSearchEmpty"),
    modelUnavailable: uiText(locale, "SettingsPanel_labels.modelUnavailable"),
    contextWindow: uiText(locale, "SettingsPanel_labels.contextWindow"),
    contextWindowHint: uiText(locale, "SettingsPanel_labels.contextWindowHint"),
    saveModel: uiText(locale, "SettingsPanel_labels.saveModel"),
    modelSaved: uiText(locale, "SettingsPanel_labels.modelSaved"),
    modelSaveFailed: uiText(locale, "SettingsPanel_labels.modelSaveFailed"),
    modelSavedDetail: uiText(locale, "SettingsPanel_labels.modelSavedDetail"),
    addedModels: uiText(locale, "SettingsPanel_labels.addedModels"),
    noAddedModels: uiText(locale, "SettingsPanel_labels.noAddedModels"),
    removeModel: uiText(locale, "SettingsPanel_labels.removeModel"),
    removeModelConfirm: uiText(
      locale,
      "SettingsPanel_labels.removeModelConfirm",
    ),
    removeModelCredentialConfirm: uiText(
      locale,
      "SettingsPanel_labels.removeModelCredentialConfirm",
    ),
    deleteProviderConfirm: uiText(
      locale,
      "SettingsPanel_labels.deleteProviderConfirm",
    ),
    confirm: uiText(locale, "SettingsPanel_labels.confirm"),
    language: uiText(locale, "SettingsPanel_labels.language"),
    languageSystem: uiText(locale, "SettingsPanel_labels.languageSystem"),
    languageEnglish: uiText(locale, "SettingsPanel_labels.languageEnglish"),
    languageChinese: uiText(locale, "SettingsPanel_labels.languageChinese"),
    languageHint: uiText(locale, "SettingsPanel_labels.languageHint"),
    theme: uiText(locale, "SettingsPanel_labels.theme"),
    themeSystem: uiText(locale, "SettingsPanel_labels.themeSystem"),
    themeLight: uiText(locale, "SettingsPanel_labels.themeLight"),
    themeDark: uiText(locale, "SettingsPanel_labels.themeDark"),
    themeHint: uiText(locale, "SettingsPanel_labels.themeHint"),
    profileAvatar: uiText(locale, "SettingsPanel_labels.profileAvatar"),
    profileAvatarUpload: uiText(
      locale,
      "SettingsPanel_labels.profileAvatarUpload",
    ),
    profileAvatarChange: uiText(
      locale,
      "SettingsPanel_labels.profileAvatarChange",
    ),
    profileAvatarRemove: uiText(
      locale,
      "SettingsPanel_labels.profileAvatarRemove",
    ),
    profileAvatarHint: uiText(locale, "SettingsPanel_labels.profileAvatarHint"),
    customProviders: uiText(locale, "SettingsPanel_labels.customProviders"),
    provider: uiText(locale, "SettingsPanel_labels.provider"),
    providerName: uiText(locale, "SettingsPanel_labels.providerName"),
    baseUrl: uiText(locale, "SettingsPanel_labels.baseUrl"),
    providerApi: uiText(locale, "SettingsPanel_labels.providerApi"),
    chatCompletionsApi: uiText(
      locale,
      "SettingsPanel_labels.chatCompletionsApi",
    ),
    responsesApi: uiText(locale, "SettingsPanel_labels.responsesApi"),
    modelId: uiText(locale, "SettingsPanel_labels.modelId"),
    modelName: uiText(locale, "SettingsPanel_labels.modelName"),
    maxTokens: uiText(locale, "SettingsPanel_labels.maxTokens"),
    reasoningModel: uiText(locale, "SettingsPanel_labels.reasoningModel"),
    highestReasoningLevel: uiText(
      locale,
      "SettingsPanel_labels.highestReasoningLevel",
    ),
    thinkingMinimal: uiText(locale, "SettingsPanel_labels.thinkingMinimal"),
    thinkingLow: uiText(locale, "SettingsPanel_labels.thinkingLow"),
    thinkingMedium: uiText(locale, "SettingsPanel_labels.thinkingMedium"),
    thinkingHigh: uiText(locale, "SettingsPanel_labels.thinkingHigh"),
    thinkingXHigh: uiText(locale, "SettingsPanel_labels.thinkingXHigh"),
    thinkingMax: uiText(locale, "SettingsPanel_labels.thinkingMax"),
    imageInput: uiText(locale, "SettingsPanel_labels.imageInput"),
    saveProvider: uiText(locale, "SettingsPanel_labels.saveProvider"),
    cancelEdit: uiText(locale, "App_copy.queueCancel"),
    providerHint: uiText(locale, "SettingsPanel_labels.providerHint"),
    configuredProviders: uiText(
      locale,
      "SettingsPanel_labels.configuredProviders",
    ),
    noProviders: uiText(locale, "SettingsPanel_labels.noProviders"),
    apiKey: uiText(locale, "SettingsPanel_labels.apiKey"),
    optionalApiKey: uiText(locale, "SettingsPanel_labels.optionalApiKey"),
    storedApiKey: uiText(locale, "SettingsPanel_labels.storedApiKey"),
    importPi: uiText(locale, "SettingsPanel_labels.importPi"),
    delete: uiText(locale, "AutomationPage_text.delete"),
    encrypted: uiText(locale, "SettingsPanel_labels.encrypted"),
    unavailable: uiText(locale, "SettingsPanel_labels.unavailable"),
    imported: uiText(locale, "SettingsPanel_labels.imported"),
    loading: uiText(locale, "App_copy.loadingSettings"),
    mcp: uiText(locale, "CustomAgentsSettingsSection_labels.mcpTools"),
    addServer: uiText(locale, "ResourceCenter_labels.addMcp"),
    backToServers: uiText(locale, "McpServerEditor_labels.cancel"),
    addMcp: uiText(locale, "McpServerEditor_labels.addMcp"),
    updateMcp: uiText(locale, "McpServerEditor_labels.updateMcp"),
    newServerHint: uiText(locale, "McpServerEditor_labels.newServerHint"),
    transportChangeHint: uiText(
      locale,
      "McpServerEditor_labels.transportChangeHint",
    ),
    serverId: uiText(locale, "SettingsPanel_labels.serverId"),
    serverName: uiText(locale, "SettingsPanel_labels.serverName"),
    transport: uiText(locale, "SettingsPanel_labels.transport"),
    endpoint: uiText(locale, "SettingsPanel_labels.endpoint"),
    launchCommand: uiText(locale, "McpServerEditor_labels.launchCommand"),
    serverUrl: uiText(locale, "McpServerEditor_labels.serverUrl"),
    arguments: uiText(locale, "McpServerEditor_labels.arguments"),
    addArgument: uiText(locale, "McpServerEditor_labels.addArgument"),
    environmentVariables: uiText(
      locale,
      "McpServerEditor_labels.environmentVariables",
    ),
    environmentKey: uiText(locale, "McpServerEditor_labels.environmentKey"),
    environmentValue: uiText(locale, "McpServerEditor_labels.environmentValue"),
    addEnvironment: uiText(locale, "McpServerEditor_labels.addEnvironment"),
    environmentVariablePassthrough: uiText(
      locale,
      "McpServerEditor_labels.environmentVariablePassthrough",
    ),
    environmentVariableName: uiText(
      locale,
      "McpServerEditor_labels.environmentVariableName",
    ),
    addEnvironmentVariable: uiText(
      locale,
      "McpServerEditor_labels.addEnvironmentVariable",
    ),
    workspace: uiText(locale, "McpServerEditor_labels.workspace"),
    bearer: uiText(locale, "McpServerEditor_labels.bearer"),
    authentication: uiText(locale, "McpServerEditor_labels.authentication"),
    authNone: uiText(locale, "McpServerEditor_labels.authNone"),
    authBearer: uiText(locale, "McpServerEditor_labels.authBearer"),
    authOAuth: uiText(locale, "McpServerEditor_labels.authOAuth"),
    authorize: uiText(locale, "AutomationPage_text.authorize"),
    oauthHint: uiText(locale, "McpServerEditor_labels.oauthHint"),
    capabilityAccess: uiText(locale, "SettingsPanel_labels.tabCapabilities"),
    shellRuntime: uiText(locale, "SettingsPanel_labels.shellRuntime"),
    shellRuntimeHint: uiText(locale, "SettingsPanel_labels.shellRuntimeHint"),
    windowsShell: uiText(locale, "SettingsPanel_labels.windowsShell"),
    windowsShellAuto: uiText(locale, "SettingsPanel_labels.windowsShellAuto"),
    windowsShellPowerShell7: uiText(
      locale,
      "SettingsPanel_labels.windowsShellPowerShell7",
    ),
    windowsShellLegacy: uiText(
      locale,
      "SettingsPanel_labels.windowsShellLegacy",
    ),
    shellProfileMode: uiText(locale, "SettingsPanel_labels.shellProfileMode"),
    shellProfileEnvironment: uiText(
      locale,
      "SettingsPanel_labels.shellProfileEnvironment",
    ),
    shellProfileFull: uiText(locale, "SettingsPanel_labels.shellProfileFull"),
    shellProfileDisabled: uiText(
      locale,
      "SettingsPanel_labels.shellProfileDisabled",
    ),
    localFullAccess: uiText(locale, "SettingsPanel_labels.localFullAccess"),
    localFullAccessDetail: uiText(
      locale,
      "SettingsPanel_labels.localFullAccessDetail",
    ),
    saveServer: uiText(locale, "McpServerEditor_labels.saveServer"),
    edit: uiText(locale, "AutomationPage_text.edit"),
    uninstall: uiText(locale, "McpServerEditor_labels.uninstall"),
    reconnect: uiText(locale, "SettingsPanel_labels.reconnect"),
    tools: uiText(locale, "ResourceCenter_labels.tools"),
    noServers: uiText(locale, "SettingsPanel_labels.noServers"),
    extensions: uiText(locale, "SettingsPanel_labels.extensions"),
    trustExtension: uiText(locale, "ResourceCenter_labels.trustExtension"),
    noExtensions: uiText(locale, "SettingsPanel_labels.noExtensions"),
    enabled: uiText(locale, "CustomAgentsSettingsSection_labels.enabledLabel"),
    extensionNetwork: uiText(locale, "SettingsPanel_labels.extensionNetwork"),
    retrust: uiText(locale, "ResourceCenter_labels.retrust"),
    extensionWarning: uiText(locale, "SettingsPanel_labels.extensionWarning"),
    updates: uiText(locale, "SettingsPanel_labels.updates"),
    checkUpdates: uiText(locale, "SettingsPanel_labels.checkUpdates"),
    installUpdate: uiText(locale, "SettingsPanel_labels.installUpdate"),
    rollbackReady: uiText(locale, "SettingsPanel_labels.rollbackReady"),
    diagnostics: uiText(locale, "SettingsPanel_labels.diagnostics"),
    diagnosticsHint: uiText(locale, "SettingsPanel_labels.diagnosticsHint"),
    exportDiagnostics: uiText(locale, "SettingsPanel_labels.exportDiagnostics"),
    diagnosticsExported: uiText(
      locale,
      "SettingsPanel_labels.diagnosticsExported",
    ),
    globalAgents: uiText(locale, "SettingsPanel_labels.globalAgents"),
    globalAgentsHint: uiText(locale, "SettingsPanel_labels.globalAgentsHint"),
    saveGlobalAgents: uiText(locale, "SettingsPanel_labels.saveGlobalAgents"),
    agentConcurrency: uiText(locale, "SettingsPanel_labels.agentConcurrency"),
    agentConcurrencyHint: uiText(
      locale,
      "SettingsPanel_labels.agentConcurrencyHint",
    ),
    concurrencyMode: uiText(locale, "SettingsPanel_labels.concurrencyMode"),
    concurrencyAutomatic: uiText(
      locale,
      "SettingsPanel_labels.concurrencyAutomatic",
    ),
    concurrencyManual: uiText(locale, "SettingsPanel_labels.concurrencyManual"),
    concurrencyManualLimit: uiText(
      locale,
      "SettingsPanel_labels.concurrencyManualLimit",
    ),
    concurrencyApply: uiText(locale, "SettingsPanel_labels.concurrencyApply"),
    concurrencyLogical: uiText(
      locale,
      "SettingsPanel_labels.concurrencyLogical",
    ),
    concurrencyConfigured: uiText(
      locale,
      "SettingsPanel_labels.concurrencyConfigured",
    ),
    concurrencyAutomaticSafe: uiText(
      locale,
      "SettingsPanel_labels.concurrencyAutomaticSafe",
    ),
    concurrencyEffective: uiText(
      locale,
      "SettingsPanel_labels.concurrencyEffective",
    ),
    concurrencyActive: uiText(locale, "SettingsPanel_labels.concurrencyActive"),
    concurrencyQueued: uiText(locale, "SettingsPanel_labels.concurrencyQueued"),
    concurrencyWaiting: uiText(
      locale,
      "SettingsPanel_labels.concurrencyWaiting",
    ),
    concurrencyHighWarning: uiText(
      locale,
      "SettingsPanel_labels.concurrencyHighWarning",
    ),
    concurrencyHardware: uiText(
      locale,
      "SettingsPanel_labels.concurrencyHardware",
    ),
    concurrencyHardwareValue: uiText(
      locale,
      "SettingsPanel_labels.concurrencyHardwareValue",
    ),
    concurrencyThrottled: uiText(
      locale,
      "SettingsPanel_labels.concurrencyThrottled",
    ),
    concurrencyCpu: uiText(locale, "SettingsPanel_labels.concurrencyCpu"),
    concurrencyEventLoop: uiText(
      locale,
      "SettingsPanel_labels.concurrencyEventLoop",
    ),
    concurrencyMemory: uiText(locale, "SettingsPanel_labels.concurrencyMemory"),
    configurationImport: uiText(
      locale,
      "SettingsPanel_labels.configurationImport",
    ),
    configurationImportHint: uiText(
      locale,
      "SettingsPanel_labels.configurationImportHint",
    ),
    scanImports: uiText(locale, "SettingsPanel_labels.scanImports"),
    applyImports: uiText(locale, "SettingsPanel_labels.applyImports"),
    importInstructions: uiText(
      locale,
      "SettingsPanel_labels.importInstructions",
    ),
    importSkills: uiText(
      locale,
      "ContextUsageIndicator_CONTEXT_USAGE_COPY.skills",
    ),
    importMcp: uiText(locale, "ResourceCenter_labels.mcp"),
    detected: uiText(locale, "SettingsPanel_labels.detected"),
    notDetected: uiText(locale, "SettingsPanel_labels.notDetected"),
    importCompleted: uiText(locale, "SettingsPanel_labels.importCompleted"),
  })),
  SourcesPanel_labels: makeUiCopy((locale) => ({
    title: uiText(locale, "App_copy.sources"),
    attachments: uiText(locale, "SourcesPanel_labels.attachments"),
    agents: uiText(locale, "SourcesPanel_labels.agents"),
    task: uiText(locale, "SourcesPanel_labels.task"),
    viewAgent: uiText(locale, "EnvironmentPullRequestError_labels.details"),
    viewFile: uiText(locale, "SourcesPanel_labels.viewFile"),
    web: uiText(locale, "SourcesPanel_labels.web"),
    empty: uiText(locale, "SourcesPanel_labels.empty"),
    draft: uiText(locale, "SourcesPanel_labels.draft"),
    sent: uiText(locale, "SourcesPanel_labels.sent"),
    parentAgent: uiText(locale, "SourcesPanel_labels.parentAgent"),
    usedBy: uiText(locale, "SourcesPanel_labels.usedBy"),
    mcpSummary: (calls: number, tools: number) =>
      calls === 1
        ? tools === 1
          ? uiText(locale, "SourcesPanel_labels.mcpSummary00", { calls, tools })
          : uiText(locale, "SourcesPanel_labels.mcpSummary01", { calls, tools })
        : tools === 1
          ? uiText(locale, "SourcesPanel_labels.mcpSummary10", { calls, tools })
          : uiText(locale, "SourcesPanel_labels.mcpSummary11", {
              calls,
              tools,
            }),
    searchSummary: (searches: number, results: number) =>
      searches === 1
        ? results === 1
          ? uiText(locale, "SourcesPanel_labels.searchSummary00", {
              searches,
              results,
            })
          : uiText(locale, "SourcesPanel_labels.searchSummary01", {
              searches,
              results,
            })
        : results === 1
          ? uiText(locale, "SourcesPanel_labels.searchSummary10", {
              searches,
              results,
            })
          : uiText(locale, "SourcesPanel_labels.searchSummary11", {
              searches,
              results,
            }),
    searchQuery: uiText(locale, "SourcesPanel_labels.searchQuery"),
    openSource: uiText(locale, "SourcesPanel_labels.openSource"),
    openImage: uiText(locale, "SourcesPanel_labels.openImage"),
    closeImage: uiText(locale, "SourcesPanel_labels.closeImage"),
    previewUnavailable: uiText(
      locale,
      "SourcesPanel_labels.previewUnavailable",
    ),
    imageUnavailable: uiText(locale, "SourcesPanel_labels.imageUnavailable"),
    showDetails: uiText(locale, "SourcesPanel_labels.showDetails"),
    hideDetails: uiText(locale, "SourcesPanel_labels.hideDetails"),
  })),
  agent_pattern_adapters_taskPlanStatusLabels: makeUiCopy((locale) => ({
    pending: uiText(
      locale,
      "agent_pattern_adapters_taskPlanStatusLabels.pending",
    ),
    in_progress: uiText(
      locale,
      "agent_pattern_adapters_taskPlanStatusLabels.in_progress",
    ),
    completed: uiText(locale, "App_copy.completed"),
    failed: uiText(locale, "App_copy.failed"),
  })),
  agent_pattern_adapters_taskPlanLabels: makeUiCopy((locale) => ({
    collapse: uiText(locale, "App_disclosureLabels.collapse"),
    expand: uiText(locale, "App_disclosureLabels.expand"),
    progress: uiText(locale, "agent_pattern_adapters_taskPlanLabels.progress"),
    taskSteps: uiText(
      locale,
      "agent_pattern_adapters_taskPlanLabels.taskSteps",
    ),
  })),
  agent_pattern_adapters_copy: makeUiCopy((locale) => ({
    toolRunning: uiText(locale, "agent_pattern_adapters_copy.toolRunning"),
    completed: uiText(locale, "App_copy.completed"),
    failed: uiText(locale, "App_copy.failed"),
  })),
  custom_agent_identity_sourceLabels: makeUiCopy((locale) => ({
    "user-explicit": uiText(
      locale,
      "custom_agent_identity_sourceLabels.user-explicit",
    ),
    "model-explicit": uiText(
      locale,
      "custom_agent_identity_sourceLabels.model-explicit",
    ),
    "model-automatic": uiText(
      locale,
      "custom_agent_identity_sourceLabels.model-automatic",
    ),
  })),
  token_usage_TOKEN_USAGE_COPY: makeUiCopy((locale) => ({
    title: uiText(locale, "App_copy.tokenUsage"),
    subtitle: uiText(locale, "token_usage_TOKEN_USAGE_COPY.subtitle"),
    activity: uiText(locale, "token_usage_TOKEN_USAGE_COPY.activity"),
    modelFilter: uiText(locale, "App_copy.modelPickerModel"),
    allModels: uiText(locale, "token_usage_TOKEN_USAGE_COPY.allModels"),
    unattributedModel: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.unattributedModel",
    ),
    usageByModel: uiText(locale, "token_usage_TOKEN_USAGE_COPY.usageByModel"),
    modelColumn: uiText(locale, "App_copy.modelPickerModel"),
    dailyTab: uiText(locale, "token_usage_TOKEN_USAGE_COPY.dailyTab"),
    weeklyTab: uiText(locale, "AutomationPage_text.weekly"),
    cumulativeTab: uiText(locale, "token_usage_TOKEN_USAGE_COPY.cumulativeTab"),
    totalTokens: uiText(locale, "token_usage_TOKEN_USAGE_COPY.totalTokens"),
    modelTotalTokens: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.modelTotalTokens",
    ),
    peakDay: uiText(locale, "token_usage_TOKEN_USAGE_COPY.peakDay"),
    peakWeek: uiText(locale, "token_usage_TOKEN_USAGE_COPY.peakWeek"),
    activeDays: uiText(locale, "token_usage_TOKEN_USAGE_COPY.activeDays"),
    longestStreak: uiText(locale, "token_usage_TOKEN_USAGE_COPY.longestStreak"),
    insights: uiText(locale, "token_usage_TOKEN_USAGE_COPY.insights"),
    averageActiveDay: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.averageActiveDay",
    ),
    mostActiveDay: uiText(locale, "token_usage_TOKEN_USAGE_COPY.mostActiveDay"),
    currentStreak: uiText(locale, "token_usage_TOKEN_USAGE_COPY.currentStreak"),
    recordedSpan: uiText(locale, "token_usage_TOKEN_USAGE_COPY.recordedSpan"),
    recordedResponses: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.recordedResponses",
    ),
    tokenComposition: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.tokenComposition",
    ),
    inputTokens: uiText(locale, "token_usage_TOKEN_USAGE_COPY.inputTokens"),
    outputTokens: uiText(locale, "token_usage_TOKEN_USAGE_COPY.outputTokens"),
    cacheReadTokens: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.cacheReadTokens",
    ),
    cacheWriteTokens: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.cacheWriteTokens",
    ),
    cacheHitTokens: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.cacheHitTokens",
    ),
    cacheHitRate: uiText(locale, "token_usage_TOKEN_USAGE_COPY.cacheHitRate"),
    cacheHitRateDescription: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.cacheHitRateDescription",
    ),
    cacheDataCoverage: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.cacheDataCoverage",
    ),
    automaticPolicyDistribution: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.automaticPolicyDistribution",
    ),
    policyDisabled: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.policyDisabled",
    ),
    policyShort: uiText(locale, "token_usage_TOKEN_USAGE_COPY.policyShort"),
    policyLong: uiText(locale, "token_usage_TOKEN_USAGE_COPY.policyLong"),
    policyExplicit30m: uiText(
      locale,
      "token_usage_TOKEN_USAGE_COPY.policyExplicit30m",
    ),
    days: uiText(locale, "token_usage_TOKEN_USAGE_COPY.days"),
    ofDays: uiText(locale, "token_usage_TOKEN_USAGE_COPY.ofDays"),
    loading: uiText(locale, "token_usage_TOKEN_USAGE_COPY.loading"),
    empty: uiText(locale, "token_usage_TOKEN_USAGE_COPY.empty"),
    error: uiText(locale, "token_usage_TOKEN_USAGE_COPY.error"),
  })),
  token_usage_TOKEN_USAGE_TOOLTIP_COPY: makeUiCopy((locale) => ({
    daily: uiText(locale, "token_usage_TOKEN_USAGE_TOOLTIP_COPY.daily"),
    weekly: uiText(locale, "token_usage_TOKEN_USAGE_TOOLTIP_COPY.weekly"),
    cumulative: uiText(
      locale,
      "token_usage_TOKEN_USAGE_TOOLTIP_COPY.cumulative",
    ),
  })),
};
