import type { AppLocale } from "@artemis/protocol";

const en = {
  paragraph: "Paragraph",
  object: "Object",
  regionSelection: "Page region",
  runtime: "Office capability",
  deactivate: "Use Lite for all three plugins",
  shared:
    "One shared runtime enhances Documents, Presentations and Spreadsheets.",
  lite: "Lite is available without this download.",
  unavailable: "A verified runtime release is not available yet.",
  install: "Install",
  offline: "Import offline pack",
  cancel: "Cancel download",
  repair: "Verify / repair",
  rollback: "Use this version",
  remove: "Remove",
  close: "Close",
  follow: "Follow changes",
  page: "Page",
  zoom: "Zoom",
  sheet: "Sheet",
  selection: "Selection",
  note: "Comment",
  addNote: "Add to message",
  region: "Drag over the page to comment on a region.",
  preview: "Preview",
  version: "Version",
  loading: "Loading document…",
  editing: "Unsaved draft",
  saved: "Saved",
  saving: "Saving…",
  opening: "Opening…",
  conflict: "File changed externally",
  recovering: "Recovering…",
  failed: "Needs attention",
  closed: "Closed",
  select: "Choose a paragraph, object or cell",
  noPreview: "Waiting for native content rendering…",
  range: "Cell range",
  sharedBy: "Shared by",
  working: "Installing…",
};
const zh: typeof en = {
  paragraph: "段落",
  object: "对象",
  regionSelection: "页面区域",
  runtime: "Office 能力包",
  deactivate: "三个插件均恢复使用 Lite",
  shared: "Documents、Presentations 和 Spreadsheets 共用一个增强运行时。",
  lite: "无需下载也可继续使用 Lite 功能。",
  unavailable: "当前还没有通过验收的能力包版本。",
  install: "安装",
  offline: "导入离线包",
  cancel: "取消下载",
  repair: "校验 / 修复",
  rollback: "使用此版本",
  remove: "卸载",
  close: "关闭",
  follow: "跟随修改",
  page: "页码",
  zoom: "缩放",
  sheet: "工作表",
  selection: "选区",
  note: "批注",
  addNote: "加入输入框",
  region: "在页面上拖动，可对区域添加批注。",
  preview: "预览",
  version: "版本",
  loading: "正在读取文档…",
  editing: "草稿未保存",
  saved: "已保存",
  saving: "正在保存…",
  opening: "正在打开…",
  conflict: "文件已被外部修改",
  recovering: "正在恢复…",
  failed: "需要处理",
  closed: "已关闭",
  select: "选择段落、对象或单元格",
  noPreview: "等待原生内容渲染…",
  range: "单元格区域",
  sharedBy: "共享插件",
  working: "正在安装…",
};
export function officeCopy(locale: AppLocale): typeof en {
  return locale.startsWith("zh") ? zh : en;
}
