import type { AppLocale } from "@artemis/protocol";

const en = {
  fitWidth: "Fit width",
  fitPage: "Fit page",
  previousPage: "Previous page",
  nextPage: "Next page",
  grid: "Data view",
  printPreview: "Print preview",
  cellHint: "Select cells to add a comment.",
  gridHint: "Values in A1:Z50. Use print preview for the original layout.",
  notePlaceholder: "Describe what you would like to change…",
  previewDetails: "Preview details",
  invalidRange: "Enter a range such as A1:B4.",
  slides: "Slides",
  cellLimit:
    "Cell selection covers A1:Z50 per sheet; the preview uses the document’s configured print areas.",
  paragraph: "Paragraph",
  object: "Object",
  regionSelection: "Page region",
  runtime: "Upgrade Office features",
  manage: "Manage Office settings",
  manageDescription:
    "Manage the Office component shared by documents, spreadsheets and presentations.",
  checkUpdates: "Check for updates",
  checkingUpdates: "Checking…",
  updateAvailable: "Version {version} is available",
  updateNow: "Update to {version}",
  upToDate: "You have the latest compatible version.",
  noUpdates: "No compatible online release was found.",
  updatesUnavailable: "Online updates are not available yet.",
  checkFailed: "Could not check for updates. Try again later.",
  offlineMaintenance: "Offline update / repair",
  selectOfflinePack: "Choose offline pack",
  offlineMaintenanceHint:
    "Choose a newer .artemis-office pack to update, or the current version to repair.",
  installed: "Installed",
  inactive: "Not active",
  inUse:
    "Close documents using Office features before removing this component.",
  removeHint:
    "Removing this component frees space and restores basic features (Lite). Your documents are kept.",
  offlineHint: "Select one .artemis-office file. No extraction is needed.",
  shared:
    "Install the preview and editing component to view original layouts and edit documents, spreadsheets and presentations. All three plugins share one installation.",
  lite: "Basic features (Lite) remain available without this download.",
  unavailable:
    "Online installation is not available yet. Import an offline pack.",
  install: "Install online",
  offline: "Import offline pack",
  cancel: "Cancel download",
  rollback: "Use this version",
  remove: "Remove",
  close: "Close",
  follow: "Follow changes",
  page: "Page",
  zoom: "Zoom",
  sheet: "Sheet",
  selection: "Selection",
  note: "Comment",
  addNote: "Add to message",
  region: "Drag over the page to comment on a region.",
  preview: "Preview",
  version: "Version",
  loading: "Loading document…",
  editing: "Unsaved draft",
  saved: "Saved",
  saving: "Saving…",
  opening: "Opening…",
  conflict: "File changed externally",
  recovering: "Recovering…",
  failed: "Needs attention",
  closed: "Closed",
  select: "Choose a paragraph, object or cell",
  noPreview: "Waiting for native content rendering…",
  range: "Cell range",
  working: "Installing…",
};
const zh: typeof en = {
  fitWidth: "适合宽度",
  fitPage: "适合窗口",
  previousPage: "上一页",
  nextPage: "下一页",
  grid: "数据视图",
  printPreview: "打印预览",
  cellHint: "拖选单元格以添加批注。",
  gridHint: "显示 A1:Z50 的单元格值，原始排版请查看打印预览。",
  notePlaceholder: "描述你希望如何修改…",
  previewDetails: "预览详情",
  invalidRange: "请输入有效区域，例如 A1:B4。",
  slides: "幻灯片",
  cellLimit: "单元格选区覆盖各工作表 A1:Z50；预览采用文档已设置的打印区域。",
  paragraph: "段落",
  object: "对象",
  regionSelection: "页面区域",
  runtime: "升级 Office 功能",
  manage: "管理 Office 配置",
  manageDescription: "管理文档、表格和演示文稿共用的 Office 组件。",
  checkUpdates: "检查更新",
  checkingUpdates: "正在检查…",
  updateAvailable: "发现新版本 {version}",
  updateNow: "更新到 {version}",
  upToDate: "当前已是可用的最新版本。",
  noUpdates: "暂未找到适用的在线版本。",
  updatesUnavailable: "在线更新暂未开放。",
  checkFailed: "检查更新失败，请稍后重试。",
  offlineMaintenance: "离线更新 / 修复",
  selectOfflinePack: "选择离线包",
  offlineMaintenanceHint:
    "选择新版 .artemis-office 包进行更新，或选择当前版本修复组件。",
  installed: "已安装",
  inactive: "未启用",
  inUse: "请先关闭正在使用 Office 功能的文档，再卸载。",
  removeHint: "卸载后恢复基础功能（Lite）并释放空间，文档会保留。",
  offlineHint: "选择一个 .artemis-office 文件即可，无需解压。",
  shared:
    "安装预览与编辑组件，支持查看原始排版并编辑文档、表格和演示文稿。三个插件共用，安装一次即可。",
  lite: "不安装也可继续使用基础功能（Lite）。",
  unavailable: "在线安装暂未开放，请导入离线包。",
  install: "在线安装",
  offline: "导入离线包",
  cancel: "取消下载",
  rollback: "使用此版本",
  remove: "卸载",
  close: "关闭",
  follow: "跟随更新",
  page: "页码",
  zoom: "缩放",
  sheet: "工作表",
  selection: "选区",
  note: "批注",
  addNote: "加入输入框",
  region: "在页面上拖动，可对区域添加批注。",
  preview: "预览",
  version: "版本",
  loading: "正在读取文档…",
  editing: "草稿未保存",
  saved: "已保存",
  saving: "正在保存…",
  opening: "正在打开…",
  conflict: "文件已被外部修改",
  recovering: "正在恢复…",
  failed: "需要处理",
  closed: "已关闭",
  select: "选择段落、对象或单元格",
  noPreview: "等待原生内容渲染…",
  range: "单元格区域",
  working: "正在安装…",
};
const translations: Record<AppLocale, typeof en> = {
  en,
  "zh-CN": zh,
  "zh-TW": {
    fitWidth: "符合寬度",
    fitPage: "符合視窗",
    previousPage: "上一頁",
    nextPage: "下一頁",
    grid: "資料檢視",
    printPreview: "列印預覽",
    cellHint: "拖曳選取儲存格以加入註解。",
    gridHint: "顯示 A1:Z50 的儲存格值，原始版面請查看列印預覽。",
    notePlaceholder: "描述你希望如何修改…",
    previewDetails: "預覽詳細資訊",
    invalidRange: "請輸入有效範圍，例如 A1:B4。",
    paragraph: "段落",
    object: "物件",
    regionSelection: "頁面區域",
    runtime: "升級 Office 功能",
    manage: "管理 Office 設定",
    manageDescription: "管理文件、試算表和簡報共用的 Office 元件。",
    checkUpdates: "檢查更新",
    checkingUpdates: "正在檢查…",
    updateAvailable: "發現新版本 {version}",
    updateNow: "更新至 {version}",
    upToDate: "目前已是相容的最新版本。",
    noUpdates: "尚未找到適用的線上版本。",
    updatesUnavailable: "線上更新尚未開放。",
    checkFailed: "檢查更新失敗，請稍後重試。",
    offlineMaintenance: "離線更新 / 修復",
    selectOfflinePack: "選擇離線套件",
    offlineMaintenanceHint:
      "選擇新版 .artemis-office 套件更新，或選擇目前版本修復元件。",
    installed: "已安裝",
    inactive: "未啟用",
    inUse: "請先關閉正在使用 Office 功能的文件，再解除安裝。",
    removeHint: "解除安裝後恢復基本功能（Lite）並釋放空間，文件會保留。",
    offlineHint: "選擇一個 .artemis-office 檔案即可，無需解壓縮。",
    shared:
      "安裝預覽與編輯元件，即可查看原始版面並編輯文件、試算表和簡報。三個外掛共用，安裝一次即可。",
    lite: "不安裝也可繼續使用基本功能（Lite）。",
    unavailable: "線上安裝尚未開放，請匯入離線套件。",
    install: "線上安裝",
    offline: "匯入離線套件",
    cancel: "取消下載",
    rollback: "使用此版本",
    remove: "解除安裝",
    close: "關閉",
    follow: "跟隨修改",
    page: "頁碼",
    zoom: "縮放",
    sheet: "工作表",
    selection: "選取範圍",
    note: "註解",
    addNote: "加入訊息",
    region: "在頁面上拖曳，可對區域加入註解。",
    preview: "預覽",
    version: "版本",
    loading: "正在讀取文件…",
    editing: "草稿未儲存",
    saved: "已儲存",
    saving: "正在儲存…",
    opening: "正在開啟…",
    conflict: "檔案已被外部修改",
    recovering: "正在復原…",
    failed: "需要處理",
    closed: "已關閉",
    select: "選擇段落、物件或儲存格",
    noPreview: "等待原生內容呈現…",
    range: "儲存格範圍",
    working: "正在安裝…",
    slides: "投影片",
    cellLimit:
      "儲存格選取範圍涵蓋各工作表 A1:Z50；預覽採用文件設定的列印範圍。",
  },
  ja: {
    fitWidth: "幅に合わせる",
    fitPage: "ページに合わせる",
    previousPage: "前のページ",
    nextPage: "次のページ",
    grid: "データ表示",
    printPreview: "印刷プレビュー",
    cellHint: "セルを選択してコメントを追加。",
    gridHint:
      "A1:Z50 の値を表示します。元のレイアウトは印刷プレビューで確認できます。",
    notePlaceholder: "変更したい内容を入力…",
    previewDetails: "プレビューの詳細",
    invalidRange: "A1:B4 のような範囲を入力してください。",
    paragraph: "段落",
    object: "オブジェクト",
    regionSelection: "ページ領域",
    runtime: "Office 機能を拡張",
    manage: "Office 設定を管理",
    manageDescription:
      "文書、表計算、プレゼンテーションで共有する Office コンポーネントを管理します。",
    checkUpdates: "更新を確認",
    checkingUpdates: "確認中…",
    updateAvailable: "バージョン {version} が利用可能です",
    updateNow: "{version} に更新",
    upToDate: "互換性のある最新バージョンです。",
    noUpdates: "互換性のあるオンライン版は見つかりませんでした。",
    updatesUnavailable: "オンライン更新はまだ利用できません。",
    checkFailed: "更新を確認できませんでした。後でもう一度お試しください。",
    offlineMaintenance: "オフライン更新 / 修復",
    selectOfflinePack: "オフラインパックを選択",
    offlineMaintenanceHint:
      "新しい .artemis-office パックで更新するか、現在のバージョンで修復します。",
    installed: "インストール済み",
    inactive: "未使用",
    inUse: "削除する前に、Office 機能を使用中の文書を閉じてください。",
    removeHint:
      "削除すると容量が解放され、基本機能（Lite）に戻ります。文書は保持されます。",
    offlineHint:
      ".artemis-office ファイルを 1 つ選択してください。展開は不要です。",
    shared:
      "Documents、Presentations、Spreadsheets は共通の実行環境で機能を拡張します。",
    lite: "ダウンロードせずに Lite を使用できます。",
    unavailable:
      "オンラインインストールはまだ利用できません。オフラインパックを読み込んでください。",
    install: "オンラインでインストール",
    offline: "オフラインパックを読み込む",
    cancel: "ダウンロードをキャンセル",
    rollback: "このバージョンを使用",
    remove: "削除",
    close: "閉じる",
    follow: "変更を追跡",
    page: "ページ",
    zoom: "ズーム",
    sheet: "シート",
    selection: "選択範囲",
    note: "コメント",
    addNote: "メッセージに追加",
    region: "ページ上をドラッグして領域にコメントします。",
    preview: "プレビュー",
    version: "バージョン",
    loading: "文書を読み込み中…",
    editing: "未保存の下書き",
    saved: "保存済み",
    saving: "保存中…",
    opening: "開いています…",
    conflict: "ファイルが外部で変更されました",
    recovering: "復元中…",
    failed: "対応が必要",
    closed: "終了",
    select: "段落、オブジェクト、セルを選択",
    noPreview: "内容の描画を待っています…",
    range: "セル範囲",
    working: "インストール中…",
    slides: "スライド",
    cellLimit:
      "セルの選択範囲は各シートの A1:Z50 です。プレビューには文書の印刷範囲を使用します。",
  },
  ko: {
    fitWidth: "너비에 맞춤",
    fitPage: "페이지에 맞춤",
    previousPage: "이전 페이지",
    nextPage: "다음 페이지",
    grid: "데이터 보기",
    printPreview: "인쇄 미리보기",
    cellHint: "셀을 선택하여 주석을 추가하세요.",
    gridHint:
      "A1:Z50의 값을 표시합니다. 원래 서식은 인쇄 미리보기에서 확인하세요.",
    notePlaceholder: "변경할 내용을 설명하세요…",
    previewDetails: "미리보기 세부 정보",
    invalidRange: "A1:B4와 같은 범위를 입력하세요.",
    paragraph: "문단",
    object: "개체",
    regionSelection: "페이지 영역",
    runtime: "Office 기능 업그레이드",
    manage: "Office 설정 관리",
    manageDescription:
      "문서, 스프레드시트 및 프레젠테이션이 공유하는 Office 구성 요소를 관리합니다.",
    checkUpdates: "업데이트 확인",
    checkingUpdates: "확인 중…",
    updateAvailable: "새 버전 {version} 사용 가능",
    updateNow: "{version}(으)로 업데이트",
    upToDate: "호환되는 최신 버전입니다.",
    noUpdates: "호환되는 온라인 버전을 찾지 못했습니다.",
    updatesUnavailable: "아직 온라인 업데이트를 사용할 수 없습니다.",
    checkFailed: "업데이트를 확인하지 못했습니다. 나중에 다시 시도하세요.",
    offlineMaintenance: "오프라인 업데이트 / 복구",
    selectOfflinePack: "오프라인 팩 선택",
    offlineMaintenanceHint:
      "새 .artemis-office 팩으로 업데이트하거나 현재 버전으로 복구하세요.",
    installed: "설치됨",
    inactive: "비활성",
    inUse: "제거하기 전에 Office 기능을 사용하는 문서를 닫으세요.",
    removeHint:
      "제거하면 공간이 확보되고 기본 기능(Lite)으로 돌아갑니다. 문서는 유지됩니다.",
    offlineHint:
      ".artemis-office 파일 하나를 선택하세요. 압축을 풀 필요가 없습니다.",
    shared:
      "Documents, Presentations, Spreadsheets가 하나의 실행 환경을 공유합니다.",
    lite: "다운로드 없이 Lite를 사용할 수 있습니다.",
    unavailable:
      "아직 온라인 설치를 사용할 수 없습니다. 오프라인 팩을 가져오세요.",
    install: "온라인 설치",
    offline: "오프라인 팩 가져오기",
    cancel: "다운로드 취소",
    rollback: "이 버전 사용",
    remove: "제거",
    close: "닫기",
    follow: "변경 사항 따라가기",
    page: "페이지",
    zoom: "확대/축소",
    sheet: "시트",
    selection: "선택 영역",
    note: "댓글",
    addNote: "메시지에 추가",
    region: "페이지를 드래그하여 영역에 댓글을 남깁니다.",
    preview: "미리 보기",
    version: "버전",
    loading: "문서 읽는 중…",
    editing: "저장하지 않은 초안",
    saved: "저장됨",
    saving: "저장 중…",
    opening: "여는 중…",
    conflict: "외부에서 파일이 변경됨",
    recovering: "복구 중…",
    failed: "확인 필요",
    closed: "닫힘",
    select: "문단, 개체 또는 셀 선택",
    noPreview: "문서 렌더링 대기 중…",
    range: "셀 범위",
    working: "설치 중…",
    slides: "슬라이드",
    cellLimit:
      "셀 선택은 각 시트의 A1:Z50을 포함합니다. 미리 보기는 문서의 인쇄 영역을 사용합니다.",
  },
  es: {
    fitWidth: "Ajustar al ancho",
    fitPage: "Ajustar página",
    previousPage: "Página anterior",
    nextPage: "Página siguiente",
    grid: "Datos",
    printPreview: "Vista de impresión",
    cellHint: "Selecciona celdas para comentar.",
    gridHint:
      "Valores de A1:Z50. Consulta el diseño original en la vista de impresión.",
    notePlaceholder: "Describe qué quieres cambiar…",
    previewDetails: "Detalles de la vista previa",
    invalidRange: "Introduce un rango como A1:B4.",
    paragraph: "Párrafo",
    object: "Objeto",
    regionSelection: "Región de página",
    runtime: "Mejorar Office",
    manage: "Administrar Office",
    manageDescription:
      "Administra el componente de Office compartido por documentos, hojas de cálculo y presentaciones.",
    checkUpdates: "Buscar actualizaciones",
    checkingUpdates: "Buscando…",
    updateAvailable: "Versión {version} disponible",
    updateNow: "Actualizar a {version}",
    upToDate: "Tienes la última versión compatible.",
    noUpdates: "No se encontró una versión en línea compatible.",
    updatesUnavailable:
      "Las actualizaciones en línea aún no están disponibles.",
    checkFailed: "No se pudieron buscar actualizaciones. Inténtalo más tarde.",
    offlineMaintenance: "Actualizar / reparar sin conexión",
    selectOfflinePack: "Elegir paquete sin conexión",
    offlineMaintenanceHint:
      "Elige un paquete .artemis-office más reciente para actualizar, o la versión actual para reparar.",
    installed: "Instalado",
    inactive: "Inactivo",
    inUse: "Cierra los documentos que usan Office antes de desinstalar.",
    removeHint:
      "Al desinstalar se libera espacio y se vuelve a las funciones básicas (Lite). Se conservan los documentos.",
    offlineHint:
      "Selecciona un archivo .artemis-office. No hace falta extraerlo.",
    shared:
      "Un entorno compartido amplía Documents, Presentations y Spreadsheets.",
    lite: "Lite está disponible sin esta descarga.",
    unavailable:
      "La instalación en línea aún no está disponible. Importa un paquete sin conexión.",
    install: "Instalar en línea",
    offline: "Importar paquete sin conexión",
    cancel: "Cancelar descarga",
    rollback: "Usar esta versión",
    remove: "Eliminar",
    close: "Cerrar",
    follow: "Seguir cambios",
    page: "Página",
    zoom: "Zoom",
    sheet: "Hoja",
    selection: "Selección",
    note: "Comentario",
    addNote: "Añadir al mensaje",
    region: "Arrastra sobre la página para comentar una región.",
    preview: "Vista previa",
    version: "Versión",
    loading: "Cargando documento…",
    editing: "Borrador sin guardar",
    saved: "Guardado",
    saving: "Guardando…",
    opening: "Abriendo…",
    conflict: "Archivo modificado externamente",
    recovering: "Recuperando…",
    failed: "Requiere atención",
    closed: "Cerrado",
    select: "Elegir párrafo, objeto o celda",
    noPreview: "Esperando la representación del contenido…",
    range: "Rango de celdas",
    working: "Instalando…",
    slides: "Diapositivas",
    cellLimit:
      "La selección abarca A1:Z50 de cada hoja; la vista previa usa las áreas de impresión del documento.",
  },
  fr: {
    fitWidth: "Ajuster en largeur",
    fitPage: "Ajuster la page",
    previousPage: "Page précédente",
    nextPage: "Page suivante",
    grid: "Données",
    printPreview: "Aperçu avant impression",
    cellHint: "Sélectionnez des cellules pour commenter.",
    gridHint:
      "Valeurs de A1:Z50. Consultez la mise en page d’origine dans l’aperçu avant impression.",
    notePlaceholder: "Décrivez les modifications souhaitées…",
    previewDetails: "Détails de l’aperçu",
    invalidRange: "Saisissez une plage comme A1:B4.",
    paragraph: "Paragraphe",
    object: "Objet",
    regionSelection: "Zone de page",
    runtime: "Améliorer Office",
    manage: "Gérer Office",
    manageDescription:
      "Gérez le composant Office partagé par les documents, les feuilles de calcul et les présentations.",
    checkUpdates: "Rechercher des mises à jour",
    checkingUpdates: "Recherche…",
    updateAvailable: "La version {version} est disponible",
    updateNow: "Mettre à jour vers {version}",
    upToDate: "Vous disposez de la dernière version compatible.",
    noUpdates: "Aucune version en ligne compatible trouvée.",
    updatesUnavailable:
      "Les mises à jour en ligne ne sont pas encore disponibles.",
    checkFailed:
      "Impossible de rechercher les mises à jour. Réessayez plus tard.",
    offlineMaintenance: "Mise à jour / réparation hors ligne",
    selectOfflinePack: "Choisir un pack hors ligne",
    offlineMaintenanceHint:
      "Choisissez un pack .artemis-office plus récent pour mettre à jour, ou la version actuelle pour réparer.",
    installed: "Installé",
    inactive: "Inactif",
    inUse: "Fermez les documents utilisant Office avant de désinstaller.",
    removeHint:
      "La désinstallation libère de l’espace et rétablit les fonctions de base (Lite). Vos documents sont conservés.",
    offlineHint: "Choisissez un fichier .artemis-office, sans le décompresser.",
    shared:
      "Un environnement partagé enrichit Documents, Presentations et Spreadsheets.",
    lite: "Lite est disponible sans téléchargement.",
    unavailable:
      "L’installation en ligne n’est pas encore disponible. Importez un pack hors ligne.",
    install: "Installer en ligne",
    offline: "Importer un pack hors ligne",
    cancel: "Annuler le téléchargement",
    rollback: "Utiliser cette version",
    remove: "Supprimer",
    close: "Fermer",
    follow: "Suivre les modifications",
    page: "Page",
    zoom: "Zoom",
    sheet: "Feuille",
    selection: "Sélection",
    note: "Commentaire",
    addNote: "Ajouter au message",
    region: "Faites glisser sur la page pour commenter une zone.",
    preview: "Aperçu",
    version: "Version",
    loading: "Chargement du document…",
    editing: "Brouillon non enregistré",
    saved: "Enregistré",
    saving: "Enregistrement…",
    opening: "Ouverture…",
    conflict: "Fichier modifié à l’extérieur",
    recovering: "Récupération…",
    failed: "Intervention requise",
    closed: "Fermé",
    select: "Choisir un paragraphe, un objet ou une cellule",
    noPreview: "En attente du rendu du contenu…",
    range: "Plage de cellules",
    working: "Installation…",
    slides: "Diapositives",
    cellLimit:
      "La sélection couvre A1:Z50 par feuille ; l’aperçu utilise les zones d’impression du document.",
  },
  de: {
    fitWidth: "An Breite anpassen",
    fitPage: "An Seite anpassen",
    previousPage: "Vorherige Seite",
    nextPage: "Nächste Seite",
    grid: "Datenansicht",
    printPreview: "Druckvorschau",
    cellHint: "Zellen zum Kommentieren auswählen.",
    gridHint:
      "Werte aus A1:Z50. Das Originallayout sehen Sie in der Druckvorschau.",
    notePlaceholder: "Gewünschte Änderungen beschreiben…",
    previewDetails: "Vorschaudetails",
    invalidRange: "Geben Sie einen Bereich wie A1:B4 ein.",
    paragraph: "Absatz",
    object: "Objekt",
    regionSelection: "Seitenbereich",
    runtime: "Office erweitern",
    manage: "Office verwalten",
    manageDescription:
      "Verwalten Sie die gemeinsame Office-Komponente für Dokumente, Tabellen und Präsentationen.",
    checkUpdates: "Nach Updates suchen",
    checkingUpdates: "Suche läuft…",
    updateAvailable: "Version {version} ist verfügbar",
    updateNow: "Auf {version} aktualisieren",
    upToDate: "Sie verwenden die neueste kompatible Version.",
    noUpdates: "Keine kompatible Online-Version gefunden.",
    updatesUnavailable: "Online-Updates sind noch nicht verfügbar.",
    checkFailed:
      "Updates konnten nicht geprüft werden. Versuchen Sie es später erneut.",
    offlineMaintenance: "Offline-Update / Reparatur",
    selectOfflinePack: "Offline-Paket auswählen",
    offlineMaintenanceHint:
      "Wählen Sie ein neueres .artemis-office-Paket zum Aktualisieren oder die aktuelle Version zum Reparieren.",
    installed: "Installiert",
    inactive: "Nicht aktiv",
    inUse:
      "Schließen Sie vor dem Entfernen die Dokumente, die Office verwenden.",
    removeHint:
      "Das Entfernen gibt Speicher frei und stellt die Basisfunktionen (Lite) wieder her. Ihre Dokumente bleiben erhalten.",
    offlineHint:
      "Wählen Sie eine .artemis-office-Datei. Entpacken ist nicht nötig.",
    shared:
      "Eine gemeinsame Laufzeit erweitert Documents, Presentations und Spreadsheets.",
    lite: "Lite ist ohne diesen Download verfügbar.",
    unavailable:
      "Die Online-Installation ist noch nicht verfügbar. Importieren Sie ein Offline-Paket.",
    install: "Online installieren",
    offline: "Offline-Paket importieren",
    cancel: "Download abbrechen",
    rollback: "Diese Version verwenden",
    remove: "Entfernen",
    close: "Schließen",
    follow: "Änderungen folgen",
    page: "Seite",
    zoom: "Zoom",
    sheet: "Tabelle",
    selection: "Auswahl",
    note: "Kommentar",
    addNote: "Zur Nachricht hinzufügen",
    region: "Zum Kommentieren eines Bereichs über die Seite ziehen.",
    preview: "Vorschau",
    version: "Version",
    loading: "Dokument wird geladen…",
    editing: "Ungespeicherter Entwurf",
    saved: "Gespeichert",
    saving: "Speichern…",
    opening: "Öffnen…",
    conflict: "Datei wurde extern geändert",
    recovering: "Wiederherstellen…",
    failed: "Aktion erforderlich",
    closed: "Geschlossen",
    select: "Absatz, Objekt oder Zelle auswählen",
    noPreview: "Warten auf die Darstellung des Inhalts…",
    range: "Zellbereich",
    working: "Installieren…",
    slides: "Folien",
    cellLimit:
      "Die Zellauswahl umfasst A1:Z50 je Tabelle; die Vorschau verwendet die Druckbereiche des Dokuments.",
  },
  "pt-BR": {
    fitWidth: "Ajustar à largura",
    fitPage: "Ajustar à página",
    previousPage: "Página anterior",
    nextPage: "Próxima página",
    grid: "Dados",
    printPreview: "Visualização de impressão",
    cellHint: "Selecione células para comentar.",
    gridHint:
      "Valores de A1:Z50. Veja o layout original na visualização de impressão.",
    notePlaceholder: "Descreva o que deseja alterar…",
    previewDetails: "Detalhes da visualização",
    invalidRange: "Insira um intervalo como A1:B4.",
    paragraph: "Parágrafo",
    object: "Objeto",
    regionSelection: "Região da página",
    runtime: "Aprimorar Office",
    manage: "Gerenciar Office",
    manageDescription:
      "Gerencie o componente do Office compartilhado por documentos, planilhas e apresentações.",
    checkUpdates: "Verificar atualizações",
    checkingUpdates: "Verificando…",
    updateAvailable: "Versão {version} disponível",
    updateNow: "Atualizar para {version}",
    upToDate: "Você tem a versão compatível mais recente.",
    noUpdates: "Nenhuma versão online compatível encontrada.",
    updatesUnavailable: "As atualizações online ainda não estão disponíveis.",
    checkFailed: "Não foi possível verificar atualizações. Tente mais tarde.",
    offlineMaintenance: "Atualização / reparo offline",
    selectOfflinePack: "Escolher pacote offline",
    offlineMaintenanceHint:
      "Escolha um pacote .artemis-office mais recente para atualizar ou a versão atual para reparar.",
    installed: "Instalado",
    inactive: "Inativo",
    inUse: "Feche os documentos que usam o Office antes de remover.",
    removeHint:
      "A remoção libera espaço e restaura as funções básicas (Lite). Seus documentos são mantidos.",
    offlineHint:
      "Selecione um arquivo .artemis-office. Não é necessário descompactar.",
    shared:
      "Um ambiente compartilhado aprimora Documents, Presentations e Spreadsheets.",
    lite: "O Lite está disponível sem este download.",
    unavailable:
      "A instalação online ainda não está disponível. Importe um pacote offline.",
    install: "Instalar online",
    offline: "Importar pacote offline",
    cancel: "Cancelar download",
    rollback: "Usar esta versão",
    remove: "Remover",
    close: "Fechar",
    follow: "Acompanhar alterações",
    page: "Página",
    zoom: "Zoom",
    sheet: "Planilha",
    selection: "Seleção",
    note: "Comentário",
    addNote: "Adicionar à mensagem",
    region: "Arraste sobre a página para comentar uma região.",
    preview: "Prévia",
    version: "Versão",
    loading: "Carregando documento…",
    editing: "Rascunho não salvo",
    saved: "Salvo",
    saving: "Salvando…",
    opening: "Abrindo…",
    conflict: "Arquivo alterado externamente",
    recovering: "Recuperando…",
    failed: "Requer atenção",
    closed: "Fechado",
    select: "Escolher parágrafo, objeto ou célula",
    noPreview: "Aguardando a renderização do conteúdo…",
    range: "Intervalo de células",
    working: "Instalando…",
    slides: "Slides",
    cellLimit:
      "A seleção abrange A1:Z50 em cada planilha; a prévia usa as áreas de impressão do documento.",
  },
  it: {
    fitWidth: "Adatta alla larghezza",
    fitPage: "Adatta alla pagina",
    previousPage: "Pagina precedente",
    nextPage: "Pagina successiva",
    grid: "Dati",
    printPreview: "Anteprima di stampa",
    cellHint: "Seleziona le celle da commentare.",
    gridHint:
      "Valori di A1:Z50. Consulta il layout originale nell’anteprima di stampa.",
    notePlaceholder: "Descrivi cosa vuoi modificare…",
    previewDetails: "Dettagli anteprima",
    invalidRange: "Inserisci un intervallo come A1:B4.",
    paragraph: "Paragrafo",
    object: "Oggetto",
    regionSelection: "Area della pagina",
    runtime: "Potenzia Office",
    manage: "Gestisci Office",
    manageDescription:
      "Gestisci il componente Office condiviso da documenti, fogli di calcolo e presentazioni.",
    checkUpdates: "Cerca aggiornamenti",
    checkingUpdates: "Ricerca…",
    updateAvailable: "È disponibile la versione {version}",
    updateNow: "Aggiorna a {version}",
    upToDate: "Hai la versione compatibile più recente.",
    noUpdates: "Nessuna versione online compatibile trovata.",
    updatesUnavailable: "Gli aggiornamenti online non sono ancora disponibili.",
    checkFailed: "Impossibile cercare aggiornamenti. Riprova più tardi.",
    offlineMaintenance: "Aggiornamento / riparazione offline",
    selectOfflinePack: "Scegli pacchetto offline",
    offlineMaintenanceHint:
      "Scegli un pacchetto .artemis-office più recente per aggiornare o la versione attuale per riparare.",
    installed: "Installato",
    inactive: "Non attivo",
    inUse:
      "Chiudi i documenti che usano Office prima di rimuovere il componente.",
    removeHint:
      "La rimozione libera spazio e ripristina le funzioni di base (Lite). I documenti vengono conservati.",
    offlineHint: "Scegli un file .artemis-office. Non è necessario estrarlo.",
    shared:
      "Un ambiente condiviso potenzia Documents, Presentations e Spreadsheets.",
    lite: "Lite è disponibile senza questo download.",
    unavailable:
      "L’installazione online non è ancora disponibile. Importa un pacchetto offline.",
    install: "Installa online",
    offline: "Importa pacchetto offline",
    cancel: "Annulla download",
    rollback: "Usa questa versione",
    remove: "Rimuovi",
    close: "Chiudi",
    follow: "Segui le modifiche",
    page: "Pagina",
    zoom: "Zoom",
    sheet: "Foglio",
    selection: "Selezione",
    note: "Commento",
    addNote: "Aggiungi al messaggio",
    region: "Trascina sulla pagina per commentare un’area.",
    preview: "Anteprima",
    version: "Versione",
    loading: "Caricamento documento…",
    editing: "Bozza non salvata",
    saved: "Salvato",
    saving: "Salvataggio…",
    opening: "Apertura…",
    conflict: "File modificato esternamente",
    recovering: "Ripristino…",
    failed: "Richiede attenzione",
    closed: "Chiuso",
    select: "Scegli paragrafo, oggetto o cella",
    noPreview: "In attesa del rendering del contenuto…",
    range: "Intervallo di celle",
    working: "Installazione…",
    slides: "Diapositive",
    cellLimit:
      "La selezione copre A1:Z50 per foglio; l’anteprima usa le aree di stampa del documento.",
  },
  ru: {
    fitWidth: "По ширине",
    fitPage: "Вся страница",
    previousPage: "Предыдущая страница",
    nextPage: "Следующая страница",
    grid: "Данные",
    printPreview: "Печать",
    cellHint: "Выберите ячейки для комментария.",
    gridHint:
      "Значения A1:Z50. Исходное оформление доступно в предпросмотре печати.",
    notePlaceholder: "Опишите нужные изменения…",
    previewDetails: "Сведения о предпросмотре",
    invalidRange: "Введите диапазон, например A1:B4.",
    paragraph: "Абзац",
    object: "Объект",
    regionSelection: "Область страницы",
    runtime: "Расширить Office",
    manage: "Настройки Office",
    manageDescription:
      "Управляйте общим компонентом Office для документов, таблиц и презентаций.",
    checkUpdates: "Проверить обновления",
    checkingUpdates: "Проверка…",
    updateAvailable: "Доступна версия {version}",
    updateNow: "Обновить до {version}",
    upToDate: "Установлена последняя совместимая версия.",
    noUpdates: "Совместимая онлайн-версия не найдена.",
    updatesUnavailable: "Онлайн-обновления пока недоступны.",
    checkFailed: "Не удалось проверить обновления. Повторите позже.",
    offlineMaintenance: "Автономное обновление / восстановление",
    selectOfflinePack: "Выбрать автономный пакет",
    offlineMaintenanceHint:
      "Выберите новый пакет .artemis-office для обновления или текущую версию для восстановления.",
    installed: "Установлено",
    inactive: "Не активно",
    inUse: "Перед удалением закройте документы, использующие функции Office.",
    removeHint:
      "Удаление освобождает место и возвращает базовые функции (Lite). Документы сохраняются.",
    offlineHint:
      "Выберите один файл .artemis-office. Распаковывать его не нужно.",
    shared:
      "Общая среда расширяет возможности Documents, Presentations и Spreadsheets.",
    lite: "Lite доступен без загрузки пакета.",
    unavailable:
      "Онлайн-установка пока недоступна. Импортируйте автономный пакет.",
    install: "Установить онлайн",
    offline: "Импортировать локальный пакет",
    cancel: "Отменить загрузку",
    rollback: "Использовать эту версию",
    remove: "Удалить",
    close: "Закрыть",
    follow: "Следить за изменениями",
    page: "Страница",
    zoom: "Масштаб",
    sheet: "Лист",
    selection: "Выделение",
    note: "Комментарий",
    addNote: "Добавить в сообщение",
    region: "Выделите область страницы перетаскиванием для комментария.",
    preview: "Предпросмотр",
    version: "Версия",
    loading: "Загрузка документа…",
    editing: "Несохранённый черновик",
    saved: "Сохранено",
    saving: "Сохранение…",
    opening: "Открытие…",
    conflict: "Файл изменён извне",
    recovering: "Восстановление…",
    failed: "Требуется внимание",
    closed: "Закрыто",
    select: "Выберите абзац, объект или ячейку",
    noPreview: "Ожидание отрисовки содержимого…",
    range: "Диапазон ячеек",
    working: "Установка…",
    slides: "Слайды",
    cellLimit:
      "Выбор ячеек охватывает A1:Z50 каждого листа; предпросмотр использует области печати документа.",
  },
  ar: {
    fitWidth: "ملاءمة العرض",
    fitPage: "ملاءمة الصفحة",
    previousPage: "الصفحة السابقة",
    nextPage: "الصفحة التالية",
    grid: "عرض البيانات",
    printPreview: "معاينة الطباعة",
    cellHint: "حدد خلايا لإضافة تعليق.",
    gridHint: "قيم A1:Z50. راجع معاينة الطباعة للتخطيط الأصلي.",
    notePlaceholder: "صف التغييرات المطلوبة…",
    previewDetails: "تفاصيل المعاينة",
    invalidRange: "أدخل نطاقًا مثل A1:B4.",
    paragraph: "فقرة",
    object: "كائن",
    regionSelection: "منطقة الصفحة",
    runtime: "ترقية ميزات Office",
    manage: "إدارة إعدادات Office",
    manageDescription:
      "إدارة مكوّن Office المشترك بين المستندات وجداول البيانات والعروض التقديمية.",
    checkUpdates: "التحقق من التحديثات",
    checkingUpdates: "جارٍ التحقق…",
    updateAvailable: "الإصدار {version} متاح",
    updateNow: "التحديث إلى {version}",
    upToDate: "لديك أحدث إصدار متوافق.",
    noUpdates: "لم يتم العثور على إصدار متوافق عبر الإنترنت.",
    updatesUnavailable: "التحديثات عبر الإنترنت غير متاحة بعد.",
    checkFailed: "تعذر التحقق من التحديثات. حاول لاحقًا.",
    offlineMaintenance: "تحديث / إصلاح دون اتصال",
    selectOfflinePack: "اختيار حزمة دون اتصال",
    offlineMaintenanceHint:
      "اختر حزمة .artemis-office أحدث للتحديث، أو الإصدار الحالي للإصلاح.",
    installed: "مثبّت",
    inactive: "غير نشط",
    inUse: "أغلق المستندات التي تستخدم ميزات Office قبل الإزالة.",
    removeHint:
      "تؤدي الإزالة إلى تحرير المساحة واستعادة الميزات الأساسية (Lite). تبقى مستنداتك محفوظة.",
    offlineHint: "اختر ملف .artemis-office واحدًا، دون فك الضغط.",
    shared: "بيئة مشتركة تعزز Documents وPresentations وSpreadsheets.",
    lite: "يمكن استخدام Lite دون تنزيل هذه الحزمة.",
    unavailable: "التثبيت عبر الإنترنت غير متاح بعد. استورد حزمة دون اتصال.",
    install: "تثبيت عبر الإنترنت",
    offline: "استيراد حزمة دون اتصال",
    cancel: "إلغاء التنزيل",
    rollback: "استخدام هذا الإصدار",
    remove: "إزالة",
    close: "إغلاق",
    follow: "متابعة التغييرات",
    page: "الصفحة",
    zoom: "التكبير",
    sheet: "ورقة",
    selection: "التحديد",
    note: "تعليق",
    addNote: "إضافة إلى الرسالة",
    region: "اسحب فوق الصفحة للتعليق على منطقة.",
    preview: "معاينة",
    version: "الإصدار",
    loading: "جارٍ تحميل المستند…",
    editing: "مسودة غير محفوظة",
    saved: "تم الحفظ",
    saving: "جارٍ الحفظ…",
    opening: "جارٍ الفتح…",
    conflict: "تم تعديل الملف خارجيًا",
    recovering: "جارٍ الاستعادة…",
    failed: "يتطلب الانتباه",
    closed: "مغلق",
    select: "اختر فقرة أو كائنًا أو خلية",
    noPreview: "بانتظار عرض المحتوى…",
    range: "نطاق الخلايا",
    working: "جارٍ التثبيت…",
    slides: "الشرائح",
    cellLimit:
      "يشمل تحديد الخلايا A1:Z50 في كل ورقة؛ وتستخدم المعاينة مناطق الطباعة المحددة في المستند.",
  },
  hi: {
    fitWidth: "चौड़ाई के अनुसार",
    fitPage: "पृष्ठ के अनुसार",
    previousPage: "पिछला पृष्ठ",
    nextPage: "अगला पृष्ठ",
    grid: "डेटा दृश्य",
    printPreview: "प्रिंट पूर्वावलोकन",
    cellHint: "टिप्पणी जोड़ने के लिए सेल चुनें।",
    gridHint: "A1:Z50 के मान। मूल लेआउट के लिए प्रिंट पूर्वावलोकन देखें।",
    notePlaceholder: "बताएँ कि आप क्या बदलना चाहते हैं…",
    previewDetails: "पूर्वावलोकन विवरण",
    invalidRange: "A1:B4 जैसी श्रेणी दर्ज करें।",
    paragraph: "अनुच्छेद",
    object: "ऑब्जेक्ट",
    regionSelection: "पेज का क्षेत्र",
    runtime: "Office सुविधाएँ बढ़ाएँ",
    manage: "Office सेटिंग प्रबंधित करें",
    manageDescription:
      "दस्तावेज़ों, स्प्रेडशीट और प्रस्तुतियों के साझा Office घटक का प्रबंधन करें।",
    checkUpdates: "अपडेट जाँचें",
    checkingUpdates: "जाँच हो रही है…",
    updateAvailable: "संस्करण {version} उपलब्ध है",
    updateNow: "{version} में अपडेट करें",
    upToDate: "आपके पास नवीनतम संगत संस्करण है।",
    noUpdates: "कोई संगत ऑनलाइन संस्करण नहीं मिला।",
    updatesUnavailable: "ऑनलाइन अपडेट अभी उपलब्ध नहीं हैं।",
    checkFailed: "अपडेट जाँचे नहीं जा सके। बाद में फिर प्रयास करें।",
    offlineMaintenance: "ऑफ़लाइन अपडेट / सुधार",
    selectOfflinePack: "ऑफ़लाइन पैक चुनें",
    offlineMaintenanceHint:
      "अपडेट के लिए नया .artemis-office पैक चुनें या सुधार के लिए वर्तमान संस्करण चुनें।",
    installed: "इंस्टॉल है",
    inactive: "सक्रिय नहीं",
    inUse: "हटाने से पहले Office सुविधाओं का उपयोग कर रहे दस्तावेज़ बंद करें।",
    removeHint:
      "हटाने से जगह खाली होती है और मूल सुविधाएँ (Lite) वापस आती हैं। आपके दस्तावेज़ सुरक्षित रहते हैं।",
    offlineHint:
      "एक .artemis-office फ़ाइल चुनें। उसे निकालने की आवश्यकता नहीं है।",
    shared:
      "एक साझा रनटाइम Documents, Presentations और Spreadsheets की क्षमताएँ बढ़ाता है।",
    lite: "इस डाउनलोड के बिना भी Lite उपलब्ध है।",
    unavailable: "ऑनलाइन इंस्टॉलेशन अभी उपलब्ध नहीं है। ऑफ़लाइन पैक आयात करें।",
    install: "ऑनलाइन इंस्टॉल करें",
    offline: "ऑफ़लाइन पैक आयात करें",
    cancel: "डाउनलोड रद्द करें",
    rollback: "इस संस्करण का उपयोग करें",
    remove: "हटाएँ",
    close: "बंद करें",
    follow: "बदलावों का अनुसरण करें",
    page: "पेज",
    zoom: "ज़ूम",
    sheet: "शीट",
    selection: "चयन",
    note: "टिप्पणी",
    addNote: "संदेश में जोड़ें",
    region: "किसी क्षेत्र पर टिप्पणी करने के लिए पेज पर खींचें।",
    preview: "पूर्वावलोकन",
    version: "संस्करण",
    loading: "दस्तावेज़ लोड हो रहा है…",
    editing: "ड्राफ़्ट सहेजा नहीं गया",
    saved: "सहेजा गया",
    saving: "सहेजा जा रहा है…",
    opening: "खोला जा रहा है…",
    conflict: "फ़ाइल बाहर से बदली गई",
    recovering: "पुनर्प्राप्त किया जा रहा है…",
    failed: "ध्यान देना ज़रूरी है",
    closed: "बंद",
    select: "अनुच्छेद, ऑब्जेक्ट या सेल चुनें",
    noPreview: "सामग्री के रेंडर होने की प्रतीक्षा…",
    range: "सेल रेंज",
    working: "इंस्टॉल हो रहा है…",
    slides: "स्लाइड",
    cellLimit:
      "सेल चयन प्रत्येक शीट में A1:Z50 तक है; पूर्वावलोकन दस्तावेज़ के निर्धारित प्रिंट क्षेत्रों का उपयोग करता है।",
  },
  id: {
    fitWidth: "Sesuaikan lebar",
    fitPage: "Sesuaikan halaman",
    previousPage: "Halaman sebelumnya",
    nextPage: "Halaman berikutnya",
    grid: "Tampilan data",
    printPreview: "Pratinjau cetak",
    cellHint: "Pilih sel untuk menambahkan komentar.",
    gridHint: "Nilai A1:Z50. Lihat tata letak asli di pratinjau cetak.",
    notePlaceholder: "Jelaskan perubahan yang diinginkan…",
    previewDetails: "Detail pratinjau",
    invalidRange: "Masukkan rentang seperti A1:B4.",
    paragraph: "Paragraf",
    object: "Objek",
    regionSelection: "Area halaman",
    runtime: "Tingkatkan fitur Office",
    manage: "Kelola pengaturan Office",
    manageDescription:
      "Kelola komponen Office bersama untuk dokumen, spreadsheet, dan presentasi.",
    checkUpdates: "Periksa pembaruan",
    checkingUpdates: "Memeriksa…",
    updateAvailable: "Versi {version} tersedia",
    updateNow: "Perbarui ke {version}",
    upToDate: "Anda memiliki versi kompatibel terbaru.",
    noUpdates: "Tidak ditemukan versi online yang kompatibel.",
    updatesUnavailable: "Pembaruan online belum tersedia.",
    checkFailed: "Tidak dapat memeriksa pembaruan. Coba lagi nanti.",
    offlineMaintenance: "Pembaruan / perbaikan offline",
    selectOfflinePack: "Pilih paket offline",
    offlineMaintenanceHint:
      "Pilih paket .artemis-office yang lebih baru untuk memperbarui, atau versi saat ini untuk memperbaiki.",
    installed: "Terinstal",
    inactive: "Tidak aktif",
    inUse: "Tutup dokumen yang menggunakan fitur Office sebelum menghapus.",
    removeHint:
      "Penghapusan mengosongkan ruang dan memulihkan fitur dasar (Lite). Dokumen Anda tetap disimpan.",
    offlineHint: "Pilih satu file .artemis-office. Tidak perlu diekstrak.",
    shared:
      "Satu lingkungan bersama meningkatkan Documents, Presentations, dan Spreadsheets.",
    lite: "Lite tersedia tanpa unduhan ini.",
    unavailable: "Instalasi online belum tersedia. Impor paket offline.",
    install: "Instal online",
    offline: "Impor paket offline",
    cancel: "Batalkan unduhan",
    rollback: "Gunakan versi ini",
    remove: "Hapus",
    close: "Tutup",
    follow: "Ikuti perubahan",
    page: "Halaman",
    zoom: "Zoom",
    sheet: "Lembar",
    selection: "Pilihan",
    note: "Komentar",
    addNote: "Tambahkan ke pesan",
    region: "Seret pada halaman untuk mengomentari suatu area.",
    preview: "Pratinjau",
    version: "Versi",
    loading: "Memuat dokumen…",
    editing: "Draf belum disimpan",
    saved: "Tersimpan",
    saving: "Menyimpan…",
    opening: "Membuka…",
    conflict: "File diubah dari luar",
    recovering: "Memulihkan…",
    failed: "Perlu perhatian",
    closed: "Ditutup",
    select: "Pilih paragraf, objek, atau sel",
    noPreview: "Menunggu perenderan konten…",
    range: "Rentang sel",
    working: "Menginstal…",
    slides: "Slide",
    cellLimit:
      "Pilihan sel mencakup A1:Z50 tiap lembar; pratinjau memakai area cetak yang ditetapkan dalam dokumen.",
  },
};
export function officeCopy(locale: AppLocale): typeof en {
  return translations[locale];
}
