import type { AppLocale } from "@artemis/protocol";

const en = {
  slides: "Slides",
  cellLimit:
    "Cell selection covers A1:Z50 per sheet; the preview uses the document’s configured print areas.",
  paragraph: "Paragraph",
  object: "Object",
  regionSelection: "Page region",
  runtime: "Office capability",
  deactivate: "Use Lite for all three plugins",
  shared:
    "One shared runtime enhances Documents, Presentations and Spreadsheets.",
  lite: "Lite is available without this download.",
  unavailable: "A verified runtime release is not available yet.",
  install: "Install",
  offline: "Import offline pack",
  cancel: "Cancel download",
  repair: "Verify / repair",
  rollback: "Use this version",
  remove: "Remove",
  close: "Close",
  follow: "Follow changes",
  page: "Page",
  zoom: "Zoom",
  sheet: "Sheet",
  selection: "Selection",
  note: "Comment",
  addNote: "Add to message",
  region: "Drag over the page to comment on a region.",
  preview: "Preview",
  version: "Version",
  loading: "Loading document…",
  editing: "Unsaved draft",
  saved: "Saved",
  saving: "Saving…",
  opening: "Opening…",
  conflict: "File changed externally",
  recovering: "Recovering…",
  failed: "Needs attention",
  closed: "Closed",
  select: "Choose a paragraph, object or cell",
  noPreview: "Waiting for native content rendering…",
  range: "Cell range",
  sharedBy: "Shared by",
  working: "Installing…",
};
const zh: typeof en = {
  slides: "幻灯片",
  cellLimit: "单元格选区覆盖各工作表 A1:Z50；预览采用文档已设置的打印区域。",
  paragraph: "段落",
  object: "对象",
  regionSelection: "页面区域",
  runtime: "Office 能力包",
  deactivate: "三个插件均恢复使用 Lite",
  shared: "Documents、Presentations 和 Spreadsheets 共用一个增强运行时。",
  lite: "无需下载也可继续使用 Lite 功能。",
  unavailable: "当前还没有通过验收的能力包版本。",
  install: "安装",
  offline: "导入离线包",
  cancel: "取消下载",
  repair: "校验 / 修复",
  rollback: "使用此版本",
  remove: "卸载",
  close: "关闭",
  follow: "跟随修改",
  page: "页码",
  zoom: "缩放",
  sheet: "工作表",
  selection: "选区",
  note: "批注",
  addNote: "加入输入框",
  region: "在页面上拖动，可对区域添加批注。",
  preview: "预览",
  version: "版本",
  loading: "正在读取文档…",
  editing: "草稿未保存",
  saved: "已保存",
  saving: "正在保存…",
  opening: "正在打开…",
  conflict: "文件已被外部修改",
  recovering: "正在恢复…",
  failed: "需要处理",
  closed: "已关闭",
  select: "选择段落、对象或单元格",
  noPreview: "等待原生内容渲染…",
  range: "单元格区域",
  sharedBy: "共享插件",
  working: "正在安装…",
};
const translations: Record<AppLocale, typeof en> = {
  en,
  "zh-CN": zh,
  "zh-TW": {
    paragraph: "段落",
    object: "物件",
    regionSelection: "頁面區域",
    runtime: "Office 能力包",
    deactivate: "三個外掛均恢復使用 Lite",
    shared: "Documents、Presentations 和 Spreadsheets 共用一個增強執行環境。",
    lite: "無需下載也可繼續使用 Lite 功能。",
    unavailable: "目前尚無通過驗證的能力包版本。",
    install: "安裝",
    offline: "匯入離線套件",
    cancel: "取消下載",
    repair: "驗證 / 修復",
    rollback: "使用此版本",
    remove: "解除安裝",
    close: "關閉",
    follow: "跟隨修改",
    page: "頁碼",
    zoom: "縮放",
    sheet: "工作表",
    selection: "選取範圍",
    note: "註解",
    addNote: "加入訊息",
    region: "在頁面上拖曳，可對區域加入註解。",
    preview: "預覽",
    version: "版本",
    loading: "正在讀取文件…",
    editing: "草稿未儲存",
    saved: "已儲存",
    saving: "正在儲存…",
    opening: "正在開啟…",
    conflict: "檔案已被外部修改",
    recovering: "正在復原…",
    failed: "需要處理",
    closed: "已關閉",
    select: "選擇段落、物件或儲存格",
    noPreview: "等待原生內容呈現…",
    range: "儲存格範圍",
    sharedBy: "共用外掛",
    working: "正在安裝…",
    slides: "投影片",
    cellLimit:
      "儲存格選取範圍涵蓋各工作表 A1:Z50；預覽採用文件設定的列印範圍。",
  },
  ja: {
    paragraph: "段落",
    object: "オブジェクト",
    regionSelection: "ページ領域",
    runtime: "Office 機能パック",
    deactivate: "3 つのプラグインで Lite を使用",
    shared:
      "Documents、Presentations、Spreadsheets は共通の実行環境で機能を拡張します。",
    lite: "ダウンロードせずに Lite を使用できます。",
    unavailable: "検証済みの機能パックはまだありません。",
    install: "インストール",
    offline: "オフラインパックを読み込む",
    cancel: "ダウンロードをキャンセル",
    repair: "検証 / 修復",
    rollback: "このバージョンを使用",
    remove: "削除",
    close: "閉じる",
    follow: "変更を追跡",
    page: "ページ",
    zoom: "ズーム",
    sheet: "シート",
    selection: "選択範囲",
    note: "コメント",
    addNote: "メッセージに追加",
    region: "ページ上をドラッグして領域にコメントします。",
    preview: "プレビュー",
    version: "バージョン",
    loading: "文書を読み込み中…",
    editing: "未保存の下書き",
    saved: "保存済み",
    saving: "保存中…",
    opening: "開いています…",
    conflict: "ファイルが外部で変更されました",
    recovering: "復元中…",
    failed: "対応が必要",
    closed: "終了",
    select: "段落、オブジェクト、セルを選択",
    noPreview: "内容の描画を待っています…",
    range: "セル範囲",
    sharedBy: "共有プラグイン",
    working: "インストール中…",
    slides: "スライド",
    cellLimit:
      "セルの選択範囲は各シートの A1:Z50 です。プレビューには文書の印刷範囲を使用します。",
  },
  ko: {
    paragraph: "문단",
    object: "개체",
    regionSelection: "페이지 영역",
    runtime: "Office 기능 팩",
    deactivate: "세 플러그인 모두 Lite 사용",
    shared:
      "Documents, Presentations, Spreadsheets가 하나의 실행 환경을 공유합니다.",
    lite: "다운로드 없이 Lite를 사용할 수 있습니다.",
    unavailable: "검증된 기능 팩이 아직 없습니다.",
    install: "설치",
    offline: "오프라인 팩 가져오기",
    cancel: "다운로드 취소",
    repair: "검증 / 복구",
    rollback: "이 버전 사용",
    remove: "제거",
    close: "닫기",
    follow: "변경 사항 따라가기",
    page: "페이지",
    zoom: "확대/축소",
    sheet: "시트",
    selection: "선택 영역",
    note: "댓글",
    addNote: "메시지에 추가",
    region: "페이지를 드래그하여 영역에 댓글을 남깁니다.",
    preview: "미리 보기",
    version: "버전",
    loading: "문서 읽는 중…",
    editing: "저장하지 않은 초안",
    saved: "저장됨",
    saving: "저장 중…",
    opening: "여는 중…",
    conflict: "외부에서 파일이 변경됨",
    recovering: "복구 중…",
    failed: "확인 필요",
    closed: "닫힘",
    select: "문단, 개체 또는 셀 선택",
    noPreview: "문서 렌더링 대기 중…",
    range: "셀 범위",
    sharedBy: "공유 플러그인",
    working: "설치 중…",
    slides: "슬라이드",
    cellLimit:
      "셀 선택은 각 시트의 A1:Z50을 포함합니다. 미리 보기는 문서의 인쇄 영역을 사용합니다.",
  },
  es: {
    paragraph: "Párrafo",
    object: "Objeto",
    regionSelection: "Región de página",
    runtime: "Paquete de Office",
    deactivate: "Usar Lite en los tres complementos",
    shared:
      "Un entorno compartido amplía Documents, Presentations y Spreadsheets.",
    lite: "Lite está disponible sin esta descarga.",
    unavailable: "Aún no hay un paquete verificado disponible.",
    install: "Instalar",
    offline: "Importar paquete sin conexión",
    cancel: "Cancelar descarga",
    repair: "Verificar / reparar",
    rollback: "Usar esta versión",
    remove: "Eliminar",
    close: "Cerrar",
    follow: "Seguir cambios",
    page: "Página",
    zoom: "Zoom",
    sheet: "Hoja",
    selection: "Selección",
    note: "Comentario",
    addNote: "Añadir al mensaje",
    region: "Arrastra sobre la página para comentar una región.",
    preview: "Vista previa",
    version: "Versión",
    loading: "Cargando documento…",
    editing: "Borrador sin guardar",
    saved: "Guardado",
    saving: "Guardando…",
    opening: "Abriendo…",
    conflict: "Archivo modificado externamente",
    recovering: "Recuperando…",
    failed: "Requiere atención",
    closed: "Cerrado",
    select: "Elegir párrafo, objeto o celda",
    noPreview: "Esperando la representación del contenido…",
    range: "Rango de celdas",
    sharedBy: "Compartido por",
    working: "Instalando…",
    slides: "Diapositivas",
    cellLimit:
      "La selección abarca A1:Z50 de cada hoja; la vista previa usa las áreas de impresión del documento.",
  },
  fr: {
    paragraph: "Paragraphe",
    object: "Objet",
    regionSelection: "Zone de page",
    runtime: "Pack Office",
    deactivate: "Utiliser Lite pour les trois extensions",
    shared:
      "Un environnement partagé enrichit Documents, Presentations et Spreadsheets.",
    lite: "Lite est disponible sans téléchargement.",
    unavailable: "Aucun pack vérifié n’est encore disponible.",
    install: "Installer",
    offline: "Importer un pack hors ligne",
    cancel: "Annuler le téléchargement",
    repair: "Vérifier / réparer",
    rollback: "Utiliser cette version",
    remove: "Supprimer",
    close: "Fermer",
    follow: "Suivre les modifications",
    page: "Page",
    zoom: "Zoom",
    sheet: "Feuille",
    selection: "Sélection",
    note: "Commentaire",
    addNote: "Ajouter au message",
    region: "Faites glisser sur la page pour commenter une zone.",
    preview: "Aperçu",
    version: "Version",
    loading: "Chargement du document…",
    editing: "Brouillon non enregistré",
    saved: "Enregistré",
    saving: "Enregistrement…",
    opening: "Ouverture…",
    conflict: "Fichier modifié à l’extérieur",
    recovering: "Récupération…",
    failed: "Intervention requise",
    closed: "Fermé",
    select: "Choisir un paragraphe, un objet ou une cellule",
    noPreview: "En attente du rendu du contenu…",
    range: "Plage de cellules",
    sharedBy: "Partagé par",
    working: "Installation…",
    slides: "Diapositives",
    cellLimit:
      "La sélection couvre A1:Z50 par feuille ; l’aperçu utilise les zones d’impression du document.",
  },
  de: {
    paragraph: "Absatz",
    object: "Objekt",
    regionSelection: "Seitenbereich",
    runtime: "Office-Funktionspaket",
    deactivate: "Lite für alle drei Plugins verwenden",
    shared:
      "Eine gemeinsame Laufzeit erweitert Documents, Presentations und Spreadsheets.",
    lite: "Lite ist ohne diesen Download verfügbar.",
    unavailable: "Noch kein geprüftes Funktionspaket verfügbar.",
    install: "Installieren",
    offline: "Offline-Paket importieren",
    cancel: "Download abbrechen",
    repair: "Prüfen / reparieren",
    rollback: "Diese Version verwenden",
    remove: "Entfernen",
    close: "Schließen",
    follow: "Änderungen folgen",
    page: "Seite",
    zoom: "Zoom",
    sheet: "Tabelle",
    selection: "Auswahl",
    note: "Kommentar",
    addNote: "Zur Nachricht hinzufügen",
    region: "Zum Kommentieren eines Bereichs über die Seite ziehen.",
    preview: "Vorschau",
    version: "Version",
    loading: "Dokument wird geladen…",
    editing: "Ungespeicherter Entwurf",
    saved: "Gespeichert",
    saving: "Speichern…",
    opening: "Öffnen…",
    conflict: "Datei wurde extern geändert",
    recovering: "Wiederherstellen…",
    failed: "Aktion erforderlich",
    closed: "Geschlossen",
    select: "Absatz, Objekt oder Zelle auswählen",
    noPreview: "Warten auf die Darstellung des Inhalts…",
    range: "Zellbereich",
    sharedBy: "Gemeinsam genutzt von",
    working: "Installieren…",
    slides: "Folien",
    cellLimit:
      "Die Zellauswahl umfasst A1:Z50 je Tabelle; die Vorschau verwendet die Druckbereiche des Dokuments.",
  },
  "pt-BR": {
    paragraph: "Parágrafo",
    object: "Objeto",
    regionSelection: "Região da página",
    runtime: "Pacote Office",
    deactivate: "Usar Lite nos três plugins",
    shared:
      "Um ambiente compartilhado aprimora Documents, Presentations e Spreadsheets.",
    lite: "O Lite está disponível sem este download.",
    unavailable: "Ainda não há um pacote verificado disponível.",
    install: "Instalar",
    offline: "Importar pacote offline",
    cancel: "Cancelar download",
    repair: "Verificar / reparar",
    rollback: "Usar esta versão",
    remove: "Remover",
    close: "Fechar",
    follow: "Acompanhar alterações",
    page: "Página",
    zoom: "Zoom",
    sheet: "Planilha",
    selection: "Seleção",
    note: "Comentário",
    addNote: "Adicionar à mensagem",
    region: "Arraste sobre a página para comentar uma região.",
    preview: "Prévia",
    version: "Versão",
    loading: "Carregando documento…",
    editing: "Rascunho não salvo",
    saved: "Salvo",
    saving: "Salvando…",
    opening: "Abrindo…",
    conflict: "Arquivo alterado externamente",
    recovering: "Recuperando…",
    failed: "Requer atenção",
    closed: "Fechado",
    select: "Escolher parágrafo, objeto ou célula",
    noPreview: "Aguardando a renderização do conteúdo…",
    range: "Intervalo de células",
    sharedBy: "Compartilhado por",
    working: "Instalando…",
    slides: "Slides",
    cellLimit:
      "A seleção abrange A1:Z50 em cada planilha; a prévia usa as áreas de impressão do documento.",
  },
  it: {
    paragraph: "Paragrafo",
    object: "Oggetto",
    regionSelection: "Area della pagina",
    runtime: "Pacchetto Office",
    deactivate: "Usa Lite per tutti e tre i plugin",
    shared:
      "Un ambiente condiviso potenzia Documents, Presentations e Spreadsheets.",
    lite: "Lite è disponibile senza questo download.",
    unavailable: "Non è ancora disponibile un pacchetto verificato.",
    install: "Installa",
    offline: "Importa pacchetto offline",
    cancel: "Annulla download",
    repair: "Verifica / ripara",
    rollback: "Usa questa versione",
    remove: "Rimuovi",
    close: "Chiudi",
    follow: "Segui le modifiche",
    page: "Pagina",
    zoom: "Zoom",
    sheet: "Foglio",
    selection: "Selezione",
    note: "Commento",
    addNote: "Aggiungi al messaggio",
    region: "Trascina sulla pagina per commentare un’area.",
    preview: "Anteprima",
    version: "Versione",
    loading: "Caricamento documento…",
    editing: "Bozza non salvata",
    saved: "Salvato",
    saving: "Salvataggio…",
    opening: "Apertura…",
    conflict: "File modificato esternamente",
    recovering: "Ripristino…",
    failed: "Richiede attenzione",
    closed: "Chiuso",
    select: "Scegli paragrafo, oggetto o cella",
    noPreview: "In attesa del rendering del contenuto…",
    range: "Intervallo di celle",
    sharedBy: "Condiviso da",
    working: "Installazione…",
    slides: "Diapositive",
    cellLimit:
      "La selezione copre A1:Z50 per foglio; l’anteprima usa le aree di stampa del documento.",
  },
  ru: {
    paragraph: "Абзац",
    object: "Объект",
    regionSelection: "Область страницы",
    runtime: "Пакет Office",
    deactivate: "Использовать Lite во всех трёх плагинах",
    shared:
      "Общая среда расширяет возможности Documents, Presentations и Spreadsheets.",
    lite: "Lite доступен без загрузки пакета.",
    unavailable: "Проверенный пакет пока недоступен.",
    install: "Установить",
    offline: "Импортировать локальный пакет",
    cancel: "Отменить загрузку",
    repair: "Проверить / восстановить",
    rollback: "Использовать эту версию",
    remove: "Удалить",
    close: "Закрыть",
    follow: "Следить за изменениями",
    page: "Страница",
    zoom: "Масштаб",
    sheet: "Лист",
    selection: "Выделение",
    note: "Комментарий",
    addNote: "Добавить в сообщение",
    region: "Выделите область страницы перетаскиванием для комментария.",
    preview: "Предпросмотр",
    version: "Версия",
    loading: "Загрузка документа…",
    editing: "Несохранённый черновик",
    saved: "Сохранено",
    saving: "Сохранение…",
    opening: "Открытие…",
    conflict: "Файл изменён извне",
    recovering: "Восстановление…",
    failed: "Требуется внимание",
    closed: "Закрыто",
    select: "Выберите абзац, объект или ячейку",
    noPreview: "Ожидание отрисовки содержимого…",
    range: "Диапазон ячеек",
    sharedBy: "Общие плагины",
    working: "Установка…",
    slides: "Слайды",
    cellLimit:
      "Выбор ячеек охватывает A1:Z50 каждого листа; предпросмотр использует области печати документа.",
  },
  ar: {
    paragraph: "فقرة",
    object: "كائن",
    regionSelection: "منطقة الصفحة",
    runtime: "حزمة Office",
    deactivate: "استخدام Lite للإضافات الثلاث",
    shared: "بيئة مشتركة تعزز Documents وPresentations وSpreadsheets.",
    lite: "يمكن استخدام Lite دون تنزيل هذه الحزمة.",
    unavailable: "لا تتوفر حزمة تم التحقق منها بعد.",
    install: "تثبيت",
    offline: "استيراد حزمة دون اتصال",
    cancel: "إلغاء التنزيل",
    repair: "تحقق / إصلاح",
    rollback: "استخدام هذا الإصدار",
    remove: "إزالة",
    close: "إغلاق",
    follow: "متابعة التغييرات",
    page: "الصفحة",
    zoom: "التكبير",
    sheet: "ورقة",
    selection: "التحديد",
    note: "تعليق",
    addNote: "إضافة إلى الرسالة",
    region: "اسحب فوق الصفحة للتعليق على منطقة.",
    preview: "معاينة",
    version: "الإصدار",
    loading: "جارٍ تحميل المستند…",
    editing: "مسودة غير محفوظة",
    saved: "تم الحفظ",
    saving: "جارٍ الحفظ…",
    opening: "جارٍ الفتح…",
    conflict: "تم تعديل الملف خارجيًا",
    recovering: "جارٍ الاستعادة…",
    failed: "يتطلب الانتباه",
    closed: "مغلق",
    select: "اختر فقرة أو كائنًا أو خلية",
    noPreview: "بانتظار عرض المحتوى…",
    range: "نطاق الخلايا",
    sharedBy: "مشترك بين",
    working: "جارٍ التثبيت…",
    slides: "الشرائح",
    cellLimit:
      "يشمل تحديد الخلايا A1:Z50 في كل ورقة؛ وتستخدم المعاينة مناطق الطباعة المحددة في المستند.",
  },
  hi: {
    paragraph: "अनुच्छेद",
    object: "ऑब्जेक्ट",
    regionSelection: "पेज का क्षेत्र",
    runtime: "Office क्षमता पैक",
    deactivate: "तीनों प्लगइन में Lite का उपयोग करें",
    shared:
      "एक साझा रनटाइम Documents, Presentations और Spreadsheets की क्षमताएँ बढ़ाता है।",
    lite: "इस डाउनलोड के बिना भी Lite उपलब्ध है।",
    unavailable: "अभी कोई सत्यापित पैक उपलब्ध नहीं है।",
    install: "इंस्टॉल करें",
    offline: "ऑफ़लाइन पैक आयात करें",
    cancel: "डाउनलोड रद्द करें",
    repair: "जाँचें / सुधारें",
    rollback: "इस संस्करण का उपयोग करें",
    remove: "हटाएँ",
    close: "बंद करें",
    follow: "बदलावों का अनुसरण करें",
    page: "पेज",
    zoom: "ज़ूम",
    sheet: "शीट",
    selection: "चयन",
    note: "टिप्पणी",
    addNote: "संदेश में जोड़ें",
    region: "किसी क्षेत्र पर टिप्पणी करने के लिए पेज पर खींचें।",
    preview: "पूर्वावलोकन",
    version: "संस्करण",
    loading: "दस्तावेज़ लोड हो रहा है…",
    editing: "ड्राफ़्ट सहेजा नहीं गया",
    saved: "सहेजा गया",
    saving: "सहेजा जा रहा है…",
    opening: "खोला जा रहा है…",
    conflict: "फ़ाइल बाहर से बदली गई",
    recovering: "पुनर्प्राप्त किया जा रहा है…",
    failed: "ध्यान देना ज़रूरी है",
    closed: "बंद",
    select: "अनुच्छेद, ऑब्जेक्ट या सेल चुनें",
    noPreview: "सामग्री के रेंडर होने की प्रतीक्षा…",
    range: "सेल रेंज",
    sharedBy: "साझा प्लगइन",
    working: "इंस्टॉल हो रहा है…",
    slides: "स्लाइड",
    cellLimit:
      "सेल चयन प्रत्येक शीट में A1:Z50 तक है; पूर्वावलोकन दस्तावेज़ के निर्धारित प्रिंट क्षेत्रों का उपयोग करता है।",
  },
  id: {
    paragraph: "Paragraf",
    object: "Objek",
    regionSelection: "Area halaman",
    runtime: "Paket kemampuan Office",
    deactivate: "Gunakan Lite untuk ketiga plugin",
    shared:
      "Satu lingkungan bersama meningkatkan Documents, Presentations, dan Spreadsheets.",
    lite: "Lite tersedia tanpa unduhan ini.",
    unavailable: "Belum ada paket terverifikasi yang tersedia.",
    install: "Instal",
    offline: "Impor paket offline",
    cancel: "Batalkan unduhan",
    repair: "Verifikasi / perbaiki",
    rollback: "Gunakan versi ini",
    remove: "Hapus",
    close: "Tutup",
    follow: "Ikuti perubahan",
    page: "Halaman",
    zoom: "Zoom",
    sheet: "Lembar",
    selection: "Pilihan",
    note: "Komentar",
    addNote: "Tambahkan ke pesan",
    region: "Seret pada halaman untuk mengomentari suatu area.",
    preview: "Pratinjau",
    version: "Versi",
    loading: "Memuat dokumen…",
    editing: "Draf belum disimpan",
    saved: "Tersimpan",
    saving: "Menyimpan…",
    opening: "Membuka…",
    conflict: "File diubah dari luar",
    recovering: "Memulihkan…",
    failed: "Perlu perhatian",
    closed: "Ditutup",
    select: "Pilih paragraf, objek, atau sel",
    noPreview: "Menunggu perenderan konten…",
    range: "Rentang sel",
    sharedBy: "Dibagikan oleh",
    working: "Menginstal…",
    slides: "Slide",
    cellLimit:
      "Pilihan sel mencakup A1:Z50 tiap lembar; pratinjau memakai area cetak yang ditetapkan dalam dokumen.",
  },
};
export function officeCopy(locale: AppLocale): typeof en {
  return translations[locale];
}
