import type { AppLocale } from "@artemis/protocol";

// summary, collapse all, expand all, more, locate, edit, save, cancel,
// input hint, send request, stale-location notice, remove comment, show fewer
type Copy = readonly [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
];
const copy: Record<AppLocale, Copy> = {
  en: [
    "{count} comments · {files} files",
    "Collapse all",
    "Expand all",
    "Show {count} more comments",
    "Show location",
    "Edit comment",
    "Save",
    "Cancel",
    "Add context, or send the comments…",
    "Please address the attached Office comments.",
    "This comment refers to an earlier document version. Its location may have changed.",
    "Remove comment",
    "Show fewer",
  ],
  "zh-CN": [
    "{count} 处批注 · {files} 个文件",
    "全部折叠",
    "全部展开",
    "展开其余 {count} 条批注",
    "查看位置",
    "编辑批注",
    "保存",
    "取消",
    "补充说明，或直接发送批注…",
    "请处理附件中的 Office 批注。",
    "此批注对应的文档版本已变化，原位置可能失效。",
    "移除批注",
    "收起更多批注",
  ],
  "zh-TW": [
    "{count} 處批註 · {files} 個檔案",
    "全部摺疊",
    "全部展開",
    "展開其餘 {count} 條批註",
    "查看位置",
    "編輯批註",
    "儲存",
    "取消",
    "補充說明，或直接傳送批註…",
    "請處理附件中的 Office 批註。",
    "此批註對應的文件版本已變更，原位置可能失效。",
    "移除批註",
    "收起更多批註",
  ],
  ja: [
    "コメント {count} 件 · ファイル {files} 件",
    "すべて折りたたむ",
    "すべて展開",
    "残り {count} 件を表示",
    "位置を表示",
    "コメントを編集",
    "保存",
    "キャンセル",
    "説明を追加、またはコメントを送信…",
    "添付の Office コメントに対応してください。",
    "文書のバージョンが変わったため、コメントの位置が異なる可能性があります。",
    "コメントを削除",
    "表示を減らす",
  ],
  ko: [
    "주석 {count}개 · 파일 {files}개",
    "모두 접기",
    "모두 펼치기",
    "주석 {count}개 더 보기",
    "위치 보기",
    "주석 편집",
    "저장",
    "취소",
    "설명을 추가하거나 주석을 보내세요…",
    "첨부된 Office 주석을 처리해 주세요.",
    "문서 버전이 변경되어 주석 위치가 달라졌을 수 있습니다.",
    "주석 삭제",
    "간략히 보기",
  ],
  es: [
    "{count} comentarios · {files} archivos",
    "Contraer todo",
    "Expandir todo",
    "Mostrar {count} comentarios más",
    "Ver ubicación",
    "Editar comentario",
    "Guardar",
    "Cancelar",
    "Añade contexto o envía los comentarios…",
    "Atiende los comentarios de Office adjuntos.",
    "La versión del documento ha cambiado; la ubicación puede ser distinta.",
    "Eliminar comentario",
    "Mostrar menos",
  ],
  fr: [
    "{count} commentaires · {files} fichiers",
    "Tout réduire",
    "Tout développer",
    "Afficher {count} autres commentaires",
    "Voir l’emplacement",
    "Modifier le commentaire",
    "Enregistrer",
    "Annuler",
    "Ajoutez du contexte ou envoyez les commentaires…",
    "Veuillez traiter les commentaires Office joints.",
    "La version du document a changé ; l’emplacement peut être différent.",
    "Supprimer le commentaire",
    "Afficher moins",
  ],
  de: [
    "{count} Kommentare · {files} Dateien",
    "Alle einklappen",
    "Alle ausklappen",
    "{count} weitere Kommentare anzeigen",
    "Position anzeigen",
    "Kommentar bearbeiten",
    "Speichern",
    "Abbrechen",
    "Kontext ergänzen oder Kommentare senden…",
    "Bitte bearbeite die beigefügten Office-Kommentare.",
    "Die Dokumentversion hat sich geändert; die Position kann abweichen.",
    "Kommentar entfernen",
    "Weniger anzeigen",
  ],
  "pt-BR": [
    "{count} comentários · {files} arquivos",
    "Recolher tudo",
    "Expandir tudo",
    "Mostrar mais {count} comentários",
    "Ver localização",
    "Editar comentário",
    "Salvar",
    "Cancelar",
    "Adicione contexto ou envie os comentários…",
    "Atenda aos comentários do Office anexados.",
    "A versão do documento mudou; a localização pode ser diferente.",
    "Remover comentário",
    "Mostrar menos",
  ],
  it: [
    "{count} commenti · {files} file",
    "Comprimi tutto",
    "Espandi tutto",
    "Mostra altri {count} commenti",
    "Mostra posizione",
    "Modifica commento",
    "Salva",
    "Annulla",
    "Aggiungi contesto o invia i commenti…",
    "Gestisci i commenti Office allegati.",
    "La versione del documento è cambiata; la posizione potrebbe essere diversa.",
    "Rimuovi commento",
    "Mostra meno",
  ],
  ru: [
    "Комментариев: {count} · Файлов: {files}",
    "Свернуть все",
    "Развернуть все",
    "Ещё {count} комментариев",
    "Показать место",
    "Изменить комментарий",
    "Сохранить",
    "Отмена",
    "Добавьте пояснение или отправьте комментарии…",
    "Обработайте приложенные комментарии Office.",
    "Версия документа изменилась; расположение могло измениться.",
    "Удалить комментарий",
    "Показать меньше",
  ],
  ar: [
    "{count} تعليقات · {files} ملفات",
    "طي الكل",
    "توسيع الكل",
    "عرض {count} تعليقات إضافية",
    "عرض الموقع",
    "تعديل التعليق",
    "حفظ",
    "إلغاء",
    "أضف توضيحًا أو أرسل التعليقات…",
    "يرجى معالجة تعليقات Office المرفقة.",
    "تغير إصدار المستند؛ قد يكون الموقع مختلفًا.",
    "إزالة التعليق",
    "عرض أقل",
  ],
  hi: [
    "{count} टिप्पणियाँ · {files} फ़ाइलें",
    "सभी समेटें",
    "सभी खोलें",
    "{count} और टिप्पणियाँ दिखाएँ",
    "स्थान दिखाएँ",
    "टिप्पणी संपादित करें",
    "सहेजें",
    "रद्द करें",
    "संदर्भ जोड़ें या टिप्पणियाँ भेजें…",
    "कृपया संलग्न Office टिप्पणियों पर काम करें।",
    "दस्तावेज़ का संस्करण बदल गया है; स्थान बदल सकता है।",
    "टिप्पणी हटाएँ",
    "कम दिखाएँ",
  ],
  id: [
    "{count} komentar · {files} file",
    "Ciutkan semua",
    "Perluas semua",
    "Tampilkan {count} komentar lagi",
    "Lihat lokasi",
    "Edit komentar",
    "Simpan",
    "Batal",
    "Tambahkan konteks atau kirim komentar…",
    "Tolong tangani komentar Office terlampir.",
    "Versi dokumen telah berubah; lokasinya mungkin berbeda.",
    "Hapus komentar",
    "Tampilkan lebih sedikit",
  ],
};

export function officeAnnotationCopy(locale: AppLocale) {
  const [
    summary,
    collapse,
    expand,
    more,
    locate,
    edit,
    save,
    cancel,
    placeholder,
    request,
    stale,
    remove,
    less,
  ] = copy[locale];
  return {
    summary,
    collapse,
    expand,
    more,
    locate,
    edit,
    save,
    cancel,
    placeholder,
    request,
    stale,
    remove,
    less,
  };
}
